### ISSUE TITLE
`"Microsoft.DotNet.SignTool.SignToolTask" task could not be loaded from the assembly` on arcade 9.0.0-beta.23510.4

### ISSUE THREAD

**Issue by dkurepa** [dotnet/dnceng#1004]
Many repos have started seeing this error https://dev.azure.com/dnceng-public/public/_build/results?buildId=434155&view=logs&j=7c8326b9-0a5f-532a-e6de-db8515c72d9a&t=2f0f1e20-badc-52e7-dbc6-29a52429fc6c in their arcade 9.0.0-beta.23510.4 update PRs.
We need to investigate why this is happening, and unblock them.
What's interesting is that some repos, like winforms, didn't have this error when updating to the same version of arcade https://github.com/dotnet/winforms/pull/10070/files

**Comment by dkurepa** [comment]
@ViktorHofer do you know what might be causing this issue in some repos?

**Comment by dkurepa** [comment]
Think repos having this issue need to update their sdk version in global.json

**Comment by ViktorHofer** [comment]
Yes, probably an SDK, VS or xcopy msbuild update. cc @mmitche

**Comment by ViktorHofer** [comment]
testfx depens xcopy-msbuild while winforms doesn't: https://github.com/microsoft/testfx/blob/4973d5a3d45cb067fc9aabf0011f49974c882fcd/global.json#L21

**Comment by Evangelink** [comment]
> testfx depens xcopy-msbuild while winforms doesn't: [microsoft/testfx@`4973d5a`/global.json#L21](https://github.com/microsoft/testfx/blob/4973d5a3d45cb067fc9aabf0011f49974c882fcd/global.json#L21)

I have tried to update to what msbuild uses in this PR https://github.com/microsoft/testfx/pull/1747/files#diff-8df3cd354bc584349d04ad5675b33c042d8b99b741b8b95af394c55e0f5001bfR21 without much success.

**Comment by rainersigwald** [comment]
> do you know what might be causing this issue in some repos?

The difference is whether the build is driven by `MSBuild.exe` (on full framework) or `dotnet msbuild.dll` (on .NET 8). In the former, the `System.Collections.Immutable` provided by MSBuild is 7.0.0.0.

This is an Arcade bug. The 9.0 version of the signtool package needs to either bump down its SRM/SCI reference, or provide copies.

**Comment by ViktorHofer** [comment]
That's on me. Will submit a PR to fix this.

**Comment by rainersigwald** [comment]
(we'll probably update to 8.0 packages soonish but not for 17.8)

**Comment by ViktorHofer** [comment]
https://github.com/dotnet/arcade/pull/14115

**Comment by dkurepa** [comment]
We're currently unable to rollout a new version of arcade. https://github.com/dotnet/dnceng/issues/997 should unblock us
