### ISSUE TITLE
vs scout images don't include vs workloads required to build a repo

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#1038]
The windows.vs2022.amd64.preview.scout images are missing all the workloads they should have for building. This is most likely a YAML inheritance bug.

As reported in https://helix.dot.net The scouting queues has:

![image](https://github.com/dotnet/dnceng/assets/23242101/baa7ca1c-f393-420a-9ed7-f6bd4a56c5bf)

While the regular preview queue has:

![image](https://github.com/dotnet/dnceng/assets/23242101/eae49982-113b-4027-9635-a300c393fae4)

### Release Note Category

- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

### Release Note Description

Made the VS workloads installed in VS2022 queues and build pools consistent. This adds workloads previously available in windows.vs2022.amd64[.open], windows.vs2022.scout.amd64.open, windows.vs2022preview.amd64[.open], and windows.amd64.vs2022.pre (a build image) to the set on windows.vs2022preview.scout.amd64[.open]. It also adds the few workloads (originally Roslyn-requested) from the windows.vs2022preview.scout.amd64[.open] images to all the rest.

**Comment by riarenas** [comment]
I think it's because https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines?path=/definitions/shared/windows.yaml&version=GBmain&line=1582&lineEnd=1583&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents is missing from the scouting queue definitions.

**Comment by dougbu** [comment]
@rainersigwald, agreed.

we decided to install the same workloads across all VS2022 queues. the workload list will be the union of the "regular" set and those (what Roslyn requested) previously only in the windows.vs2022preview.scout.amd64[.open] queues. this should roll out tomorrow.

**Comment by dougbu** [comment]
oops, ^^ was a comment to you @riarenas

**Comment by dougbu** [comment]
rolled out today
