### ISSUE TITLE
Repo 'dnceng' must link correct Code of Conduct

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#1042]
https://github.com/dotnet/org-policy-violations/issues/5030

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description
No release note lol

**Comment by riarenas** [comment]
Will wait for the policy bot to run again before closing for real.

**Comment by riarenas** [comment]
The policy service determined this violation is resolved. Closing
