### ISSUE TITLE
Project is reaching the limit of issues again

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/dnceng#1047]
we got the following error last week:
<img width="365" alt="image" src="https://github.com/dotnet/dnceng/assets/6895254/617f8907-9802-452f-95c6-f241f59acef5">

I mitigated the situation by changing the last updated date from 14 days to 7 days
<img width="1052" alt="image" src="https://github.com/dotnet/dnceng/assets/6895254/fdad0db4-02a0-4797-8285-c81824fcf806">

what got 22 issues free which was enough to keep us going but we are very close to the limit.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by missymessa** [comment]
@garath maybe we should sit down and start closing old issues in Arcade and that will help free up more stuff in the project.

**Comment by AlitzelMendez** [comment]
theoretically this is the number of issues: https://github.com/orgs/dotnet/projects/86/insights
 ( I don't think it match with what happened but also unsure when this numbers is recorded)

the limit is 1200: https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-items-in-your-project/adding-items-to-your-project , so we should have around of 200 issues now, if the counting is what it says

**Comment by missymessa** [comment]
Also, it's not just issues, but also PRs for some of the repos (Ilya wanted them to show up on the board so that SSA/Ops could take care of the dependency flow PRs).

**Comment by AlitzelMendez** [comment]
oh ok! I created this view with everything: https://github.com/orgs/dotnet/projects/86/insights/3

**Comment by missymessa** [comment]
This is fine for now, but it's possible this will occur happen, and we'll cross that bridge when we come to it.
