### ISSUE TITLE
[Build Analysis Check] Escape mechanism

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/dnceng#1075]
Allow users to override the build analysis status by adding a comment to the pull request or similar that explains why they want to merge on red. 

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Build Analysis now supports a escaped mechanism to change status to Succeeded.

**Comment by AlitzelMendez** [comment]
can we have a table of the comments? or at least have an AI message! people were talking about analyzing this data later

**Comment by missymessa** [comment]
Thoughts about functionality: 
- [ ] The exception will function similar to `/azp run` in which specific text in the comment on the PR will trigger the webhook to turn the Build Analysis check green. 
- [ ] Comment must also contain some content (meaning, a reason must be provided, not just the trigger text alone).
- [ ] The escape will only be valid for the current state of Build Analysis. Meaning that if another commit is made to the PR, it would reset the current state of the Build Analysis check and if failures are detected again, the user will need to provide a new comment to trigger the exception.

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/36673

**Comment by AlitzelMendez** [comment]
rolled out and shared :)
