### ISSUE TITLE
[Known issue validation] Explore other options to improve known issue validation

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/dnceng#1091]
We are still uncertain on how much we will invest on this space; we already offer a complete validation on GitHub issues but it takes time to executes and doesn't feel fluid.

we can probably add this to our landing page, if we only validate the regex and if it matches with a string should be cheaper to achieve, if the expectation is to analyze a build this has more implication, that is the reason we haven't committed to this, just creating the issue because is in our radar. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Created known issues helper on lading page to facilitate the creation of known issues

**Comment by missymessa** [comment]
Example of failing validation: https://github.com/dotnet/runtime/issues/94436

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/37047

This is a very simple helper

**Comment by AlitzelMendez** [comment]
helper: https://helix.dot.net/BuildAnalysis/CreateKnownIssues
