### ISSUE TITLE
New Queues for Performance Team

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#1100]
The performance team is getting some additional hardware as well as wanting to update their existing systems to newer operating systems. We need to create the following queues to support this
- ubuntu.2204.arm64.perf 
    - This queue is to replace the ubuntu.2004.arm64.perf queue
 - windows.11.amd64.viper.perf.open
    - Used to replace windows.11.amd64.tiger.perf.open
 - windows.11.amd64.viper.perf 
    -  Used to replace windows.11.amd64.tiger.perf
 - ubuntu.2204.amd64.viper.perf.open 
    - Used to replace ubuntu.2204.amd64.tiger.perf.open
 - ubuntu.2204.amd64.viper.perf
    - Used to replace ubuntu.2204.amd64.tiger.perf.
 - windows.11.amd64.urchin.perf 
    -  Configuration is similar to windows.11.amd64.viper.perf 
- ubuntu 2204.amd64.urchin.perf
    -  Configuration is similar to ubuntu.2204.amd64.viper.perf

Additionally, we would like to "rename" the windows.11.arm64.perf.surf queue to windows.11.arm64.surf.perf so it aligns with the other queues. There are currently no systems attached to this queue.  

### Release Note Category
- [X] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Adding new queues to support PERFURCHIN and PERFVIPER systems.

**Comment by riarenas** [comment]
@ilyas1974 I need some information here.

What are the values for the PreInstalled image for all of these queues? specifically I need to know the version of the linux kernel these machines are running before I can create the queues.

**Comment by riarenas** [comment]
Also, I believe this needs to be done in two steps?

- [ ] add the new queues
- [ ] At a later date, remove the old queue definitions once machines have been moved to the new queue
Is that correct?

**Comment by riarenas** [comment]
Had some clarification for preinstalled images:

* ubuntu.2204.open.perf: We still need the PreinstalledImage information
* For everything else, copy the configuration exactly from the previous queues.

**Comment by riarenas** [comment]
Even more clarification. This is a chicken and egg problem, we will use the current information from the previous queues initially. That's going to be wrong. After the machines are set up and in the queue, we will go back and fix the values.

**Comment by riarenas** [comment]
@ilyas1974 I see that we also have some perftiger scouting queues, such as Ubuntu.2204.Amd64.Tiger.Perf.Scouting. Do we need scouting viper and/or urchin queues?

**Comment by ilyas1974** [comment]
Not at this time - I have a feeling we'll be keeping those queues long term. The goal is to allow the perf team to test an OS update before it is mass deployed to the production environment. The type of machine this is done on doesn't matter.

**Comment by riarenas** [comment]
Working on this in PR https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/35033

**Comment by riarenas** [comment]
This has rolled out
