### ISSUE TITLE
Reduce `osob-cli.cmd definitions` redundancies

### ISSUE THREAD

**Issue by dougbu** [dotnet/dnceng#1115]
The `osob-cli.cmd definitions` command output includes individual information about every queue and build pool listed in our helix-machines YAML. The result is a 1.71 MB file at the moment. When looking for information about the much smaller number of individual images, this file is cumbersome to say the least. In local experiments, I found the output is only about a third of the original size.

Suggest adding a new `--unique` command line option.

### Release Note Category

- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements

### Release Note Description

Add a new command-line option to an internal tool. Aim was to remove redundancy in a large output file.

**Comment by garath** [comment]
PR [!34712](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/34712)

**Comment by dougbu** [comment]
!34712 change merged. this is an internal tool and doesn't require a roll out
