### ISSUE TITLE
delete private feed proxies and related secrets

### ISSUE THREAD

**Issue by ghost** [dotnet/dnceng#1144]
We no longer use sleet, so we don't need to keep the redirection azure functions, or any other infrastructure related to them. Most importantly, it allows us to remove secrets from the manifests to simplify secret rotations

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by riarenas** [comment]
Secrets have been deleted from manifest. I need to delete some left over azure resources and the secrets themselves from the vault.

**Comment by riarenas** [comment]
Remaining work here is to delete the [dotnetfeedinternalproxy](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/68672ab8-de0c-40f1-8d1b-ffb20bd62c0f/resourceGroups/DotnetFeedInternalProxy/overview) resource group. This requires a SAW. I'll take care of it on Monday.

**Comment by riarenas** [comment]
Resource group has been deleted

**Comment by riarenas** [comment]
Next steps here:
* [ ] delete all references to these secrets from variable groups in dnceng and devdiv
* [ ] Disable and delete the secrets in engkeyvault and dnceng-pipeline-secrets
