### ISSUE TITLE
New Queue to support ppc64le Mainframe

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#1156]
We need to create a new helix queue to support the OS that is currently running on the PPC64le device. 

New Queue Name: ubuntu.2204.ppc64le.experimental.open 
Please use the information in the ubuntu.2004.ppc64le.experimental.open for specifications about the hardware

### Release Note Category
- [X] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Add ubuntu.2204.ppc64le.experimental.open queue

**Comment by riarenas** [comment]
Does ubuntu.2004.ppc64le.experimental.open still have to exist?

**Comment by riarenas** [comment]
@ilyas1974 I need some information here. Specifially:
```
  PreInstalledImage: # This Queue is handled by on-premises, preconfigured
  # machines. The actual deployment of the images is not handled by Helix,
  # and must be triggered by some external mechanism.
  # The values here are to ensure that automation is run on the correct
  # set of machines, and will be enforced by the installer
    System: Windows # Required: Name of this image, as returned by platform.system()
    Processor: ARM64 # Required: Processor architecture, as returned by platform.machine()
    Version: 17.6.0 # Required: Version of the OS, as returned by platform.release()
```

**Comment by riarenas** [comment]
We will rely on the information from the 2004 queue. This is going to be wrong. Once the machines are in the queue, we will go back and fix the YAML.

**Comment by riarenas** [comment]
The queue definition has been merged and will roll out on the next helix-machines deployment.

**Comment by riarenas** [comment]
This has rolled out
