### ISSUE TITLE
Increase RAM of the Ubuntu.2204.Amd64.Open queue definition

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#1163]
Per request from the Runtime team, some of their tests require at least 16gb of ram.

Details in [this internal teams conversation](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1698250585384?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1698250585384&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1698250585384)

- [ ] Create a new queue entry specifically for the native aot tests, based on the [ubuntu.2204.amd64(.open)](https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines?path=/definitions/shared/linux.yaml&version=GBmain&line=1146&lineEnd=1147&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) queue definitions
- [ ] These queues should use D4a_v4 machines, by specifying a [mincores: 4](https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines?path=/definitions/shared/linux.yaml&version=GBmain&line=722&lineEnd=723&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) requirement.
- [ ] We only really need a .rt version of this queue that runs in the runtime Azure subscription. This should be specified in the definition [as seen here](https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines?path=/definitions/shared/linux.yaml&version=GBmain&line=866&lineEnd=867&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents)
- [ ] Once the queue is in staging, contact @kotlarmilos with instructions on how they can point their jobs to the new queue in staging.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Added Ubuntu.2204.Amd64-Extra-Large(.Open).rt queue with 4 cores instead of 2

**Comment by kotlarmilos** [comment]
Providing more context here:
 - The job consistently hit OOM issue after 2h when AOT compiling the `System.Private.CoreLib.dll` when running a docker container based on the `cbl-mariner-2.0-cross-amd64` image
 - The current VMs have a limit on docker containers RAM consumption
 - The same job finishes the compilation successfully within 10min on machine with 32gb of RAM
 - The job belongs to extra-platforms and will not be executed on each PR
 - We don't want to migrate other jobs to the upgraded VMs in order to maintain costs

**Comment by missymessa** [comment]
Let's create a new queue for this work.

**Comment by kotlarmilos** [comment]
Thank you! It would be good to test it before setting up the entire queue. Can we test it on a single machine in the queue before adding more machines?

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/35422

**Comment by AlitzelMendez** [comment]
this has rolled out :) feel free to reopen if you haver any questions
