### ISSUE TITLE
Define CloudTest investment criteria

### ISSUE THREAD

**Issue by chcosta** [dotnet/dnceng#122]
- Feature parity with Helix
  - Automated retries
  - Test case reporting for catastrophic failures
  - Known issues
  - Force_queue (helix-machines feature)
  - tbd
		
- Comparable dollar cost
  - CloudTest [costs](https://eng.ms/docs/more/developer-guides/cloudtest-user-guide/cloudtest/how-tos/ap-to-azure-cost-estimate) / month
    - Machine hours
    - Sku
    - Region
    - Pre-provisioning enabled?
  - Helix costs / month

- Ongoing cost (dev hours)
  - CloudTest
  - Unauthenticated CloudTest service layer 
  - Helix servicing (SSA and rollouts)
  - Helix feature work (customer feature requests, evolving security requirements, etc…)
		
- Investment costs (dev hours)
  - Unauthenticated CloudTest service layer implementation
  - Migration cost estimate
    - Cost to move Runtime
      - Test authoring
      - Image availability
        - Customizations
          - Visual Studio versions
          - Visual Studio preview versions
          - Artifacts
        - Device support
      - Cost to move dnceng owned repos
      - total repos / branches to move

**Comment by chcosta** [comment]
Reassigning to @epananth .

@chcosta to add more context here and provide a more explicit direction.

**Comment by epananth** [comment]
this is done. Closing this one
