### ISSUE TITLE
Remove "from arcade" where it makes no sense

### ISSUE THREAD

**Issue by dougbu** [dotnet/dnceng#124]
As seen at https://github.com/dotnet/dnceng/blob/6f53ce75c5c8ffa095c859556979bf8aca1de162/eng/enforce-issue.ps1#L40 and similar locations in our other copies, this script writes a non-sensical error e.g.,

``` text
Error fetching issue dotnet/dnceng#12345 from arcade. Does it exist?
```

As a low-priority cleanup item, we should remove "from arcade" here.

### Release Note Category
- [ ] Feature changes/additions 
- [x] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
n/a

**Comment by garath** [comment]
Oh, good catch. This seems appropriate for the Ownership Alignment epic. @dkurepa, @missymessa what do you think?

**Comment by dougbu** [comment]
/btw how many copies of this file do we have and does anything synchronize them❔ I'm thinking of adding a checklist to the issue description so we can keep track (likely reopening the issue repeatedly until we fix things everywhere).

**Comment by missymessa** [comment]
PR for dotnet-helix-service here: https://dnceng.visualstudio.com/internal/_git/dotnet-helix-service/pullrequest/32129

**Comment by missymessa** [comment]
PR for dotnet/dnceng: https://github.com/dotnet/dnceng/pull/272
