### ISSUE TITLE
Stop using pool providers and instead use Azure Virtual Machine Scale Set Agents

### ISSUE THREAD

**Issue by dotnet-bot** [dotnet/dnceng#1246]
Migrated from https://github.com/dotnet/core-eng/issues/9944

@Chrisboh wrote:

Casey just informed me that AzDo has released a new feature that would remove our need to maintain our own pool providers and instead let AzDo automatically scale machines on our behalf.  The added benefit we get from this is that they will delete and create a new machine for us after every build.  I am sure there are also possible drawbacks to leveraging this feature but I do feel it is something worth exploring.

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops#use-scale-set-agent-pool

@ulisesh as an FYI

**Comment by dougbu** [comment]
This issue feels like it's done. We don't implement our own pool providers and instead use 1ES hosted pools. Thoughts @riarenas❔
