### ISSUE TITLE
DotCJade06 is disabled

### ISSUE THREAD

**Issue by garath** [dotnet/dnceng#1258]
Machine DotCJade-06 in queue windows.server.arm64.perf has been taken offline at request of @LoopedBard3

**Comment by garath** [comment]
Except... this machine and queue are not found in the inventory. A mystery!

**Comment by garath** [comment]
Helix was happy to disable the machine though.

**Comment by garath** [comment]
It is now back online.

**Comment by AlitzelMendez** [comment]
it was requested again to put this machines offline

**Comment by AlitzelMendez** [comment]
It is now back online.
