### ISSUE TITLE
Build monitoring now supports simple prefix pattern matching

### ISSUE THREAD

**Issue by premun** [dotnet/dnceng#126]
Add the possibility to match branches by prefix when detecting failing builds.

Needed for matching all `release/*` branches (https://github.com/dotnet/dnceng/pull/110)

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Build monitoring now supports simple prefix pattern matching

**Comment by missymessa** [comment]
@premun did your PR resolve this issue?
