### ISSUE TITLE
Publishing to symbol-feeds 

### ISSUE THREAD

**Issue by epananth** [dotnet/dnceng#1270]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Publishing to symbols-feeds is really slow. So we discontinued publishing to symbol-feeds. Except for stable builds and the stable packages from those builds.( We still publish to darc-pub-sym)

Note : we cannot publish stable builds to storage cos their paths will get overwritten. 

Fix to try : 

1)  By making symbol packages always have non-stable version numbers, but his has to be investigated . (does it matter if they differ in version number from the non-symbol package?) etc.

cc: @mmitche

**Comment by missymessa** [comment]
This issue is pretty old. If it continues to be an issue, we can reopen/recreate.
