### ISSUE TITLE
Symbol Upload to Nuget feed is slow

### ISSUE THREAD

**Issue by epananth** [dotnet/dnceng#1276]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

For Stable builds, symbols upload to Nuget feeds is extremely slow. 

Build : https://dev.azure.com/dnceng/internal/_build/results?buildId=950931&view=logs&j=226748d0-f812-5437-d3f0-2dd291f5666e&t=bad11196-972e-5d03-45a8-9db526506073

Maestro promotion build : https://dnceng.visualstudio.com/internal/_build/results?buildId=951405&view=results

Time it took to publish artifacts : 50m05s
Total Build time : 3h 52m 22s

cc: @mmitche

**Comment by missymessa** [comment]
This issue is pretty old. If this is still a problem, we can reopen/create a new one.
