### ISSUE TITLE
Notify authors when other Arcade validation gates fail

### ISSUE THREAD

**Issue by dotnet-bot** [dotnet/dnceng#128]
Migrated from https://github.com/dotnet/core-eng/issues/12374

@missymessa wrote:

In an effort to improve investigations and visibility of Arcade validation failures we want to create a mechanism that will notify any authors of code that has been merged into the version of Arcade currently being validated (since the last version that was promoted to `.NET Eng - Latest` channel) if failures occur in the following areas: 
- Dependency flow PRs into Arcade Validation from Arcade
- Regular Arcade Validation Official Build pipeline runs
- ~~Arcade Validation for Promotion (or future incarnation of this) pipeline runs.~~

The mechanism can operate much like how Build Monitor does today by creating a GitHub issue and notifying (either by tagging or assigning) the authors on the issue.

**Comment by missymessa** [comment]
Since I wrote this issue, failures that occur in Arcade Validation due to changes in Arcade don't occur often enough to have this kind of mechanism, and the investigation is usually straight-forward in determining what caused the failure. I'm going to close this one.
