### ISSUE TITLE
Cost of Helix

### ISSUE THREAD

**Issue by epananth** [dotnet/dnceng#1280]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Get the cost of the following 
- [ ] Helix machine and Helix services - Cost includes the following ( No of devs + Dev time spent on the following)
                                                              1) Feature work 
                                                               2) Bug fixes 
                                                               3) Rollouts 
                                                               4) Servicing 
                                                               5) SSA
                                                               6) Pre and post re-org 

- [ ] The work with DDFUN to maintain our on premises hardware and the work DDFUN do.  

@epananth to find out 
- [ ] Does CloudTest bill us any different way? If yes, how is it different? 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by ilyas1974** [comment]
We have created a dashboard - https://msit.powerbi.com/groups/de8c4cb8-b06d-4af8-8609-3182bb4bdc7c/reports/f7d76a57-6783-4656-a739-fb8ebaf6307b/ReportSection?experience=power-bi that shows the machine cost for helix. As the service continues to change, please open another issues whenever this information is needed for updates.
