### ISSUE TITLE
Make Rollout Scorer more maintainable 

### ISSUE THREAD

**Issue by dotnet-bot** [dotnet/dnceng#131]
Migrated from https://github.com/dotnet/core-eng/issues/11154

@jonfortescue wrote:

This issue is non-critical, it'll simply be a slight annoyance for me to have to close PRs and delete a line from the database every day between now and the next helix-machines rollout.

The 10/7 helix-machines rollout lasted through 10/9 which is over the two day buffer period that we have in place for when to score a rollout. The scorer correctly waited until [10/12 at midnight UTC to score the 10/7 rollout](https://github.com/dotnet/core-eng/pull/11130/); however on 10/13 at midnight it [scored a 10/9 rollout](https://github.com/dotnet/core-eng/pull/11153/) consisting of the single build that happened outside the two day window.

I think this is because the scorer determines discrete rollouts based on the last day of a rollout (10/7) rather than the last time a rollout was scored (10/12).

**Comment by missymessa** [comment]
I think @AlitzelMendez did some work to make this better recently, so maybe we don't need this issue. We can open new issues for specific bugs as we encounter them.
