### ISSUE TITLE
Remove Component.GitHub.Copilot from vs2022 images

### ISSUE THREAD

**Issue by dougbu** [dotnet/dnceng#1315]
From a [First Responders Teams conversation](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1698189803236?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1698189803236&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1698189803236), we have learned the `Component.GitHub.Copilot` component added in recent VS 17.8 preview releases causes interactive test failures. Solution should mimic https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/501712?_a=files.

Would be ideal to remove the component in every VS image or every VS2022 image to make `ArtifactBelongingTests` additions easy and avoid problems when 17.8 moves to our regular (non preview) VS2022 images.

### Release Note Category

- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

### Release Note Description

Removed the `Component.GitHub.Copilot` VS component from many images, including windows.vs2022preview.amd64[.open] and windows.vs2022preview.scout.amd64[.open].

**Comment by dougbu** [comment]
run a quick "all VS images" test w/ [!34883](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/34883). will scope that down as necessary&hellip;

**Comment by riarenas** [comment]
Ah, there's mention of offline conversations that probably have the answer to my question. Carry on.

**Comment by dougbu** [comment]
> I saw the FR chat, but it wasn't clear which team is blocked by our current set of workloads? Do we know if the teams that do UI testing expect this component to be there, or for it to be explicitly gone?

bottom line: it's not a blocker exactly but their workaround has a noticeable performance downside. removing the component aligns w/ approach taken elsewhere

**Comment by dougbu** [comment]
Unassigning myself from this. About to create an issue and put up a related PR but won't deal w/ the meat of the problems unless I'm on Ops.

**Comment by dougbu** [comment]
oops, never mind. this is just waiting for rollout and I commented on the wrong issue.

**Comment by dougbu** [comment]
confirmed rollout
