### ISSUE TITLE
Investigate helix-machines failures.

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#1317]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

https://dnceng.visualstudio.com/internal/_build/results?buildId=2160719&view=results

latest build was a mess. A lot of images failed. Investigate and try to figure out.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by dougbu** [comment]
I suggest closing this b/c all of the work seems to be covered in other issues. If some of the issues remain open in dotnet/arcade, suggest moving them to dotnet/dnceng. I did this for #1320.

**Comment by dougbu** [comment]
Oh, none of the other issues referenced above remain open. #1320 is all we have left.

**Comment by ilyas1974** [comment]
As there are just other issues being referenced here, I am going to close this issue.
