### ISSUE TITLE
Add the Job/WorkItem hash into our DB

### ISSUE THREAD

**Issue by dotnet-bot** [dotnet/dnceng#132]
Migrated from https://github.com/dotnet/core-eng/issues/10969

@ChadNedzlek wrote:

When things go badly on machines, usually all we have is the "D:\word\HASH\w\HASH", which is hard to turn back into a real job.

Let's write down those hashes into our DB or something so it's easy to figure out which job did the bad thing.

**Comment by garath** [comment]
This is stale and unlikely to be done. Closing.
