### ISSUE TITLE
Keep helix-machines up to date

### ISSUE THREAD

**Issue by dougbu** [dotnet/dnceng#1340]
the helix-machines repo uses Arcade bits that are really out of date. that makes local builds painful (required .NET SDK isn't auto-installed et cetera) and we aren't keeping up w/ .NET SDK releases, opening us up to vulnerabilities in the stack. would also be great to have current and usable YAML templates to make the various pipelines' YAML readable

### Release Note Category

- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements

### Release Note Description

moved our image creation repository to use current Arcade and Helix SDKs. going forward, we will update dependencies like any other Arcade-ified repo

**Comment by dougbu** [comment]
[!35018](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/35018) currently blocked due to build failures. may be better to wait for .NET 8 GA and use the '.NET 8 Eng' channel instead. Leaving the PR open but unassigning myself here&hellip;

/cc @garath @ilyas1974

**Comment by garath** [comment]
Super excited to move this repo to .NET 8.

**Comment by dougbu** [comment]
let's see if you break my PR before it breaks itself due to packages that aren't `net8.0` compatible 😄

**Comment by dougbu** [comment]
``` text
> darc get-subscriptions --target-repo dotnet-helix-machines
https://github.com/dotnet/arcade (.NET 8 Eng) ==> 'https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines' ('main')
  - Id: aff5607e-7a49-4e6d-6bc5-08dbe7c92a57
  - Update Frequency: EveryWeek
  - Enabled: True
  - Batchable: False
  - PR Failure Notification tags:
  - Merge Policies:
    Standard
  - Last Build: 20231114.4 (0aaeafef60933f87b0b50350313bb2fd77defb5d)
```
and, as expected, it hasn't triggered yet. must wait for next arcade-validation update to the '.NET 8 Eng' channel

**Comment by dougbu** [comment]
done :grin:
