### ISSUE TITLE
Use DependancyInjection in all services that use AzureDevOpsClient

### ISSUE THREAD

**Issue by dkurepa** [dotnet/dnceng#137]
Currently we have two ways of creating the AzureDevOpsClient, via DependancyInjection and via AzureDevOpsClient factory. It might be better to always use DependancyInjection

**Comment by missymessa** [comment]
I don't see this taking priority any time soon. If folks are working in the code and wish to refactor it then, they're more than welcome to. We can reopen this issue if we need to.
