### ISSUE TITLE
Use a virtual environment for helix-scripts/

### ISSUE THREAD

**Issue by dougbu** [dotnet/dnceng#1371]
Our Helix Python code is quite dependent on the Python packages installed along w/ the OS in most Linux distributions. In addition, `cloud-init` is a consistent Python-based package installed in most Linux systems in Azure. We do not currently separate ourselves from that default installation at all. Worse, even if we chose the newest `python3` executable on a system (see #436), we end up sharing common package directories w/ the system.

The first step in #1363 is to move our Python use into a virtual environment. This will allow us to installer newer `python3` executables `pip` and other Python packages based on our own requirements, not the stability requirements of most OS vendors.

### Release Note Category

- [x] Feature changes/additions
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

### Release Note Description

Moved our team's Python infrastructure into a `venv`, isolating us from the system. This should have minimal impact on customers because existing `python3` executables and system-installed Python packages are not changing. However, if you use `python3` in your pipelines and Helix jobs, some Python packages may be missing. Please let us know if you hit issues and are unable to use a `venv` (preferably in the Helix work item folder or build root).

**Comment by garath** [comment]
Looks like this broke at least one customer. See [build 2329162](https://dev.azure.com/dnceng/internal/_build/results?buildId=2329162&view=logs&j=b65b05e1-c985-593c-6ffc-1fb9e008884e&t=5e10b7c2-5974-53b8-808b-5a4ba33175a0).

**Comment by dougbu** [comment]
> Looks like this broke at least one customer. See [build 2329162](https://dev.azure.com/dnceng/internal/_build/results?buildId=2329162&view=logs&j=b65b05e1-c985-593c-6ffc-1fb9e008884e&t=5e10b7c2-5974-53b8-808b-5a4ba33175a0). Teams FR converation [here](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1701818703360?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1701818703360&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1701818703360).

/fyi we resolved this conversation through helping the customer set up their own `venv`.
