### ISSUE TITLE
Maestro build promotion pipeline broken in DevDiv

### ISSUE THREAD

**Issue by dkurepa** [dotnet/dnceng#1393]
Since Yesterday, the Maestro Build Promotion pipeline has been failing with the same error: 
`Could not fetch access token for AAD. Error: Value cannot be null.\r\nParameter name: nodeInstanceName` https://dev.azure.com/devdiv/DevDiv/_build?definitionId=12603&_a=summary
when it's attempting to download secrets from a keyvault specified in the variable group.
Everything looks ok with the ServiceConnection we're using.
I created an ICM with AzDo to get this resolved: https://portal.microsofticm.com/imp/v3/incidents/incident/439788317/summary

**Comment by dkurepa** [comment]
I've been contacted by a person from the AzDo team.
They think it's a bug with the identity federation way of authenticating, and have asked us to revert back to the secret schema. According to the [docs](https://devblogs.microsoft.com/devops/public-preview-of-workload-identity-federation-for-azure-pipelines/#:~:text=You%20can%20roll%20back%20from%20a%20conversion%20to%20use%20a%20secret%20by%20clicking%20the%20revert%20link%20on%20the%20service%20connection%20details%20page%3A), there should be a button for doing that but I don't see it. @mmitche can you see it? You're listed as the service connection creator

**Comment by premun** [comment]
So apparently this has been fixed by AzDO turning off a feature flag. 

cc @ilyas1974
