### ISSUE TITLE
dotnet-eng-status-staging bot is not applying labels to alert issues

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#1427]
Alerting issues opened from alerts in staging do not have labels applied to them so that they are routed correctly and instead, end up in triage. Let's ensure that there is parity between how staging alert issues are created and prod alert issues. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description

**Comment by AlitzelMendez** [comment]
the bot wasn't installed and it didn't have so permission so it wasn't able to put the labels, this has been fixed as can be seen in: https://github.com/dotnet/dnceng/issues/1462

closing
