### ISSUE TITLE
Get a haircut

### ISSUE THREAD

**Issue by dougbu** [dotnet/dnceng#1429]
### Release Note Category

- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements

### Release Note Description

Got a haircut.

**Comment by missymessa** [comment]
Make sure this goes on your Connect

**Comment by dougbu** [comment]
Would have done if that was incomplete. Something to remember in 6 months.

**Comment by garath** [comment]
Did you get a review first? I don't remember seeing any invite on my calendar...

**Comment by michellemcdaniel** [comment]
Looks like an internal infra improvement to me

**Comment by dougbu** [comment]
Thanks @michellemcdaniel, I reclassified the issue. @garath it'll be reviewed when my wife gets back in town tomorrow, same time as the official rollout

**Comment by garath** [comment]
Okay as long as LT approves then I'll sign-off too.

**Comment by chcosta** [comment]
why are we wasting time on this.  Please make sure this gets triaged, I didn't see this as one of our business priorities.

**Comment by dougbu** [comment]
rolled out successfully late yesterday
