### ISSUE TITLE
Clean up the Firewall rules for maestro-prod SQL server

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/dnceng#1479]
The [maestro-prod](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/68672ab8-de0c-40f1-8d1b-ffb20bd62c0f/resourceGroups/maestro/providers/Microsoft.Sql/servers/maestro-prod/networking) SQL server has multiple firewall rules set up for IP addresses outside the corpnet (usually to be able to access the BAR database from a home office). It'd be great to clean up the rules.
We have a documentation that describes how to add the firewall rule [Accessing-the-BAR-(BuildAssetRegistry)-database](https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1009/Accessing-the-BAR-(BuildAssetRegistry)-database) and it has "Delete the firewall rule once you're done for increased safety".

Discussed with @ilyas1974 .

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Not release notes worthy

**Comment by garath** [comment]
FWIW some tooling, like SSMS, will add this firewall exception on behalf of the user. This is convenient, but it does hide what actually happens so it becomes easy to forget to remove the exception afterwords.

**Comment by garath** [comment]
I've removed all firewall exceptions.
