### ISSUE TITLE
Failures when running secretNotifier

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#1491]
The [secretNotifier](https://dnceng.visualstudio.com/internal/_git/dotnet-helix-service?path=/src/ServiceFabric/Helix/WebJobs/SecretNotifier/SecretNotifier.cs&version=GBmain&_a=contents) web job in helix-service has been failing to run due to nullrefs.

I don't have much more information on what is failing other than this stack trace:

```
Exception thrown while attempting to do notifications for Azure.Security.KeyVault.Secrets.SecretClient: System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.Helix.WebJobs.SecretNotifier.LoadSecretsFromVault(SecretClient keyVaultClient) in S:\src\ServiceFabric\Helix\WebJobs\SecretNotifier\SecretNotifier.cs:line 198
at Microsoft.Helix.WebJobs.SecretNotifier.LoadSecretsFromVault(SecretClient keyVaultClient) in S:\src\ServiceFabric\Helix\WebJobs\SecretNotifier\SecretNotifier.cs:line 177
at Microsoft.Helix.WebJobs.SecretNotifier.RunAsync(CancellationToken token) in S:\src\ServiceFabric\Helix\WebJobs\SecretNotifier\SecretNotifier.cs:line 58
```
This seems to have started on 11/16

I used [this app insights query](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fdotnet-eng-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fdotnet-eng/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAAz2OwU7DMBBE73zFKh%252Fg3Cv1gBASApFDI8EROc6kWcnxVus1bRAfj1Og15nRe2PqA%252FLdN51nKChEKePHQSI6v4D2e2omPyiHXfuEyJf2HcOzDD30kwPaVw4qWSZz19b9ttn1CArrxHhiaHPDL8jZH0Gzz9Q8XgJOxpLIZpVzqhuOIG%252BGpebpSCY0CqUrJvhtmmkSpfuvotgkRdlW94L1zZdof9p%252F%252FUNkJNtRv%252BZKdF2J8YCp3kgBN%252Ff2TXSE0rCScT1ofjnRiBx%252BAEiv%252FOcbAQAA/timespan/2023-09-01T17%3A33%3A51.000Z%2F2023-11-28T17%3A33%3A51.937Z)

### Release Note Category
- [ ] Feature changes/additions 
- [x] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Fix model mapping for KeyVault references in SecretNotifier

**Comment by AlitzelMendez** [comment]
This looks super related with these changes: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/35217?_a=files&path=/src/ServiceFabric/Helix/WebJobs/SecretNotifier/SecretNotifier.cs / my guess is that there are some problems with SecretClient, how we are setting this up

**Comment by garath** [comment]
Ah! It looks like this was my break. I'll take a look!

**Comment by garath** [comment]
PR: [!35724](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/35724)

**Comment by garath** [comment]
@ilyas1974 FYI, found the issue and the PR is in the system.
