### ISSUE TITLE
Helix workitems with no output

### ISSUE THREAD

**Issue by chcosta** [dotnet/dnceng#15]
There are a number of Helix workitems that are returning exit code 1, but not displaying any console output which makes it difficult to reason about the quality of the branch, see https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1684358766264?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1684358766264&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1684358766264

**Comment by missymessa** [comment]
@hoyosjs are you still having this issue?

**Comment by hoyosjs** [comment]
It was still happening last week with very specific queues, but there's not a lot of runs to go against.

**Comment by missymessa** [comment]
@hoyosjs do you recall which queues are having this issue? Might help in figuring out if there's something specific to those queues causing the problem.
