### ISSUE TITLE
See if we can leverage CloudMine for querying GitHub issues

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#1500]
The Runtime team would like the ability to look up any PRs that had a failing Build Analysis check overridden via the escape mechanism. We should see if the CloudMine database would already be collecting the data we'd need and if it is, come up with a query so that the Runtime team can look up that information. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by missymessa** [comment]
We can! Will write up documentation for customers for how to use it after the feature is completed.

**Comment by AlitzelMendez** [comment]
Started looking into this and wrote the [query](https://dataexplorer.azure.com/clusters/1es/databases/GitHub?query=H4sIAAAAAAAAA0WOQQrCQBAEvzLkpBBR8BxBcxWV%2FGB0m81KshNnJ4aIj5fkEK%2Fd1VTf%2Bqap8OqRrMI7YCilbRGNvjTUUFCpYIM7Gh2Ivaz2O7deyqt6juHDFiSexYdIRUGZE4uwbKFO4kZKxmppCFZTtr3zxtMEdCpPPOxvyalCJymY6HjhFvm8ntLpHHS2%2FAAA%2BBANtQAAAA%3D%3D) I will add this to power bi once we roll out the feature

**Comment by AlitzelMendez** [comment]
Added this to power bi: https://msit.powerbi.com/groups/de8c4cb8-b06d-4af8-8609-3182bb4bdc7c/reports/f7bf2957-c550-4f52-8e3d-adf3ed35cda2/ReportSection1fd09e40b8a707271300?experience=power-bi but right now is empty, closing as has been handle!
