### ISSUE TITLE
[Grafana] Error while logging into Grafana

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/dnceng#1506]
https://dotnet-eng-grafana.westus2.cloudapp.azure.com

<img width="233" alt="image" src="https://github.com/dotnet/dnceng/assets/6895254/f5e471f6-ad7d-413d-9eb7-0ba011cd2e26">

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by garath** [comment]
Now resolved. Looks like a simple expired secret.
