### ISSUE TITLE
Add gh package to ubuntu machines

### ISSUE THREAD

**Issue by mmitche** [dotnet/dnceng#1514]
Need the 'gh' package for use in the source build release pipeline. This package is available in the 1es images, but the 1es images do not have enough disk space to handle source build releases.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

### Release Note Description

Add the GitHub CLI to standard set of ubuntu package artifacts. Required for release infra.

**Comment by mmitche** [comment]
https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/35803

**Comment by dougbu** [comment]
marking this as blocked b/c errors finding `gh` package are still occurring

**Comment by dougbu** [comment]
to fix this will need to redo fix in some more reliable fashion

**Comment by dougbu** [comment]
must roll out together w/ fix for #1865

**Comment by dougbu** [comment]
done :grin:
