### ISSUE TITLE
Rotation Apple Signing Certificate

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#1515]
It's time for us to rotate the certificate associated with our Apple Developer account. Details on what needs to be done can be found at https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/862/Apple-(iOS-tvOS)-signing-certificates. 

As each machine needs to have the new certificate applied to it we would like this work done during Prague business hours - when usage of these machines is low. 

We have until 12/9 to complete this work.

**Comment by dkurepa** [comment]
The mlskvm portal is having some certificate issues currently: opened up an icm https://portal.microsofticm.com/imp/v3/incidents/incident/448138436/summary

**Comment by dkurepa** [comment]
I have created a new certificate and provisioning profiles, and uploaded those to the storage account in the instructions.

**Comment by dkurepa** [comment]
The script has been run on all machines in all queues, most have finished, a few queues are still running.
Per instructions, started https://dev.azure.com/dnceng-public/public/_build/results?buildId=491968&view=results for validation

**Comment by dkurepa** [comment]
Queue list with status:
- [ ] osx.1200.amd64.open
- [ ] osx.1200.arm64.open
- [ ] osx.13.amd64.open
- [ ] osx.13.amd64.appletv.open
- [ ] osx.13.amd64.iphone.open
- [ ] osx.1015.amd64.iphone.perf
- [ ] osx.1100.amd64.open
- [ ] osx.13.amd64
- [ ] osx.1200.amd64
- [ ] osx.1100.amd64
- [ ] osx.13.arm64.open
- [ ] osx.1200.arm64
- [ ] osx.1100.arm64.open
- [ ] osx.13.arm64
- [ ] osx.1100.arm64
- [ ] osx.13.amd64.perf
- [ ] osx.13.amd64.iphone.perf
- [ ] osx.13.amd64.appletv
- [ ] osx.13.amd64.iphone
- [ ] osx.13.arm64.m1.perf
- [ ] osx.13.arm64.m2.perf
- [ ] osx.1200.amd64.iphone.open

**Comment by dkurepa** [comment]
Just an FYI, when I was creating provisioning profiles for iOS and tvOS I named them `NET Apple Development iOS/tvOS New`, since `NET Apple Development iOS/tvOS` was already taken. Before I uploaded them to the storage account, I changed their name, so they overwrote the old provisioning profiles

**Comment by dkurepa** [comment]
All of the queues above have been updated, closing the issue
