### ISSUE TITLE
[Build Analysis] Fix emojis not rendering correctly

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/dnceng#1516]
Looks like some emojis are not rendering correctly in build analysis.
Looks like it was a change in markdown/github or something that wasn't as this impacted older markdowns (that didn't change) and than previously looked good and now the don't

Like in here:
<img width="562" alt="image" src="https://github.com/dotnet/dnceng/assets/6895254/84ae9f7d-f63c-434e-b87e-a64768c969f5">

### Release Note Category
- [ ] Feature changes/additions 
- [x] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Fixed report known issues emojis not rendering correctly

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/35816

**Comment by akoeplinger** [comment]
I noticed the same happening for known issue validation, PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/35871

<img width="811" alt="image" src="https://github.com/dotnet/dnceng/assets/1376924/16a8aaa7-0488-485f-b6fa-be8d262f1b96">

**Comment by AlitzelMendez** [comment]
rolled out and is not working as expected, closing
