### ISSUE TITLE
Some Mac machines didn't get the new Apple certificates

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/dnceng#1542]
This is related to https://github.com/dotnet/dnceng/issues/1515, it looks like some machines didn't get the new cert and the existing one expired, causing work item failures: https://github.com/dotnet/runtime/issues/95875

According to Kusto these are the affected machines:
DNCENGMAC131
DNCENGMAC130
DNCENGMAC116
DNCENGMAC119
DNCENGMAC052
DNCENGMAC127
DNCENGMAC055
DNCENGMAC112

Looking at one of them via KVM showed:
<img width="775" alt="image" src="https://github.com/dotnet/dnceng/assets/1376924/541f7cbe-03a4-4af1-8fb3-b7f4faf97e8b">

/cc @ilyas1974 @dkurepa 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by dkurepa** [comment]
I must have missed this queue, or not put enough workitems to cover all 28 machines. Should be fixed now
