### ISSUE TITLE
Index page of helix.int-dot.net website down 

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/dnceng#1586]
This is only impacting the index page but well it's the index page and is how we mostly get to all of the places :)

So this page is completely down I already this the investigation

## Findings 
The problem is a System.IndexOutOfRangeException as can be observed on the logs:  [Go to Log Analytics and run query](https://ms.portal.azure.com/#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fcab65fc3-d077-467d-931f-3932eabf36d3%2FresourceGroups%2Fdotnet-eng-int-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fdotnet-eng-int/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAAz2NSwrCMBgG954idCvUuhUrFC3ahW2pBygx%252BdRAHiX5qyl4eFHRzaxmGESBgZSzYfZkjxs8mNBulH3nNGpuwPKcJRd%252B9kqsFgdoFb8s2ir5J4N3Zw1TyY99mgLBpJWViM1IzaXj9oryd2KcWBGGGrR1HntYeE6QOydGA0tpy68I%252Faeer8sIMRKKMFmxkX2fpUd3R41I77tWRhFbZi8ksjt2xgAAAA%253D%253D/timespan/P1D)

This is happening because in the past we always listed all the python packages next to the version we were using, and this is no longer true as can be observed in here: [helix.base.yaml - Repos (azure.com)](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines?path=/definition-base/helix.base.yaml&version=GBmain&line=27&lineEnd=28&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) 

As this has changed also our code should adapt and list the version only when there is a version, the actual error is happening in here: [Index.cshtml - Repos (azure.com)](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service?path=/src/ServiceFabric/Helix/HelixAPI/Pages/Index.cshtml&version=GBmain&line=325&lineEnd=326&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents), we can add a simple if to review if we have the artifact version or something around those lines 

## Additionally
We need to fix this before rolling out helix-machines, otherwise we will break the index page in production 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
No release note needed.

**Comment by dougbu** [comment]
suggest
``` cshtml
@if (package.Length == 1) {
  <td/>
} else {
  <td>v@(package[1])</td>
}

**Comment by AlitzelMendez** [comment]
this has been fixed, closing :)
