### ISSUE TITLE
Online OSX machine

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#162]
Machine `dci-mac-build-313` was taken offline from the `osx.1200.amd64.open` queue for investigation. We'll need to put it back online when @michaelgsharp has completed his work. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by epananth** [comment]
Done
