### ISSUE TITLE
Documentation Update - Helix Service Fabric Alerts

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#1682]
In doing some documentation clean up, I found that the alerts we have related to the Helix Service Fabric do not have troubleshooting instructions. I have created a wiki page - https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1166/-Alerts-Helix-Service-Fabric-Exceptions - as a placeholder. 

We need to create instructions for troubleshootin alerts from the following grafana alerts 
https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/historical/backend-status?editPanel=64&tab=alert&orgId=1
https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/historical/backend-status?editPanel=10&tab=alert&orgId=1

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-eng-wiki/pullrequest/36260

**Comment by AlitzelMendez** [comment]
done!! closing 🥳
