### ISSUE TITLE
KnownIssues page on helix.dot.net

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#1684]
From @akoeplinger 

I just noticed that the data on
https://helix.dot.net/BuildAnalysis/KnownIssues
doesn't match the table in the github issue, e.g. 89054 and 82894 both show 1 for the month hit count but on github they show 3 and 4 respectively (it seems most of the hit counts don't match actually)

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Fixed Landing Page Known issues not showing the correct number of impacted builds

**Comment by AlitzelMendez** [comment]
Thanks for reporting this :)

Unfortunately we need completely different information for each site so we have different queries and there was a problem with the one on helix.dot.net, fixing this

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/36220

**Comment by AlitzelMendez** [comment]
fixed, closing
