### ISSUE TITLE
New Grafana Alert Needed - VM Cleaner Services

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#1686]
We need an alert created to track the health of the VM Cleaner Service. 

Details on best practices for creating alerts can be found at https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/581/Alerting

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description
No release note needed

**Comment by AlitzelMendez** [comment]
We need to first gather the information for the alert: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/36232

**Comment by AlitzelMendez** [comment]
I didn't get to the alert creation, only to the gathering data part, this is the information we are now gathering:  [Go to Log Analytics and run query](https://ms.portal.azure.com/#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fdotnet-eng-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fdotnet-eng/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA0suLS7Jz3UtS80rKeaqUSjPSC1KVchLzE1VsLVVUHJJTUwJ83XOSU3MSy1yzs8tyEktSU1RUsgvwqHGqTKwNLU0VQkAmyWq9FcAAAA%253D/timespan/P1D)

I suggest using DeadVMCleanerCompleted event data for this alert: [Go to Log Analytics and run query](https://ms.portal.azure.com/#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fdotnet-eng-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fdotnet-eng/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA0suLS7Jz3UtS80rKeaqUSjPSC1KVchLzE1VsLVVUHJJTUwJ83XOSU3MSy1yzs8tyEktSU1RAgBRrzO8NQAAAA%253D%253D/timespan/P1D)

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/38994
PR Documentation: https://dev.azure.com/dnceng/internal/_git/dotnet-eng-wiki/pullrequest/38993

**Comment by AlitzelMendez** [comment]
rolled out. closing
