### ISSUE TITLE
dotnet/dnceng does not have mirroring enabled for the production branch

### ISSUE THREAD

**Issue by ghost** [dotnet/dnceng#170]
https://github.com/dotnet/versions/blob/main/Maestro/subscriptions.json#L444-L445C27

This means that production rollouts are not automatically triggered and need a manual run of the code-mirror pipeline.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by riarenas** [comment]
@missymessa @dkurepa

**Comment by missymessa** [comment]
PR: https://github.com/dotnet/versions/pull/891

**Comment by missymessa** [comment]
This was merged! Closing.
