### ISSUE TITLE
Find and fix pipelines with missing classifications

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#1712]
Per @akoeplinger: "there are a _lot_ more pipelines missing classification (at least on public, some on internal as well) so it'd be good if someone from dnceng could go through all of them and get them classified"

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by ilyas1974** [comment]
I have gone through all the within the group that we were notified about and make sure they were classified.
