### ISSUE TITLE
Helix jobs timing out

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/dnceng#1716]
Helix jobs are timing out across multiple repos. Example: https://dev.azure.com/dnceng-public/public/_build/results?buildId=506787&view=results. The helix API claims that the jobs are finished, so it could be a reporting issue: https://helix.dot.net/api/jobs/6bbc85b2-8868-4d13-a050-5d59a897c2d7/workitems?api-version=2019-06-17

Other build: https://github.com/dotnet/arcade-validation/pull/4102

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by ViktorHofer** [comment]
This is blocking PRs like https://github.com/dotnet/arcade/pull/14320 to get in.

**Comment by ViktorHofer** [comment]
While this one just got merged in, see https://github.com/dotnet/arcade/pull/14327 or any other recent PR. Especially, see the AzDO builds per commit. All of them failed because of the Helix time out.

**Comment by sebastienros** [comment]
FYI, all ASP.NET PRs are currently blocked. Including cross repos dependency flow. I would expect someone to be able to look into this, is there a channel we can reach to raise the issue?

**Comment by Forgind** [comment]
This is affecting a bunch of code flow PRs in dotnet/sdk as well like:
https://github.com/dotnet/sdk/pull/37675

**Comment by Forgind** [comment]
I've tried rerunning a few. Will see if that works.

**Comment by AlitzelMendez** [comment]
This was discussed in [Teams](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1703789937339?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1703789937339&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1703789937339) and looks like everything is back to normal, feel free to reopen if is not the case

**Comment by Forgind** [comment]
> This was discussed in [Teams](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1703789937339?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1703789937339&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1703789937339) and looks like everything is back to normal, feel free to reopen if is not the case

This week's code flow PRs passed CI checks as desired 👍
