### ISSUE TITLE
Documentation Updates - Maestro related alerts

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#1726]
In doing some documentation clean up, I found that the alerts we have related to our Maestro Service that do not have troubleshooting instructions. I have created the following wiki pages as placeholders:

https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1180/-Alerts-Maestro-BarViz-Alert
https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1182/-Alerts-Maestro-Failed-Requests-Alert

**Comment by dkurepa** [comment]
I did some investigations and updated both of the pages. It's not too much information right now, but we'll be able to update these instructions once we actually have these alerts trigger, and deal with them. Closing for now
