### ISSUE TITLE
DNCENGMAC055 doesn't trust the attached iPhone

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/dnceng#1749]
DNCENGMAC055 doesn't trust the iPhone that is attached to it. This is causing work items running on that machine to fail.

Probably also need to open Xcode on the machine to make sure the connection works in Devices & Simulators.

<img width="943" alt="image" src="https://github.com/dotnet/dnceng/assets/1376924/d643a4b4-8b02-4bdf-982c-e57c2cc59da1">

/cc @dkurepa 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by dkurepa** [comment]
I disabled the machine, it should stop taking in workitems now. We will enable it once the issue has been resolved

**Comment by andriipatsula** [comment]
reported an ICM https://portal.microsofticm.com/imp/v3/incidents/incident/456984074/summary

**Comment by andriipatsula** [comment]
Machine `DNCENGMAC055` in `osx.13.amd64.iphone.open` has been enabled

**Comment by andriipatsula** [comment]
resolved.
