### ISSUE TITLE
Reenable `AzSecPack` on `ubuntu.2204.armarch[.open]` image

### ISSUE THREAD

**Issue by dougbu** [dotnet/dnceng#1752]
In the fix for #813 ([!34863](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/34863), I disabled `AzSecPack`. After the Azure/azure-linux-extensions#1815 / Azure/azure-linux-extensions@0b91dacd98e1ea63933a52d7899609956114471e fix to the "Agent for Linux Server Monitoring" extension (aka `Microsoft.Azure.Monitor.AzureMonitorLinuxAgent`) is rolled out, we can revert https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/commit/d1bf3852d61b29c1fb19bbc89a204aee53e49262 and slightly improve our security stance.

### Release Note Category

- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements

### Release Note Description

Re-enabled `AzSecPack`  on the  `ubuntu.2204.armarch[.open]` image.

**Comment by dougbu** [comment]
According to https://learn.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-extension-versions#version-details, a new version of the Azure Monitor agent extension should be available that will avoid our need to disable `AzSecPack`. Waiting to hear back about which extension version (v1.29.4 contains the fix, we hope) we're currently picking up&hellip;

**Comment by dougbu** [comment]
@AlitzelMendez didn't the [!36234](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/36234) fix roll out today❔

**Comment by AlitzelMendez** [comment]
yes, the fixed rolled out. Closing this issue 😄
