### ISSUE TITLE
Make queue `Description` visible on https://helix.dot.net/

### ISSUE THREAD

**Issue by dougbu** [dotnet/dnceng#1754]
Our definitions YAML includes a `Descriptions` property for every image (aka queue in this context). The descriptions seem useful for our customers. However, the only place I've seen it output is from the `.\osob-cli.cmd definitions` command. In particular, it's not displayed on https://helix.dot.net/

Fix should require only a simple edit of the home page for the relevant application. See https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service?path=/src/ServiceFabric/Helix/HelixAPI/Pages/Index.cshtml

### Release Note Category

- [x] Feature changes/additions
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

### Release Note Description

Added queue descriptions to the information available on https;//helix.dot.net/

**Comment by riarenas** [comment]
Seems like a reasonable ops ask. We should make sure we scrub any information we don't want exposed in the descriptions.

**Comment by AlitzelMendez** [comment]
@doug / @riarenas  do we have any specific information in mind that we would like to scrub?

**Comment by dougbu** [comment]
> @dougbu / @riarenas do we have any specific information in mind that we would like to scrub?

I didn't suggest scrubbing the `Description` settings in helix-machines and am not sure what @riarenas had in mind. Personally, I don't see anything objectionable. Would likely be better for @riarenas or @ilyas1974 to make specific suggestions.

Note scrubbing (if someone thinks it'll help) may be easier to do in the `dotnet-helix-machines` definitions up front, not clean things later in `dotnet-helix-service`.

**Comment by AlitzelMendez** [comment]
thanks Doug.

Create the pull request: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/39028 and I will wait for @riarenas feedback before merging

**Comment by AlitzelMendez** [comment]
this was rolled out, closing
