### ISSUE TITLE
investigate warnings during deployment of dotnet-status

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#176]
The latest two production deployments of dotnet/dnceng have the following warnings:

```
Failed to update App Service configuration details. Error: Error: Failed to update App service 'dotneteng-status-staging' Meta data. Error: Conflict - The slot cannot be changed because its configuration settings have been prepared for swap. (CODE: 409)
```
This warning has only happened since the move out of arcade-services.

```
##[warning]Error: Failed to update deployment history. Error: Conflict (CODE: 409)
```
The deployment history warning has been a common occurrence for some time, but it would be good to understand it.

We should spend some time to investigate what's up with these and ideally clean them up.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by riarenas** [comment]
@dkurepa @missymessa FYI.

**Comment by missymessa** [comment]
Didn't see this error occur in the last rollout.
