### ISSUE TITLE
 Azure Key Vault task intermittently failing 

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/dnceng#1799]
It was reported that the  Azure Key Vault task  is something failing to download secrets, the impact can be follow up in: [Timeline - Helix (dot.net)](https://helix.dot.net/BuildAnalysis/SearchTimeline?error=@azure%2Fmsal-node@1.14.5%20%3A%20Error%20-%20Did%20not%20find%20cloud%20discovery%20metadata%20from%20hardcoded%20values...%20Metadata%20could%20not%20be%20obtained%20from%20config,%20cache,%20network%20or%20hardcoded%20values.%20Throwing%20Untrusted%20Authority%20Error.&dateType=Day(s)&dateValue=7&pageNumber=0)

As this is a AzDO task I opened an IcM: https://portal.microsofticm.com/imp/v3/incidents/incident/457790571/summary

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by ilyas1974** [comment]
Linking additional issue that is tracking impact to our customers - https://github.com/dotnet/dnceng/issues/1830

**Comment by davfost** [comment]
If this is still occurring, does it have anything to do with all the warnings on the pipelines saying that Pat Tokens created before 2/13 need to be rolled?



![Image](https://github.com/dotnet/dnceng/assets/32279912/32eb47ac-ae78-4319-ac65-91da8aa82a37)

**Comment by AlitzelMendez** [comment]
this is still occurring, you can take a loot at [Timeline - Helix (dot.net)](https://helix.dot.net/BuildAnalysis/SearchTimeline?error=@azure%2Fmsal-node@1.14.5%20%3A%20Error%20-%20Did%20not%20find%20cloud%20discovery%20metadata%20from%20hardcoded%20values...%20Metadata%20could%20not%20be%20obtained%20from%20config,%20cache,%20network%20or%20hardcoded%20values.%20Throwing%20Untrusted%20Authority%20Error.&dateType=Day(s)&dateValue=7&pageNumber=0) to get some examples

This is not related with the PAT rotation

**Comment by epananth** [comment]
Planning to turn on System.Debug = true for Runtime repo to collect some logs over the weekend.

**Comment by epananth** [comment]
Turned on System.debug in runtime official pipeline, keeping my fingers crossed hoping we will catch some errors over the weekend :)

**Comment by epananth** [comment]
Assigning this back to @ilyas1974, someone in FR will have to follow up with the ICM ticket

**Comment by riarenas** [comment]
The ICM says there was a change to add retries to the task. Our telemetry shows the latest instance of this issue happened on 3/26. I will keep an eye on the query until it clears.
