### ISSUE TITLE
Tests cannot connect to 'arm64-v8a' emulator

### ISSUE THREAD

**Issue by matouskozak** [dotnet/dnceng#1819]
### Build

https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=519155

### Build leg reported

IcuAppLocal.Tests.WorkItemExecution

### Pull Request

https://github.com/dotnet/runtime/pull/96023

### Known issue core information

Fill out the known issue JSON section by following the [step by step documentation on how to create a known issue](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step)

```json
 {
    "ErrorMessage" : "fcrit: Failed to find compatible device: arm64-v8a",
    "BuildRetry": false,
    "ErrorPattern": "",
    "ExcludeConsoleLog": false
 }
 ```

 @dotnet/dnceng

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Additional information about the issue reported
- Error log
```
[06:21:02] warn: Device 9CJAY1PTEF is offline; retrying up to five minutes
[06:21:02] dbug: All 30 retries of action failed
[06:21:02] fail: Failed to get device's property SupportedArchitectures. Check if a device is attached / emulator is started
                 error: device unauthorized.
                 This adb server's $ADB_VENDOR_KEYS is not set
                 Try 'adb kill-server' if that seems wrong.
                 Otherwise check for a confirmation dialog on your device.
                 
[06:21:02] fail: No attached device supports one of required architectures arm64-v8a
[06:21:02] dbug: No suitable devices found
[06:21:02] crit: Failed to find compatible device: arm64-v8a
[06:21:02] dbug: Saving diagnostics data to 'D:\h\w\AE00090C\w\AD89096B\e/diagnostics.json'
XHarness exit code: 81 (DEVICE_NOT_FOUND)
```

_No response_

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[519155](https://dev.azure.com/dnceng-public/public/_build/results?buildId=519155)|dotnet/runtime|[System.IO.Compression.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=519155&view=ms.vss-test-web.build-test-results-tab&runId=12201728&resultId=129777)|dotnet/runtime#96023|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|1|

**Comment by missymessa** [comment]
IcM created for DDFUN here: https://portal.microsofticm.com/imp/v3/incidents/incident/461549167/summary

**Comment by missymessa** [comment]
`DNCENGWIN-061` has been re-enabled. Closing this issue
