### ISSUE TITLE
Restore Windows 7 images

### ISSUE THREAD

**Issue by dougbu** [dotnet/dnceng#184]
Microsoft is no longer making a `windows-7` image available to us. We are attempting to find someone who can restore the image or our access but it's unclear that will be possible. The continued use of the image fails dotnet-helix-machines-ci builds that use it. Errors look like the following:
``` text
Exception in ValidateImage: Failed to find image: VM Image from publisher: MicrosoftWindowsDesktop with - Offer: windows-7, Sku: win7-enterprise, Version: 7601.26366.230209 is deprecated.
```

For example, see the following PR builds:
- [#20230608.04](https://dev.azure.com/dnceng/internal/_build/results?buildId=2197022&view=results)
- [#20230609.05](https://dev.azure.com/dnceng/internal/_build/results?buildId=2197685&view=results)

The following osob-cli.cmd output confirms no images are available:
``` text
For MicrosoftWindowsDesktop/windows-7/win7-enterprise:
   Current version:          7601.26366.230209
   Latest available version: (none)
   Image is using version not found in the Marketplace. This is an error.
   No versions of this image are available. This is an error.
```

In addition, the following command finds no matches:
``` powershell
az vm image list --location westus --publisher MicrosoftWindowsDesktop --offer windows-7 --output table --all
```

### Release Note Category
- [ ] Feature changes/additions 
- [x] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

Solution unknown at this point. Release note may be unnecessary. Worst case, we need to remove the queues in an inelegant and expedited manner.

**Comment by dougbu** [comment]
Windows Server 2012 images are also no longer available to us

**Comment by dougbu** [comment]
unmonitored the queues in https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/31794>. this is **not** a great solution for this issue but may suffice for now.

**Comment by garath** [comment]
Extended Support for Windows 7 ended January 10, 2023, which makes Win7 fully unsupported. Unless I'm missing some avenue of support somewhere. 

What's keeping Win7 around for us? Since ESU has expired, does .NET even still support it?

**Comment by dougbu** [comment]
> Extended Support for Windows 7 ended January 10, 2023, which makes Win7 fully unsupported. Unless I'm missing some avenue of support somewhere.
> 
> What's keeping Win7 around for us? Since ESU has expired, does .NET even still support it?

We've been using this image w/o problems until I filed this issue. .NET 6 and 7 both support this OS according to the matrix of truth. And Grafana shows the queues have been used over the last 30 days by dotnet/corefx, dotnet/coreclr, and dotnet/runtime.

**Comment by garath** [comment]
> We've been using this image w/o problems until I filed this issue. .NET 6 and 7 both support this OS according to the matrix of truth. And Grafana shows the queues have been used over the last 30 days by dotnet/corefx, dotnet/coreclr, and dotnet/runtime.

I notice on the current official "[.NET 7 - Supported OS versions](https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md)" does not show Win7. The language indicates it has always been that way (a deliberate change from .NET 6) so maybe a MoT error?

[.NET 6 - Supported OS versions](https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md) does list it but with the caveat of being able to use ESU (which is no longer valid). 

It seems like a good time to figure out a "shut down the queues" plan. There is precedence for this (e.g. macOS 10.13, which went EOL during .NET 6's lifecycle). This should also be an "important" thing to do before there are compliance troubles. 

@ilyas1974 and possibly @markwilkie, who on the PM side would be interested in talking about OS support with us?

**Comment by dougbu** [comment]
Adding @garath to the assignees b/c he's digging deeper / taking over / stepping up / restrengthening our solutioning 😀

**Comment by garath** [comment]
> what's your status on this

I'm only really just getting started now. Let's chat tomorrow and see how far I get.

**Comment by dougbu** [comment]
**Note** this issue should **not** be closed after our next rollout. let's continue using it for the real `perl` upgrade

**Comment by dougbu** [comment]
(fixed typo, sorry)

**Comment by garath** [comment]
Rollout happened. These queues are unmonitored now.

**Comment by garath** [comment]
Unassigning and moving to the ops backlog.

**Comment by garath** [comment]
No need for this anymore. See dotnet/dnceng#2498
