### ISSUE TITLE
Move to the subnet delegation model for 1ES hosted pools

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#1850]
Our current deployment model for 1ES hosted pools and 1ES images (Bring your own subscription) is outdated. We should now be onboarding to subnet delegation inside 1ES managed subscriptions. 

docs are here: https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-hosted-azure-devops-pools/subnet-delegation

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

### Release Note Description
1ES hosted pools will now create the VMs that run the builds in 1ES hosted subscriptions.

**Comment by riarenas** [comment]
Looks like the process is relatlively straightforward:
* Deploy and configure a VNet
* Follow the migration guide to connect existing pools to the vnet
* Validate that things work as expected after each migration
* Change the helix-machines code to deploy new pools pointing to the new vnet.

**Comment by dougbu** [comment]
given our conversation this afternoon, should this issue be assigned to me @riarenas❔

**Comment by riarenas** [comment]
@dougbu Oh, I was thinking that you'd be working on #1145. I was thinking this issue would deal mostly with the conversion of existing resources to the new model once there was a VNet set up for #1145 

If you want to tackle them both at the same time, or one after the other I can leave this alone, I don't think I'll get to do more than investigation for this week anyways!

**Comment by riarenas** [comment]
This isn't strictly related to 1es managed images, and it's more of a compliance requirement at this point. Even the pipeline templates task requires this. I'll move this out of the epic and into ops-compliance.

**Comment by riarenas** [comment]
Starting to look at this as a 1ES PT prerequisite

**Comment by riarenas** [comment]
The process here will be:

* Stop setting the [parameters needed](https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-hosted-azure-devops-pools/subnet-delegation#migrating-from-a-self-managed-pool-bring-your-own-subscription) for hosting the machines in our own subscriptions.
* Make the code changes to start deploying a VNET with an NSG as part of creating the resource group that will have the hosted pool in it
* Correctly set up the [networkProfile section](https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-hosted-azure-devops-pools/subnet-delegation#3b-associate-the-subnet-with-your-cloudtest-pool-using-arm-templates) of the Pool during deployment, pointing to the new vnet

**Comment by riarenas** [comment]
https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/37265

**Comment by riarenas** [comment]
Taking a close look at https://dev.azure.com/dnceng/internal/_build/results?buildId=2381029&view=results to validate in the staging environment.

**Comment by riarenas** [comment]
Womp womp, failed with a nullref. Checking.

**Comment by riarenas** [comment]
This is currently undergoing deployment. As we move to 1ES managed subscriptions, we are finding out that these subs that we get assigned to start out with very low core quota, so we'll need to go through quota increase requests for each pool we deploy.

**Comment by riarenas** [comment]
We are still working with 1ES to get the remaining pools migrated. We have some suggestions from the 1ES team that we will try today.

* try again, see if that gets you a different subscription that is allowlisted
* try again with a different SKU, to see if that doesn't get denied. 

The two pools in this state currently are:
* netcore1es-pool-internal-xl
* netcorepublic-xl

**Comment by riarenas** [comment]
netcore1espool-internal-xl has been updated after getting our core request approved. Still working on `netcorepublic-xl`

**Comment by riarenas** [comment]
We were finally granted all the cores we needed for our pools. This is complete

**Comment by markwilkie** [comment]
[celebrate]     Mark Wilkie reacted to your message:
________________________________
