### ISSUE TITLE
Forward workloads from Ubuntu.2004.PPC64le.Experimental.Open to Ubuntu.2204.PPC64le.Experimental.Open

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#1890]
The Ubuntu.2004.PPC64le.Experimental.Open has been deprecated. We have received a request to forward any workloads that may still be using this queue to the new Ubuntu.2204.PPC64le.Experimental.Open. 

### Release Note Category
- [X] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Forward Ubuntu.2004.PPC64le.Experimental.Open request to Ubuntu.2204.PPC64le.Experimental.Open queue

**Comment by dougbu** [comment]
[!38001](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/38001) contains the fix

**Comment by dougbu** [comment]
done
