### ISSUE TITLE
How to handle Rollout Scorecard PRs that don't have a linked issue?

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#191]
Need to figure out how we want to handle PRs from Rollout Scorer, since we require issues to be tied to the PR. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

No release notes.

**Comment by riarenas** [comment]
seems like we should just skip them

**Comment by missymessa** [comment]
I agree, what kind of mechanism do we want to have handle that? Maybe Rollout Scorer throws a label on it and we see the label and skip it? Somethings specific for Rollout Scorer or do we want something more generic for other use cases?

**Comment by missymessa** [comment]
I don't think scorecards have been generating, so I can't validate this quite yet.

**Comment by missymessa** [comment]
This worked! Closing.
