### ISSUE TITLE
Issue mirror not mirroring issues

### ISSUE THREAD

**Issue by garath** [dotnet/dnceng#1931]
The issue mirror not mirroring issues. Why?

**Comment by riarenas** [comment]
🧛

**Comment by garath** [comment]
I see issues being openeg again. Closing.

**Comment by missymessa** [comment]
Issues that had to be manually mirrored: 

https://github.com/dotnet/dnceng/issues/2073
https://github.com/dotnet/dnceng/issues/2074
https://github.com/dotnet/dnceng/issues/2075
https://github.com/dotnet/dnceng/issues/2076

**Comment by AlitzelMendez** [comment]
this is now fixed 😄 
do we feel happy closing it? or do we want some follow up?

**Comment by garath** [comment]
If you believe you got it solved, then yay! we can close.
