### ISSUE TITLE
Update Helix SAS tokens for DDFUN access and helix checks

### ISSUE THREAD

**Issue by v-parose** [dotnet/dnceng#1952]
Hello DotNet team,

While trying to run the helix check and accessing the Helix queues in Storage explorer we are getting an authentication issue. I believe the SAS token for these connections was rotated recently and needs to be updated in our DDFUN KeyVaults so we can access them again?

Trying to run the Helix Queue Check script I see the following error:
![image](https://github.com/dotnet/dnceng/assets/147425076/58e627fa-9b1c-4b55-b38f-1508c385e055)

Previously MattGal would update the SAS token for this script for us, but I believe he is no longer with the DotNet team. Can someone from the DotNet team please help to update that?

For accessing the Helix queues heartbeat table, and OS config files in storage explorer we use the below connection strings under the main DDFUNESSUPPORT KV. Can you please update these with the latest connection strings?

Helix Production queues connection string:
https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/asset/Microsoft_Azure_KeyVault/Secret/https://ddfunessupport.vault.azure.net/secrets/HelixProd-ReadOnlyConnectionString

Helix Staging queues connection string:
https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/asset/Microsoft_Azure_KeyVault/Secret/https://ddfunessupport.vault.azure.net/secrets/HelixStaging-ReadOnlyConnectionString

OSconfig Production script files connection string:
https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/asset/Microsoft_Azure_KeyVault/Secret/https://ddfunessupport.vault.azure.net/secrets/helixosconfig-PrimaryConnectionString
 
OSconfig Staging script files connection string:
https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/asset/Microsoft_Azure_KeyVault/Secret/https://ddfunessupport.vault.azure.net/secrets/helixosconfigstaging-PrimaryConnectionString

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description
Uploading Helix check strip to source control

**Comment by riarenas** [comment]
The storage account key was cycled today. I'll start working on these after I validate https://github.com/dotnet/dnceng/issues/1951 is mitigated.

**Comment by riarenas** [comment]
@ilyas1974 Is this a process that DDFUN should be able to perform on their own? it feels strange to manually update another team's vaults because of our standard secret cycling practices. Should DDFUN onboard to secret-manager?

**Comment by riarenas** [comment]
@v-parose I updated the vaults. I tried to use the existing secrets to determine the set of permissions for the SAS. Let me know if you still see issues.

**Comment by v-parose** [comment]
Thank you @riarenas I was able to connect to the Storage Accounts using the updated connection strings in the KV. 

The only thing still having issues is the "ListOnPremMachinesNeedingHelp.exe" script from the screenshot I posted. I'm not sure how that gets updated? In the past we were given an updated script file from DotNet which I then just copied to our own DDFUN share for our team to run.

**Comment by riarenas** [comment]
I don't know what ListOnPremMachinesNeedingHelp.exe is. @ilyas1974 is this something maintained by our team? if this was something that was manually written by a dev no longer on the team, I don't know how to help.

**Comment by AlitzelMendez** [comment]
@ilyas1974 , do you have more information ListOnPremMachinesNeedingHelp.exe? :)  does this issue is still present?

**Comment by ilyas1974** [comment]
I have a meeting setting up with Mattgal to address this tomorrow. Will be writing up instructions for next time.

**Comment by ilyas1974** [comment]
The console app has been added to the Helix-Services repo.
