### ISSUE TITLE
List of prerequisites to onboard to 1ES PT

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#1956]
There are a few prerequisites that engineering organizations need to have in place before pipelines in their orgs can use the 1ES PT.

Look at https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/onboardingesteams/overview and figure out the minimum set up needed to start supporting generic pipelines with the templates in dnceng.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by riarenas** [comment]
Known work for this so far:


* Ensure dnceng is completely onboarded to get the current versions of the templates: https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/onboardingesteams/provisioning
* Onboard our existing 1ES hosted pools to subnet delegation, or create a separate 1ES Hosted pool for pipelines using the templates: https://github.com/dotnet/dnceng/issues/1850
* Have machines available in the pools with images that can run the templates: https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/onboardingesteams/create-agent-image. Strongly preferred if we can just use the 1ES PT images. 
* Investigate the signing story. The pipelines have signing built in, but it requires an ESRP connection. Since our current signing story is tied to Microbuild, should guidance be to use the [Microbuild pipeline templates](https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/38949/MicroBuild-Templates) instead of the 1ES pipeline templates?
*

**Comment by missymessa** [comment]
> Investigate the signing story. The pipelines have signing built in, but it requires an ESRP connection. Since our current signing story is tied to Microbuild, should guidance be to use the [Microbuild pipeline templates](https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/38949/MicroBuild-Templates) instead of the 1ES pipeline templates?

Yes :)

**Comment by riarenas** [comment]
We've broken this down into other work items.
