### ISSUE TITLE
New Helix Queue needed

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#196]
As macOS 14 is only supported on M1/2 devices, we need to have a scouting new created for this platform

New queue needed - osx.arm64.scouting.open
XCode version: Xcode 15 Beta

### Release Note Category
- [X] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Adding ARM Mac scouting queue

**Comment by epananth** [comment]
Spoke to @AlitzelMendez  about this, looks like we need more information to make this change.

For starters we need to know image name and system id. What artifacts have to be published. The correct xcode version. There is nothing defined for osx.14 beta, so is it a brand new queue or is it base of another queue?

@AlitzelMendez said she will take over this on Monday after these questions are answered.
