### ISSUE TITLE
Add images that can run the 1ES pipeline templates

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#1973]
The templates can only be used by machines that meet certain requirements, mainly having a prerequisite artifact installed.

We should make sure we have images that can run builds with these templates in our 1ES hosted pools.

https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/onboardingesteams/create-agent-image has alternatives on how to get a compliant image. 

Our pools currently provide two types of images:

* **The 1ES equivalents of the Microsoft hosted images**:  The pipeline template equivalent corresponds to option 1 in the linked guide. These are what the 1ES teams calls the kitchen sink images, that have support for a variety of workloads. We will need to get these images into our pools so that we can support pipelines that used the Microsoft hosted agents, or the existing 1es-windows and 1es-ubuntu images.
* **Custom images with specific VS versions and workloads for building .NET repos:** These are the non-1ES images that we build ourselves, such as windows.vs2022.preview.scout. These would fall under scenario 3 of the guide. We will need to come up with a way to get the prerequisites installed into those images.

### Release Note Category

- [X] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

### Release Note Description

Updated vs2022 images to include the 1ES pipeline template prerequisites. This affects public and internal build pools and Helix queues.

Note that, so far, our build pools include a mix of 1ES-ready images (e.g., `windows.vs2022.amd64` and `1es-mariner-2-pt`) and those that are not ready (e.g., `mariner.2.amd64` and `1es-ubuntu-1804`). the majority of the images are _not_ compatible with the 1ES pipeline templates.

`-pt` images are temporary. please use them to help us validate they're ready for general use. but, once we've all done that validation, we'll update the "normal" `1es-mariner-2` (and so on) images and eventually remove the then-duplicate `-pt` ones.

**Comment by riarenas** [comment]
For the custom images, I'm exploring two avenues:

1. Install the prerequisites artifact in [the base images](https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines?path=/base-images). The base images use the ImageFactory artifact source, so they will have the artifact available. 
2. Have the image factory team make the template prerequisite artifact a [Universal Artifacts](https://dev.azure.com/devdiv/XlabImageFactory/_wiki/wikis/XlabImageFactory.wiki/6337/Artifacts) supported by image factory. The (admittedly minor) advantage here is that we only add the artifact to the final images, and we get to keep the existing base images as they are.

I'll start experimenting with option 1 today as it's the one most actionable right now. If I run into a lot of obstacles with incompatibility we'll have to push for option 2.

**Comment by riarenas** [comment]
New image factory tracking ID: `a6b7c297-181e-8b15-e25d-a92ac2cea4ec`

Still installing VS, will check on it in the morning.

**Comment by riarenas** [comment]
* For the 1ES kitchen sink images, I found that the PT images are hosted in a different subscription than the other 1ES images that we copy into our pools. We'll need to refactor the way we deploy the 1es Hosted pools to allow for more than one subscription, but they are easy enough to copy. This [Resource group in our staging subscription](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/cab65fc3-d077-467d-931f-3932eabf36d3/resourceGroups/1ESHostedPoolImagesWestUS-PR37118-rg/overview) has the images that I generated manually.

* For the custom images. request a6b7c297-181e-8b15-e25d-a92ac2cea4ec [finished creating my image](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/84a65c9a-787d-45da-b10a-3a1cefce8060/resourceGroups/helixosauto-lab-rg-wus/providers/Microsoft.Compute/images/VS2022Enterprise_17_8_6-PT-2024-02-07/overview) successfully, which means we can create copies of all our existing base images with the 1ES PT artifact in them.

These findings prove that we won't need a lot of infrastructure changes to support these images. I'll work on the PRs to get these created now.

**Comment by riarenas** [comment]
* The 1es general use images (kitchen sink images) will be available with tomorrow's deployment
* We still need to generate images with the template prerequisites

**Comment by dougbu** [comment]
@riarenas' branch is not yet working end-to-end. Problem appears to be the length of one of the new image names. We have a request out to the Image Factory team for confirmation.

**Comment by riarenas** [comment]
> @riarenas' branch is not yet working end-to-end. Problem appears to be the length of one of the new image names. We have a request out to the Image Factory team for confirmation.

Never expected it to work end to end. This was very much work in progress before I had to move on.

**Comment by dougbu** [comment]
[!37581](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/37581) is ready for review. it covers VS2022 build images

**Comment by dougbu** [comment]
[!37590](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/37590) covers the second part of creating new 1ES-compatible vs2022 images (both build and test)

**Comment by dougbu** [comment]
done
