### ISSUE TITLE
Close windows.10.amd64.android.open

### ISSUE THREAD

**Issue by garath** [dotnet/dnceng#1994]
Queue windows.10.amd64.android.open has been deprecated and replaced by windows.11.amd64.android.open.

- [x] Set `DeprecatedTo` property in helix-machines YAML
- [x] Ensure [ICM 457737520](https://portal.microsofticm.com/imp/v3/incidents/details/457737520/home) is completed
- [x] Update known users where possible
- [x] Update arcade's release/6.0 branch
- [x] Update arcade's release/8.0 branch
- [ ] Delete the deprecated queue once there is confidence that all users have been covered

<hr />

### Release Note Category

- [x] Feature changes/additions
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

### Release Note Description

Queue windows.10.amd64.android.open has been deprecated in favour of windows.11.amd64.android.open for a while. We have now removed this older queue. Please use windows.11.amd64.android.open going forward.

**Comment by garath** [comment]
See also dotnet/dnceng#1884

**Comment by garath** [comment]
PR to make this redirect persistent: [37186](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/37186)

**Comment by dougbu** [comment]
@garath exactly what work remains here❔ the ICM has been resolved but isn't checked above. plus, the queue is deprecated in `dotnet-helix-machines` and that change has rolled out. I suspect this issue just needs to be closed.

unless of course there should be changes in all active arcade branches and then we intend to remove the queue name entirely❔

**Comment by garath** [comment]
> the ICM has been resolved but isn't checked above

It's not checked because I stopped monitoring the work here and used that language to indicate that it's a gating factor to closing. 

The remaining work is just those two first items.

**Comment by dougbu** [comment]
No use of the queue since 5 September

**Comment by dougbu** [comment]
this change rolled out on 2 October
