### ISSUE TITLE
Issue with Publishing Artifacts

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#2009]
I am getting reports of an issue within the Publish Intermediate Artifacts step in runtime. 

Error being seen:

`This job was abandoned. We have detected that logs from the agent may have not finished uploading. We have included our in-memory record of all log lines uploaded before we lost contact with the agent:
Starting: Publish intermediate artifacts`

Build for Reference: https://dev.azure.com/dnceng/internal/_build/results?buildId=2376277&view=logs&j=46718cb1-cc84-5b44-d4ae-44c5afdef23a

**Comment by garath** [comment]
Any feel for how widespread it is?

**Comment by ilyas1974** [comment]
I do not believe it's too widespread at this time (couldn't find metrics about it in known issues) but would like to understand what going on - if its related to the work we recently did with the publishing pools.

**Comment by riarenas** [comment]
Any reason to believe this isn't related to the other million issues with mac vms in the microosft hosted pools?

this is not related at all with the publishing pool.

**Comment by riarenas** [comment]
See https://github.com/dotnet/dnceng/issues/1886. This build was picked up by that known issue.

**Comment by epananth** [comment]
This is already part of known issue, @ilyas1974  can I close this?
