### ISSUE TITLE
Automate `NetCore1ESPool-Publishing-Internal` updates

### ISSUE THREAD

**Issue by dougbu** [dotnet/dnceng#2082]
We created `NetCore1ESPool-Publishing-Internal` manually to expedite work on #1145. That means our automation does not update the pool (though images are updated over time) and the settings may get out of sync. To fill this gap, we need to slightly extend our pool definitions to support standby agents.

The ARM template bit needed here is
``` json
        "agentProfile": {
            "type": "Stateless",
            "kind": "Stateless",
            "resourcePredictions": [
                {
                    "00:00:00": 3
                }
            ]
        },
```

### Release Note Category

- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements

### Release Note Description

Automated updates to the `NetCore1ESPool-Publishing-Internal` hosted pool. This should avoid unintended configuration inconsistencies going forward.

**Comment by dougbu** [comment]
yup

**Comment by epananth** [comment]
here is the I tried PR -:> https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/37778

**Comment by dougbu** [comment]
taking this back to Dev 😦 a [!37778 comment](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullRequest/37778#1710998293) I made about a testing gap nagged at me. I bumped `MinimumStagingSize` and ran https://dev.azure.com/dnceng/internal/_build/results?buildId=2411354&view=results. That build succeeded but the created pool _lacked_ the expected reservation settings. I missed a scenario &mdash; comparisons with existing pool properties. Suspect it's a quick fix&hellip;

**Comment by dougbu** [comment]
Work completed with [!38496](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/38496). If we need to announce internal-only fixes, this should be mentioned _next_ week.

**Comment by dougbu** [comment]
part one has rolled out to production. will close after [!38496](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/38496) also reaches production

**Comment by dougbu** [comment]
Confirmed today's rollout set up `NetCore1ESPool-Publishing-Internal` correctly today
