### ISSUE TITLE
Azdo Issue #5889

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#2093]
https://dev.azure.com/dnceng/internal/_workitems/edit/5889

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by dougbu** [comment]
@missymessa didn't you address this issue in all dotnet/arcade branches❔

**Comment by missymessa** [comment]
Yeah, this should've been handled. Ricardo, are we still seeing this in places, or was this a dupe of the one we fixed?
