### ISSUE TITLE
Create new helix queue for perf team

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#2094]
The perf team has asked that we create a new, non specific osx queue for them. 

Please create osx.am64.iphone.perf within helix. Setting can be identical to the osx.13.amd64.iphone.per queue. 

The new queue should be in production on Thursday  3/21/2024.

Notify parkerbibus in email once we verify that the new pool shows up on the available queue information site for production:
https://helix.dot.net/

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Create osx.am64.iphone.perf helix queue

**Comment by davfost** [comment]
Adding a ipohne segregation pool named OSX.Amd64.Iphone.Perf based on the setting for the existing pool named OSX.13.Amd64.Iphone.Perf per customer request.

PR 37968: 
https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/37968

**Comment by davfost** [comment]
The new queue now shows up in production and the customer has been notified in email.
