### ISSUE TITLE
Update `build.ubuntu.*` images to include 1ES prerequisites

### ISSUE THREAD

**Issue by dougbu** [dotnet/dnceng#2113]
Work is almost done making sure the build images we provide are compatible with the 1ES pipeline templates. One remaining gap (after in-flight issues are resolved) is our `build.ubuntu.*` images. We're waiting for @ChulHul to let us know when the "multiple sources" feature has been rolled out. That feature will allow us to use XLabImageFactory and helix-machines artefacts together in a single generation request, rather than creating more base images (temporarily).

Specific images to update are for
- `build.ubuntu.1804.amd64[.open]` &mdash; as long as the PT prerequisites artifact is compatible w/ 18.04. the lack of MMS image from the 1ES team may indicate a problem.
- `build.ubuntu.2004.amd64[.open]`
- `build.ubuntu.2204.amd64[.open]`

### Release Note Category

- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

### Release Note Description

Completed work on adding 1ES pipeline template prerequisites to the build images available in dnceng/internal.

**Comment by riarenas** [comment]
Since it seems like the multiple artifact sources feature won't be available by our migration deadline, we are going to generate new base images for these build images, and install the artifact there. 

We will want to remove those images when we adopt the multiple sources feature.

**Comment by riarenas** [comment]
> build.ubuntu.1804.amd64[.open] — as long as the PT prerequisites artifact is compatible w/ 18.04. the lack of MMS image from the 1ES team may indicate a problem.

We now know that 1ES is dropping support for 18.04 altogether, so 18.04 images are not compatible with the templates.

For 20.04 and 22.04 I have generated the new base images and I'm still working on applying those to just our build image definitions.

**Comment by riarenas** [comment]
The changes have been merged and are scheduled to be deployed on our next rollout.

**Comment by akoeplinger** [comment]
did this get rolled out yesterday?

**Comment by riarenas** [comment]
Yep, this was deployed yesterday. Let me know if you see any issues.
