### ISSUE TITLE
Migrate DNCEng pipelines to 1ES Templates

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#2118]
As part of the project to enable 1ES templates, we need to move the pipelines that dnceng owns/uses. Below you will find a list of pipelines that need to be migrated. 

To do:
- (none)

In progress:
- (none)

Complete:
- dotnet-helix-service-CI: dotnet/dnceng#2162
- Maestro build promotion (Devdiv): dotnet/dnceng#2177
- Maestro build promotion (Dnceng): dotnet/dnceng#2176
- dotnet-dnceng-ci: dotnet/dnceng#2171
- dotnet-dnceng-shared-ci: dotnet/dnceng#2172
- arcade-services-internal-ci: dotnet/arcade-services#3396
- dotnet-helix-machines-image-generation: dotnet/dnceng#1953
- arcade-official-ci: dotnet/dnceng#2270
- dotnet-arcade-validation-official: dotnet/dnceng#2178
- dotnet-helix-machines-ci: dotnet/dnceng#1953
- dotnet-arcade-testing-1es-pipeline-templates: dotnet/dnceng#2158
- generate-xcopy-msbuild: dotnet/dnceng#2158

---

### Release Note Category

- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements

### Release Note Description
No release note needed.

**Comment by garath** [comment]
We... completed all this!
