### ISSUE TITLE
log publish seems to not be using 1ES.PublishBuildArtifacts

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#2133]
See @directhex's thread here: https://teams.microsoft.com/l/message/19:32be8fb7e8164f8b95a112ab87d588c3@thread.skype/1709570888816?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1709570888816&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=1ES%20PT%20Porting%20Effort&createdTime=1709570888816

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by riarenas** [comment]
This is specifically about: 

Publishing log artifacts: https://github.com/dotnet/arcade/blob/2215d18d04a6565e9133c15ece7df7161fdf1e8e/eng/common/templates-official/job/job.yml#L204C1-L209C28
Publishing build retry configuration: https://github.com/dotnet/arcade/blob/2215d18d04a6565e9133c15ece7df7161fdf1e8e/eng/common/templates-official/job/job.yml#L251C1-L255C28

which use the `-publish` syntax so we missed converting them to the 1ES tasks.

**Comment by riarenas** [comment]
Fix has been merged in main. Will monitor that it gets to be available for repos tomorrow. Once we validate this fixes things I'll backport to release/8.0

**Comment by carlossanlop** [comment]
> Once we validate this fixes things I'll backport to release/8.0

Did this happen already?

**Comment by riarenas** [comment]
Yes. This was backported already to all branches.
