### ISSUE TITLE
Validate pipeline migration success

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#2142]
According to 1ES, any branch on a pipeline that successfully uses 1ES PT is marked as migrated. We should ensure that that's the case while other branches (i.e., servicing) are still in progress. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by dougbu** [comment]
do we also need a way to separately track the servicing progress❔
