### ISSUE TITLE
Switch the official arcade templates to use the publishing build pool

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#2146]
Currently, the publish-build-assets official arcade template is using the regular dnceng internal build pool instead of using the dedicated publishing pool. This was done because the images in that pool are not compatible with the 1es templates. Once https://github.com/dotnet/dnceng/issues/2080 has been fixed we should move back to the publishing pool.

* https://github.com/dotnet/arcade/blob/ae62c8d33c26fead308f9ad0f3bbc2018ecd1c14/eng/common/templates-official/job/publish-build-assets.yml#L62-L65
* https://github.com/dotnet/arcade/blob/ae62c8d33c26fead308f9ad0f3bbc2018ecd1c14/eng/common/templates-official/post-build/post-build.yml#L264

Should both be moved to using `NetCore1ESPool-Publishing-Internal`

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by dougbu** [comment]
#2080 is just waiting for rollout

**Comment by dougbu** [comment]
@riarenas shouldn't this be assigned to you and either marked as done (now that the backport bot has done its magic) or ready for rollout❔

**Comment by riarenas** [comment]
it's done
