### ISSUE TITLE
Remediating End-of-Life Docker Operating Systems

### ISSUE THREAD

**Issue by epananth** [dotnet/dnceng#2151]
In the Power BI report, we can identify Docker container operating systems that have either reached their End-of-Life (EOL) or are approaching it. The A&D team requires a systematic process to notify the product team about these containers, indicating which ones have reached or are nearing EOL status so that they can update them.

Eg : https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/973 

cc: @lbussell 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by MichaelSimons** [comment]
I personally gravitate towards opening issues.  This is more favorable to me over email notification because it is traceable/actionable.

**Comment by epananth** [comment]
Created epic https://github.com/dotnet/dnceng/issues/2543, so closing this epic
