### ISSUE TITLE
Add a temporary 1ES hosted pool with pre-provisioned machines

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#2160]
The runtime team would like their own exclusive pool to work on their migration to the 1ES pipeline templates. 

They would like to have machines instantly available when they queue their builds and not have to wait for machines to spin up, so this pool will need to have machines pre-provisioned, just like the [netcore1espool-publishing-internal](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/68672ab8-de0c-40f1-8d1b-ffb20bd62c0f/resourceGroups/netcore1espool-publishing-internal-rg/providers/Microsoft.CloudTest/hostedpools/NetCore1ESPool-Publishing-Internal/overview) pool.

Note that the helix-machines deployment code does not yet support adding pre-provisioning to the pool.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by riarenas** [comment]
I believe we mentioned keeping 5 machines around? We'll need to figure out how pre-provisioning works with multiple images, maybe we'll need to keep 5 machines around for each image that the pool uses?

**Comment by dougbu** [comment]
> the helix-machines deployment code does not yet support adding pre-provisioning to the pool

&hellip; yet. @epananth is working on this in her #2082 work.

> maybe we'll need to keep 5 machines around for each image that the pool uses?

that will be a significant sunk cost, albeit short term
