### ISSUE TITLE
Rotate Password

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#2161]
Need to rotate the password on the accounts found [here](https://coreidentity.microsoft.com/manage/service) to comply with new MS requirements.

### Release Note Category

- [ ] Feature changes/additions
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements

### Release Note Description

No release notes.

**Comment by riarenas** [comment]
Should we use secret-manager instead of directing to coreidentity? Only owners will be able to see the list of non people account, should that list be explicitly stated instead of a link that only certain folks will be able to access?

**Comment by tkapin** [comment]
@ilyas1974, as the list of non-personal accounts at https://coreidentity.microsoft.com/manage/service is user-specific, how do we ensure we have all accounts covered? I assume you have ownership of (almost) every non-personal account we use, but how can we make it certain? Cheers!

**Comment by tkapin** [comment]
Thanks Ilya, I confirm the account I see in coreidentity is captured on that page you reffered.

**Comment by garath** [comment]
Reopening to cover one additional account that was originally missed.

**Comment by garath** [comment]
Rotated and confirmed it's listed in a secret-manager manifest.
