### ISSUE TITLE
[1ES Template] Migrate generate-xcopy-msbuild pipeline to 1ES Templates 

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/dnceng#2170]
Migrating pipeline: https://dev.azure.com/dnceng/internal/_build?definitionId=1315&_a=summary

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
No release note needed

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-arcade/pullrequest/37999

**Comment by chcosta** [comment]
we could just delete this pipeline, OneEs is now producing the xcopy-msbuild package for us.

**Comment by garath** [comment]
> we could just delete this pipeline, OneEs is now producing the xcopy-msbuild package for us.

Do you know if there is anything that must be done to use the 1ES version? Or is deleting this pipeline all we need to do to clean up?
