### ISSUE TITLE
[1ES Template] Migrate dotnet-dnceng-ci pipeline

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/dnceng#2171]
Migrating dotnet-dnceng-ci

#### Pull requests
- split pr: https://github.com/dotnet/dnceng/pull/2129
- migrated ci: https://github.com/dotnet/dnceng/pull/2267

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
No release note needed

**Comment by AlitzelMendez** [comment]
First pr to split pr pipelien and ci pipeline: https://github.com/dotnet/dnceng/pull/2129

**Comment by garath** [comment]
This rolled-out this week I believe, yes?

**Comment by AlitzelMendez** [comment]
the rollout wasn't approved: https://dev.azure.com/dnceng/internal/_build/results?buildId=2408932&view=result so it didn't actually rolled out

**Comment by garath** [comment]
Uh... that looks like my mistake...

**Comment by AlitzelMendez** [comment]
> Uh... that looks like my mistake...

sorry for not bringing this up, I thought it was on purpose, because a lot of things were happening around :(

**Comment by AlitzelMendez** [comment]
rolled out is now done :)
