### ISSUE TITLE
Better mechanism for recovering on-prem machines

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#218]
Fall out from https://dnceng.visualstudio.com/internal/_workitems/edit/5102/

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by riarenas** [comment]
This issue needs more details before it's actionable @ilyas1974

**Comment by garath** [comment]
> This issue needs more details before it's actionable @ilyas1974

Emphasizing this. I don't believe this is actionable as it is. Is it worth keeping open? @ilyas1974

**Comment by garath** [comment]
Closing this as it's older than six months and the issue description isn't actionable as it stands now.
