### ISSUE TITLE
helix.dot.net CreateKnownIssues "error message or regex pattern" text is getting escaped twice

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/dnceng#2186]
Site: https://helix.dot.net/BuildAnalysis/CreateKnownIssues

After filling out all the fields and passing the validations, some characters are getting escaped twice when the clicking on the "Create your new known issue" link. Here is an example:

- Repository for new known issue: `dotnet/runtime`
- Build URL: https://dev.azure.com/dnceng-public/public/_build/results?buildId=600377
- Failing test or failing step: Leave blank
- [X] Regex pattern checked
- Error message or regex pattern: 
```
Failed to connect to port \d+ \(\d+\) on device \(error\: 61\)
```
- Sample text:
```
[17:10:46] dbug: [TCP tunnel] Xamarin.Hosting: Attempting USB tunnel between the port 56494 on the device and the port 56494 (44764) on the mac: 61
[17:10:46] dbug: [TCP tunnel] Xamarin.Hosting: Failed to connect to port 56494 (44764) on device (error: 61)
```

Resulting GitHub template issue:

ACTUAL

<img src="https://github.com/dotnet/dnceng/assets/1175054/f1964e3c-ad95-48fd-b75f-f135666d980d" width="600px" />

EXPECTED

<img src="https://github.com/dotnet/dnceng/assets/1175054/0db6e002-9c59-425e-bb74-b2cabfd4cb13" width="600px" />

@AlitzelMendez @missymessa @JulieLeeMSFT 

### Release Note Category
- [ ] Feature changes/additions 
- [x] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Fixed known issue helper escaping special characters

**Comment by AlitzelMendez** [comment]
Hi Carlos,

The problem that I see is that we are changing some symbols like `+` to \u002B, this seems problematic, and I will take a look at this.

For the expected scenario, it looks likes the input in the image is invalid, as can be observed the symbols are in red which most likely means that is not a valid json, my suggestion is to use double escape in there and to remove the symbols transformation such as: \u002B

**Comment by carlossanlop** [comment]
> as can be observed the symbols are in red which most likely means that is not a valid json

I don't think that's the problem. The red is "expected" in GitHub markdown, but only because syntax highlighter is unable to properly show the escaped characters as an expected part of that string. The string itself is correct.

I did have a tiny error making the expected screenshot. I should've escaped the colon character to `\:`. I corrected it.

You can confirm the regex is correct by testing it in https://regex101.com/ : 


![image](https://github.com/dotnet/dnceng/assets/1175054/b30b8e85-3aed-451f-b9e0-b3ceffded67f)

**Comment by AlitzelMendez** [comment]
could you please share your known issue?

**Comment by carlossanlop** [comment]
https://github.com/dotnet/runtime/issues/99649

I fixed the `\:` there too just now. Not sure how long KnownBuildError takes to update the hits table.

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/38426

**Comment by AlitzelMendez** [comment]
fixed and rolled out.
