### ISSUE TITLE
Additional telemetry when a storage account is attempted to be accessed and it fails

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#220]
Fall out from https://dnceng.visualstudio.com/internal/_workitems/edit/5102/

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by riarenas** [comment]
This is not part of the followup items in the issue and is not described in the RCA, so I'm not sure what this issue is asking for. Sending out for triage once again.

**Comment by missymessa** [comment]
Good idea, but not actionable right now.
