### ISSUE TITLE
Additional section for RCA template

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#224]
Add a section to the RCA temple for follow-up issues that were created due to the RCA. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by riarenas** [comment]
Done. Even older RCAs like our latest https://dnceng.visualstudio.com/internal/_workitems/edit/5102/ now includes the new section

**Comment by missymessa** [comment]
Oh that's neat, I didn't know it would retroactively add it :)
