### ISSUE TITLE
Document "not enough disk space" suggestions for customer documentation

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#225]
https://teams.microsoft.com/l/message/19:276707cdcf5d431caaa8792b29bd832d@thread.skype/1686775516622?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=147df318-61de-4f04-8f7b-ecd328c256bb&parentMessageId=1686775516622&teamName=.NET%20Eng%20Services&channelName=FR%20Internal&createdTime=1686775516622

Would probably be a good thing for our chatbot to be able to report on, too :)

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by ilyas1974** [comment]
I have updated our customer facing wiki - https://dev.azure.com/dnceng-public/public/_wiki/wikis/DNCEng%20Services%20Public%20Wiki/4/Home - with information about what action to take when space issues are experienced.
