### ISSUE TITLE
[1ES Template] Migrate  arcade-official-ci

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/dnceng#2270]
Pipeline migrating: https://dev.azure.com/dnceng/internal/_build?definitionId=6

arcade-official-ci-pr pipeline: 

### main
- pr split: https://github.com/dotnet/arcade/pull/14605
- ci: https://github.com/dotnet/arcade/pull/14613

### release/8.0
- pr split: https://github.com/dotnet/arcade/pull/14604
- ci: https://github.com/dotnet/arcade/pull/14624

### release/7.0
- pr split: https://github.com/dotnet/arcade/pull/14612
- ci: https://github.com/dotnet/arcade/pull/14648

### release/6.0
- pr split:  https://github.com/dotnet/arcade/pull/14614
- ci: https://github.com/dotnet/arcade/pull/14623

**Comment by garath** [comment]
Is there any more work waiting before closing this issue?

**Comment by AlitzelMendez** [comment]
yes, release/7.0 
I will create the pr in an hour or less, I am running the validation

**Comment by AlitzelMendez** [comment]
everything has been migrated, closing
