### ISSUE TITLE
Opt-in mechanism for behavior of build analysis check

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#23]
As part of the work in https://github.com/dotnet/arcade/issues/13309, the runtime team wants the build analysis check to report success if all the errors found by the analysis have a known issue associated with it. Instead of making all repos participating in build analysis to adapt to this change, we should think of a way to make this feature opt-in. Either via some configuration on the service side, or on the repository.

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Added repository configuration extension point for build analysis.

**Comment by riarenas** [comment]
I think we should do this in two phases:

1. While we enable the functionality and need to iterate quickly we can use a table in Azure. This allows us to turn the feature on or off quickly, as well as easily modifying the entity's schema as needed. The disadvantage here is that configuration is not discoverable by the repo owners, but this can be mitigated by providing docs. 

1. Once we are through phase 3 and have worked out any kinks with the feature, we transition to a checked in file in the repository. By this point we will know what, if any other levers we want to include in the feature, as well as give better control to repo owners.

**Comment by riarenas** [comment]
Right now we probably only care about configuring the check by repo and branch, but some possible additional configuration points that might be interesting to include at some point based on repo feedback:
* behavior for specific repo paths, build legs or tests
* threshold of occurrences of the known issues that are allowed to merge the PR
* age of the known issues
* different behaviors for repository or infra known issues

**Comment by riarenas** [comment]
Note: I did not consider adding full fledged feature flags to the project using an azure app configuration store as:
* It seemed overkill for this purpose
* Adds a new Azure resource instead of reusing the project's storage account
* dnceng does not yet have an established process for the management of feature flags.

**Comment by AlitzelMendez** [comment]
I think is a great idea :) a table give us the ability to move things around easily! :) and in this project tables are our friends!
let's start with that and as you said when this is more stable, we can transition to a checked in file!
