### ISSUE TITLE
Pool documentation in dnceng wiki is out of date

### ISSUE THREAD

**Issue by lbussell** [dotnet/dnceng#2313]
The pool info in the wiki (https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/554/Information-about-Build-Pools-in-the-'dnceng'-organization?anchor=public-pools-(https%3A//dnceng.visualstudio.com/public)) is out of date compared to the actual pool listing at https://dev.azure.com/dnceng-public/_settings/agentpools.

The documentation should be updated. Or, since the info is duplicated anyways, consider removing the wiki entry.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by riarenas** [comment]
I'd like to have @ilyas1974 thoughts on keeping the manual list. I'm in the "don't keep a manually updated list when there's a source of truth already" camp.

**Comment by ilyas1974** [comment]
@lbussell, Can you please take a look at https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1236/Pools-on-dnceng-and-dnceng-public and see if it is what you had in mind as a replacement for the out of date doc.

**Comment by lbussell** [comment]
@ilyas1974 looks great! Closing as completed.
