### ISSUE TITLE
Update Secret Manager to interface with service connections

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#2318]
While we currently have functionality to generate PATs, we do not have anything in place to update Azure DevOps Service Connections. This is something that @garath starting working on and should be completed to reduce the burden on the team. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by garath** [comment]
Closing in favor of dotnet/dnceng#2689
