### ISSUE TITLE
Builds in DevDiv losing access to variable groups

### ISSUE THREAD

**Issue by garath** [dotnet/dnceng#2335]
FR is getting reports of certain pipelines failing with errors indicating that the pipeline is not able to access particular variable groups. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by garath** [comment]
Internal conversation to diagnose the issue is [here](https://teams.microsoft.com/l/message/19:276707cdcf5d431caaa8792b29bd832d@thread.skype/1711039633633?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=147df318-61de-4f04-8f7b-ecd328c256bb&parentMessageId=1711039633633&teamName=.NET%20Eng%20Services&channelName=FR%20Internal&createdTime=1711039633633).

**Comment by dkurepa** [comment]
Opened up an ICM with the Azdo folks https://portal.microsofticm.com/imp/v3/incidents/incident/485409299/summary

**Comment by garath** [comment]
ICM traced error to an issue with a new ADO feature. Feature was disabled in DevDiv and now pipelines are working again.
