### ISSUE TITLE
Build analysis taking too long to get updated after escape mechanism used

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/dnceng#2336]
It was reported that escape mechanism is taking more than 8 minutes to get updated after the request is done.

This is expected, as the request is ingested on the build analysis queue, that also process all build and does the reprocessing of builds when a known issue is created.

But the expectation is that we communicate that it can take a while to get this updated, like -> the request has been received but it is going to take some time to get processed or something similar

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Build analysis now displays a tip mentioned escape mechanism and explaining that the wait time can take several minutes

**Comment by AlitzelMendez** [comment]
I have been thinking about this, and there is not much workaround about this. I think we can take two paths
- move all escape mechanism to their own service
- just post a general message on check run saying that his can take a while

The webhook messages are received by HelixAPI, these messages are send by both apps (.NET Helix and Build Analysis), after that, in general, nothing is really processed there, the events are redirected to their right queues.

The problem is that the HelixAPI uses .NET Helix App, so we can't post a message from there to a pull requests (it doesn't have the permissions) but more than that it would mean having two apps working around build analysis. meaning that Build Analysis will be relying on .NET Helix

The request made in here is to post a message that the update can take a while, so we can't send this message to Build Analysis queue because this message providing an update will take as long to appear as the update on the check run, so we should have a faster path to post this message, so we probably need a intermediary service, but once that we are here with this service, this particual escape mechanism is pretty simple as doesn't execute the build analysis, so it is pretty cheap to do, so we could just perform the whole process on this new service.


If we don't want to take that route we could just add more information on the build analysis check run,

**Comment by jkotas** [comment]
I have added a note about the delayed updates to https://github.com/dotnet/runtime/blob/main/docs/workflow/ci/failure-analysis.md#bypassing-build-analysis . If we cannot actually fix the problem and make the updates real-time, I think that this note is sufficient.

**Comment by AlitzelMendez** [comment]
a note was added to the build analysis check run and this was rolled out, closing
