### ISSUE TITLE
Unable to load the service index for source https://pkgs.dev.azure.com/...

### ISSUE THREAD

**Issue by jkotas** [dotnet/dnceng#2337]
### Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=612209

### Build leg reported

Build / osx-x64 Release NativeAOT / Build Tests

### Pull Request

https://github.com/dotnet/runtime/pull/100097

### Known issue core information

Fill out the known issue JSON section by following the [step by step documentation on how to create a known issue](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step)

```json
 {
    "ErrorMessage" : "error NU1301: Unable to load the service index for source https://pkgs.dev.azure.com/",
    "BuildRetry": false,
    "ErrorPattern": "",
    "ExcludeConsoleLog": false
 }
 ```

 @dotnet/dnceng

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Known issue validation
**Build: :mag_right:** 
**Result validation:** :warning: Provided build not found. Provide a valid build in the "**Build:** :mag_right:" line.
**Validation performed at:** 6/19/2024 10:51:53 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[818460](https://dev.azure.com/dnceng-public/public/_build/results?buildId=818460)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/818460/logs/143)|dotnet/sdk#43696|
|[818433](https://dev.azure.com/dnceng-public/public/_build/results?buildId=818433)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/818433/logs/129)|dotnet/sdk#43070|
|[818395](https://dev.azure.com/dnceng-public/public/_build/results?buildId=818395)|dotnet/sdk|Run dotnet-format on dotnet/msbuild MSBuild.sln|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/818395/logs/214)|dotnet/sdk#43070|
|[818205](https://dev.azure.com/dnceng-public/public/_build/results?buildId=818205)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/818205/logs/225)|dotnet/sdk#43690|
|[818350](https://dev.azure.com/dnceng-public/public/_build/results?buildId=818350)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/818350/logs/129)|dotnet/sdk#43239|
|[818354](https://dev.azure.com/dnceng-public/public/_build/results?buildId=818354)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/818354/logs/143)|dotnet/sdk#43694|
|[818215](https://dev.azure.com/dnceng-public/public/_build/results?buildId=818215)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/818215/logs/129)|dotnet/sdk#43070|
|[818178](https://dev.azure.com/dnceng-public/public/_build/results?buildId=818178)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/818178/logs/143)|dotnet/sdk#43239|
|[818016](https://dev.azure.com/dnceng-public/public/_build/results?buildId=818016)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/818016/logs/225)|dotnet/sdk#43491|
|[818015](https://dev.azure.com/dnceng-public/public/_build/results?buildId=818015)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/818015/logs/225)|dotnet/sdk#43620|
|[818097](https://dev.azure.com/dnceng-public/public/_build/results?buildId=818097)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/818097/logs/143)|dotnet/sdk#43607|
|[818011](https://dev.azure.com/dnceng-public/public/_build/results?buildId=818011)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/818011/logs/153)|dotnet/sdk#43627|
|[2546577](https://dev.azure.com/dnceng/internal/_build/results?buildId=2546577)|dotnet-dotnet|Build|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2546577/logs/2256)||
|[817969](https://dev.azure.com/dnceng-public/public/_build/results?buildId=817969)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/817969/logs/129)|dotnet/sdk#43642|
|[2531387](https://dev.azure.com/dnceng/internal/_build/results?buildId=2531387)|dotnet-roslyn|Build|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2531387/logs/382)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|8|14|15|

**Comment by epananth** [comment]
This was resolved. Closing this
