### ISSUE TITLE
Investigate PR Assistant bot use in our repos

### ISSUE THREAD

**Issue by dougbu** [dotnet/dnceng#2368]
1ES supports an AI-backed PR reviewer under the Merlinbot that should be useful for catching security and other issues earlier in the development cycle. The feature is enabled at the repository level (e.g., see https://github.com/1ES-microsoft/GitOps.Defaults/blob/main/app-primitives/pull-request-copilot-activation.yml#L912 for the start of DevDiv's repo list) but can be customized in a number of ways. For example, we may want to enable the bot only for `internal/release/*` branches in our mirror repos.

Features include the above-mentioned PR reviews as well as description updates and responding to [Copilot commands](https://eng.ms/docs/products/1es-merlinbot/extensions/prassistantcopilot). [PR Assistant docs](https://eng.ms/docs/products/1es-merlinbot/extensions/prassistant) provides the full docs.

### Release Note Category

- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements

### Release Note Description

Enabled the [PR Assistant bot](https://eng.ms/docs/products/1es-merlinbot/extensions/prassistant) in some internal DNCEng repositories.

**Comment by missymessa** [comment]
Looks like it's running on our internal-only repos, so we're considering this done. :)
