### ISSUE TITLE
Add Matrix of Truth Pipeline to build monitor

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#2382]
Please add the matrix of truth pipeline (dotnet-helix-machines-matrix-of-truth) to build monitor so we are informed when the pipeline does not run successfully. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description
No release note needed.

**Comment by AlitzelMendez** [comment]
PR: https://github.com/dotnet/dnceng/pull/2465
