### ISSUE TITLE
Update Matrix of Truth

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#2383]
There are several updates that need to be made to the matrix of truth
- Add newer Operating Systems to the Matrix
- Add information about .NET 9 support
- Display non-supported OSes that are still being used though docker
- Update EOL dates 
- Add support for new hardware types

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Updating Matrix of Truth with current information

**Comment by epananth** [comment]
completed this. Closing it
