### ISSUE TITLE
Secret manager should help identify dependent secrets when force-rotating a parent secret

### ISSUE THREAD

**Issue by garath** [dotnet/dnceng#2389]
Secret-manager should help identify dependent secrets when rotating parent secrets. For example, `kusto-connection-string` uses information from an `ad-application` secret. Changing the latter invalidates the former. 

See also #2320, which describes an outage where we missed updating the Kusto secret after rotating a client secret. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by missymessa** [comment]
Dupe of https://github.com/dotnet/dnceng/issues/1202
