### ISSUE TITLE
Update MoT to support 1ES Pools

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#2400]
With all the changes that were made recently to the 1ES agent pools in Azure DevOps, I do not believe the data in the Matrix of Truth is accurate. Please evaluate what the current status of the agent pools is and modify the Matrix of Truth data to reflect any changes. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Update MoT to support 1ES Pools

**Comment by dkurepa** [comment]
The matrix was missing the 1es PT images in it's configuration. This PR adds those images, and refactors the code a bit to better reflect reality https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/38695

**Comment by dougbu** [comment]
@dkurepa did your changes in https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/40291 or other helix-machines work resolve this issue❓
