### ISSUE TITLE
The check "runtime (Build browser wasm li...) was stuck for 2 days with blank error message.

### ISSUE THREAD

**Issue by cshung** [dotnet/dnceng#2410]
### Build

https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=624502

### Build leg reported

Build / browser-wasm linux Release LibraryTests

### Pull Request

https://github.com/dotnet/runtime/pull/98712

### Known issue core information

Fill out the known issue JSON section by following the [step by step documentation on how to create a known issue](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step)

```json
 {
    "ErrorMessage" : "",
    "BuildRetry": false,
    "ErrorPattern": "",
    "ExcludeConsoleLog": false
 }
 ```

 @dotnet/dnceng

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Additional information about the issue reported

I am not sure what can I do with a blank error message, so I just left the "Known issue core information" blank.

![image](https://github.com/dotnet/dnceng/assets/3410332/d6e5274f-d819-4a30-8269-bb784ada35fc)

Force pushing a squashed version doesn't change anything, it is still stuck.

**Comment by riarenas** [comment]
As the error in the build says: https://dev.azure.com/dnceng-public/public/_build/results?buildId=624502&view=logs&j=d4e38924-13a0-58bd-9074-6a4810543e7c this is due to a disconnect by the agent, which didn't leave an error message. I would attempt to rerun the leg. IF this is consistent for your PR, consider investigating whether your tests are causing an agent disconnect.

I don't think build analysis could've done much more here. The error in Azure devops is literally that there was no message, so build analysis presents as blank.

I'm closing this issue as it's not actionable by us.

**Comment by cshung** [comment]
@riarenas It is still stuck on rerun by clicking the rerun button, it is stuck there after reporting "Received request to deprovision: The request was cancelled by the remote provider." again.

Last week I tried to push some other changes there and that doesn't change a thing either.

**Comment by riarenas** [comment]
I would work with your repository's engineering team to figure out what you need to do to rerun this leg of your PR.

**Comment by cshung** [comment]
> I would work with your repository's engineering team to figure out what you need to do to rerun this leg of your PR.

Who would be a good person to talk to for dotnet/runtime?

**Comment by riarenas** [comment]
Basically, without an actual error, we cannot use a known issue for this.

It looks like your latest attempts are timing out during the build step.

**Comment by riarenas** [comment]
@dotnet/runtime-infrastructure might be able to help.

**Comment by cshung** [comment]
> @dotnet/runtime-infrastructure might be able to help.

Thank you!
