### ISSUE TITLE
Answer questions regarding .NET's Microbuild signing setup.

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#2424]
The Microbuild team is requesting details of the current setup we use to get the certificates they need for the signing plugin to work. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by markwilkie** [comment]
This was setup with Trevo back in the day - prob be good to touch bases with him.

**Comment by riarenas** [comment]
Yep. Trevor is part of the team asking the questions, and this has changed a lot. I'm... getting confused as I look through this.

**Comment by riarenas** [comment]
Questions were answered. Once the Microbuild team has a path forward we'll create issues for any work related to the changes needed.

**Comment by riarenas** [comment]
Today, all our Microbuild signing machines are Azure VMs in 1ES hosted pools. We support two types of images in these pools:

* Our custom build images, where we add the artifact that adds a script to the machine to obtain the certs on boot.
* the 1es-* images use a provisioning script that does the same.

As changes are needed, we should consider consolidating only on the second item, and using the provisioning script to set the certs up regardless of image.
