### ISSUE TITLE
GitHub webhook causing incorrect linking/issue state changes in Azure DevOps issues

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#243]
A webhook in GitHub is causing incorrect linking of issues or state change of issues in Azure DevOps. 

For example, this comment was left on an issue in Azure DevOps: https://dnceng.visualstudio.com/internal/_workitems/edit/5102/#7296315

issue that commented was related to: https://github.com/dotnet/vscode-csharp/issues/5102

commit: [Resolve issue #5102: Support input variables for `envFile` (#5189) · dotnet/vscode-csharp@7b1f541 (github.com)](https://github.com/dotnet/vscode-csharp/commit/7b1f541aec032c36961677005adba4853fa30aad)

dnceng mirror commit: [Commit 7b1f541a: Resolve issue #5102: Support input variables for `envFile` (#5189)... - Repos (visualstudio.com)](https://dnceng.visualstudio.com/internal/_git/63e32aa5-8db9-4c0d-8886-e8ec4b36e8d7/commit/7b1f541aec032c36961677005adba4853fa30aad)

Additionally, some brief investigation with @dibarbet showed that about 125 issues in Azure DevOps have been affected indirectly by him via this bug. I would assume that more than that have been affected through others' activities. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by AlitzelMendez** [comment]
@premun gave some updates on this that confirmed what I saw during my investigation.

This is a summary of what he says


``` What's going on is that if we mirror a commit from GitHub to AzDO, and it contains some #ID it does the same as GitHub does and auto-resolves the item in AzDO.

This only happens when some GH repo gets within a range of IDs that are currently in AzDO so it happens only sometimes which makes it even harder to notice.

https://learn.microsoft.com/en-us/azure/devops/repos/git/resolution-mentions?view=azure-devops

Close work items using commit messages - Azure Repos

How to close work items using commit messages

```
 
looks like we can remove this feature
![MicrosoftTeams-image (11)](https://github.com/dotnet/dnceng/assets/6895254/fab3c0f6-05f5-4ee6-ab12-e3e6dcd5c611)

We can take this route, we just need to send an email to inform them about this change and confirm no one is using the feature.

**Comment by premun** [comment]
We should only do that for mirrored repositories but I would go as far and say that this will be turned off.

We should also update instructions for new repo creation.

**Comment by AlitzelMendez** [comment]
This has been done and I created this pr to update the documentation: https://dev.azure.com/dnceng/internal/_git/dotnet-eng-wiki/pullrequest/32216
