### ISSUE TITLE
Close win7 queues

### ISSUE THREAD

**Issue by garath** [dotnet/dnceng#2498]
Windows 7 is EOL and the PMs have given the ok to shut-down those queues.

### Release Note Category
- [X] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Removed the windows 7 Helix queues

**Comment by riarenas** [comment]
Starting work on this!

My approach would be something like:
* [ ] deprecate the queue
* [ ] Give two week notice to partners that the queue will be removed
* [ ] Remove the queue definition, and deploy the changes.
* [ ] Delete any leftover resources related to the win 7 queue
* [ ] Celebrate that we won't get any more Windows 7 ICMs

**Comment by dougbu** [comment]
> deprecate the queue by deadlettering messages

You may want to instead forward queue messages to a corresponding Win8 one. Dead-lettering breaks some of our tests unfortunately. See at least `ArtifactBelongingTest.NoQueuesDeprecatedToDeadletter()`.

**Comment by riarenas** [comment]
Does it make sense to move workloads in windows 7 to windows 8? wouldn't that cause more noise than help? should we just rip out the queue instead in one go?

**Comment by dougbu** [comment]
> Does it make sense to move workloads in windows 7 to windows 8? wouldn't that cause more noise than help? should we just rip out the queue instead in one go?

Options include using our telemetry to find the remaining users, doing nothing prior to warning our partners, dead-lettering but removing the tests that fail as a result (temporarily), build warnings (I seem to remember we have options that warn in build jobs when Helix jobs use queues that are due for removal), and forwarding to other queues that will work for longer. Our process may have been consistent in the past but I'm not sure. I also don't have a recommendation for the "best" option.

Re: "using our telemetry to find the remaining users" we may find it's only a couple of repos still testing on Win7.

**Comment by riarenas** [comment]
Our telemetry says it's only one repo. Updated plan:

* [ ] Let the repo owners know they should remove usage, warn them we plan to remove the queue on 4/24
* [ ] Remove the queue, and deploy the removal on 4/24

**Comment by riarenas** [comment]
PR for removal: https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/38885

**Comment by ilyas1974** [comment]
@riarenas , as part of this work item, can you please close the following ICM after roll out?
https://portal.microsofticm.com/imp/v3/incidents/incident/492083431/summary

**Comment by riarenas** [comment]
I'm leaving my ops rotation today, so I don't think I'll be the person to do that, but whoever picks this up should note that.

**Comment by missymessa** [comment]
Ricardo's PR got a few approvals, so I'm merging it in.
