### ISSUE TITLE
Add Azure Linux 3.0 support to helix

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#2523]
Microsoft has announced the preview release of Mariner 3.0 (rebranded as Azure Linux 3.0). We need to make sure this new operating system is available within our environment as well as add support for it within the Matrix of Truth. 

### Release Note Category
- [X] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Add support for Azure Linux 3.0 (Mariner 3.0)

**Comment by richlander** [comment]
Note: We've adopted Azure Linux 3.0 in containers already. We did that early because Azure Linux 3.0 GA date is too late in .NET 9 release to wait. The hosts are not quite as impactful, however, it would be nice to have the opportunity to start the host transition as well.

https://github.com/dotnet/runtime/blob/main/docs/workflow/building/coreclr/linux-instructions.md#docker-images

**Comment by epananth** [comment]
Assigning this to @davfost,

I already have a PR out for this https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/41809

some information for this is incorrect 

I spoke to @dougbu 

Need to update 

  Image:
    Publisher: canonical
    Offer: 0001-com-ubuntu-server-jammy
    Sku: 22_04-lts-arm64
    Version: 22.04.202408010

We could not find the name of the image. You should prob work with DDfun to get more information about the image

**Comment by davfost** [comment]
Handing off to @chcosta

**Comment by ilyas1974** [comment]
Some helpful links
https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1142
https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/src/azurelinux/3.0/helix/Dockerfile

**Comment by epananth** [comment]
Finally got a green build https://dev.azure.com/dnceng/internal/_build/results?buildId=2551241&view=logs&s=9e5bb256-3a69-5ac1-6d3a-c533213b8bf5

**Comment by ilyas1974** [comment]
Changes have been rolled out.

**Comment by richlander** [comment]
Sweet! I will try that shortly on runtime main.
