### ISSUE TITLE
cycle Storage account key

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#2524]
### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by garath** [comment]
Resolved. Some additional context in [FR Internal chat](https://teams.microsoft.com/l/message/19:276707cdcf5d431caaa8792b29bd832d@thread.skype/1712600171804?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=147df318-61de-4f04-8f7b-ecd328c256bb&parentMessageId=1712600171804&teamName=.NET%20Eng%20Services&channelName=FR%20Internal&createdTime=1712600171804)
