### ISSUE TITLE
Check on sick machines

### ISSUE THREAD

**Issue by dougbu** [dotnet/dnceng#260]
As @ilyas1974 and I chatted about the root cause of S360 alerts that showed up despite "machines used under 7 days are already excluded from telemetry", I began considering ways to avoid the problem in the future.

The root cause of some machines lasting more than a week is twofold: skipped rollouts and sick machines. We can't do much about skipped rollouts but we can delete sick machines even if we're not rolling out. @ilyas1974 mentioned this in <https://dev.azure.com/dnceng/internal/_workitems/edit/4948#7312352> and suggested I create this issue.

We could start w/ a query and a process change i.e., have a canned query to list sick machines (in the sense they're orphaned from Helix and likely generally incommunicado) and a process we execute on (say) Mondays and Fridays to run the query and kill the listed machines manually. Might even be able to get away w/ less e.g., just do the process on Wednesdays when we are delaying or skipping our usual rollout.

The fullest approach would be to automate executing the query and deleting the machines. If that ran (say) daily, rollouts should go smoother and we should never (well, never say never) get S360 alerts just because a machine "lived" too long.

### Release Note Category

- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements

### Release Note Description

At the first click stop, a note such as "Designed a query and enhanced our processes to avoid leaving unregistered build and test machines around. The aim here is to avoid unactionable security alerts.

**Comment by garath** [comment]
> and we should never (well, never say never) get S360 alerts just because a machine "lived" too long.

Yeah, I think it's still possible for this to happen under unlikely-but-not-unheard-of circumstances.

**Comment by riarenas** [comment]
I think I don't understand why this is different from what the dead VM cleaner does. Do we think there's a bug there? We recently fixed the service to run quicker. I'm going to close this issue as I can't see how having a manual process would help here. Feel free to reopen and bring back to triage if you believe the fixes to the vm cleaner are not sufficient for this scenario.

**Comment by dougbu** [comment]
@riarenas does the VM cleaner really do a solid job❔ I thought cleaning up machines that shouldn't exist in various scale sets was a big part of our rollouts. And, VMs that hang around for 7 days or more is a clear indicator _something_ isn't happening that should be.

**Comment by riarenas** [comment]
VM cleaner needs two passes to clean any machines that are not heartbeating. Which means it takes two hours and makes it unsuitable for point in time efforts like the rollouts.

I still reject the idea of having a manual process that we make part of our weekly rotations for something that doesn't happen often.

**Comment by dougbu** [comment]
I'm confused. I didn't suggest the end state would be manual

**Comment by riarenas** [comment]
The only actionable piece of this issues that could be started by me as the person in rotation on ops is:

> We could start w/ a query and a process change i.e., have a canned query to list sick machines (in the sense they're orphaned from Helix and likely generally incommunicado) and a process we execute on (say) Mondays and Fridays to run the query and kill the listed machines manually.

Do we want to maybe split the issues? 

How often do we have machines that live long enough to trigger this alert?

**Comment by dougbu** [comment]
> Do we want to maybe split the issues?

that might make sense

> How often do we have machines that live long enough to trigger this alert?

we've seen S360 alerts about machines that shouldn't live longer than a day (but last a week) multiple times but I don't have a count. we'd need to inventory the machines mentioned in the S360 dashboard a few times to get accurate numbers.

how often do you, @garath, and @AlitzelMendez hit machines the VM cleaner shouldn't have left around but cause problems during rollouts❔ that number might be easier to guage

**Comment by riarenas** [comment]
> how often do you, @garath, and @AlitzelMendez hit machines the VM cleaner shouldn't have left around but cause problems during rollouts❔ that number might be easier to guage

Given how we only fixed the vm cleaner this past rollout, that will require some more time to be able to gauge. My anecdotal experience is that most machines I have to clean have only existed for a few hours.
