### ISSUE TITLE
SF failing after secrets are rotated 

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/dnceng#2616]
In some scenarios when a secret is rotated SF is not able to get properly working, I think there is a gap in how some secrets are monitored inside the services, I will try to narrow all these secrets to see if we can stop restarting SF

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description
Fixed helix api not properly reloading secrets after they are rotated

**Comment by garath** [comment]
Is there something in particular motivating this? It might make sense to wait until @davfost's service principal epic is finished as I expect that will eliminate many of these gaps.

**Comment by AlitzelMendez** [comment]
> Is there something in particular motivating this? It might make sense to wait until @davfost's service principal epic is finished as I expect that will eliminate many of these gaps.

not really, my motivation is that we have been having frequent reports of secrets leaked and every time we need to restart SF

**Comment by garath** [comment]
We spoke in person, so just to keep this thread up: be aware that Chris is about to make a significant change to Helix and David will be making changes to authentication in general. 

I am super interested, though, if you find the spots where access to the managed storage accounts would fail if the keys were rotated. Fixing that will have good, immediate impact.

**Comment by AlitzelMendez** [comment]
Stu and I synched about this offline :) 
I will narrow my work to the storage as it is the most impactful area right now and in that way we can have a more manageable/smaller change

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/39161

**Comment by missymessa** [comment]
Will be fixed by work in Wave 1. Closing.
