### ISSUE TITLE
[Buid Analysis] Fix some test failures not getting analyzed 

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/dnceng#2628]
An issue was reported that some tests were no matching his known issues when this was expected, after some investigation we found that we are not analyzing all the tests, we are using an azure sdk to get the check runs but it is returning only 100 check runs when some repositories like runtime now has around 105 test runs, so some check runs aren't being analyzed and this is causing not matching some known issues. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Fixed build analysis not analyzing all failing test causing that known issues were skipping some test for analysis

**Comment by lewing** [comment]
cc @JulieLeeMSFT

**Comment by JulieLeeMSFT** [comment]
Thanks for the bug report, @lewing. 
Very good  @AlitzelMendez  already rootcaused it.

**Comment by AlitzelMendez** [comment]
pull request: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/39094

**Comment by AlitzelMendez** [comment]
this was rolled out, this should be fixed now, let me know if you are still facing this issue.
