### ISSUE TITLE
SSA Support Features

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#2632]
## Context

With the shift from First Responsders to Shared Services Advisors, we need to have processes in place that are sustainable for .NET Eng Services to manage and straightforward for our customers to use (for self-service processes). This epic will address any processes, services, et cetera, that are required to achieve that goal. 

## Business goals

- [ ] New processes/features/services are sustainable for .NET Eng Services devs and product devs
- [ ] Documentation is provided for product devs to be able to use new processes/features/services

**Comment by ilyas1974** [comment]
As a team, we have decided what is supported within SSA and what is part of our Ops team. Details can be found at https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1096/SSA-vs-Ops.md
