### ISSUE TITLE
Create a Compendium of Self-Service Info for Customers

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#2633]
This should be a landing page of sorts to help direct our customers where to find information or processes for accomplishing a request they have through self-service means. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by ilyas1974** [comment]
Site has been created - https://dev.azure.com/dnceng-public/public/_wiki/wikis/DNCEng%20Services%20Public%20Wiki/4/Home and includes the information above.
