### ISSUE TITLE
Document CLA Bot info

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#2634]
- [ ] Who to contact when CLA Bot is broken (add to this wiki page: https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1019/Reaching-out-to-Partner-Teams)
- [ ] How to mitigate common issues with CLA Bot (include a link to this documentation in whatever results from this issue: https://github.com/dotnet/dnceng/issues/2633)

**Comment by ilyas1974** [comment]
Contacts have been added to the wiki page listed above and coming issues have been documented for our customers.
