### ISSUE TITLE
Retriage "Operations" view on board

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#273]
https://github.com/orgs/dotnet/projects/86/views/16

- [ ] Retriage issues
- [ ] Delete or reconfigure "Operations" view to use the Operations label in the query

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by garath** [comment]
This was sorted a bit ago.
