### ISSUE TITLE
Guardian/SpotBugs step failing because of missing java

### ISSUE THREAD

**Issue by premun** [dotnet/dnceng#2740]
> This is an issue for tracking an IcM we opened with the Guardian team: https://portal.microsofticm.com/imp/v3/incidents/incident/499541728/summary

The auto-injected Guardian step SpotBugs started to fail this week and is consistently failing.
The error is following:

```
##[error]ToolLauncherNotFoundException: Could not successfully find the java tool launcher. Please ensure any dependent frameworks are installed.
##[error]Win32Exception: An error occurred trying to start process 'java' with working directory 'D:\a\_work\1'. The system cannot find the file specified.
```

Example build: 
https://dnceng.visualstudio.com/internal/_build/results?buildId=2442859&view=logs&j=9050e078-31bf-5111-d8ec-8b6fa95caf9c&t=49b7ce52-27c5-55b3-42b4-f221aea95a78&l=77

**Comment by premun** [comment]
We were advised to check whether SpotBugs was actually ever running - maybe we never had java installed.
We were also advised to silence the check if needed: https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/sdlanalysis/overview

**Comment by dkurepa** [comment]
There's a step before the actual `SpotBugs` scan that checks if the repo contains jar files, if it does the scan runs. The last time the windows leg was green, the scan didn't find any `jars` https://dnceng.visualstudio.com/internal/_build/results?buildId=2433978&view=logs&j=9050e078-31bf-5111-d8ec-8b6fa95caf9c&t=13ee69c4-8290-5298-26a1-897420ec7c4f, but it's finding 6 now. Will check what these jars actually are

**Comment by dkurepa** [comment]
Aspnetcore does have some shipping java packages, the whole SignalR bundle that gets published to Maven central. I'm not sure how that will look in Unified Build land.

@wtgodbe I noticed that in the aspnetcore pipeline, the `Guardian: Check if enable SpotBugs` scan doesn't find any jars, even tho some should be there, is there some special setting that's being used there?

**Comment by ViktorHofer** [comment]
Do you have an advice on what to do? This still nukes all our unified-build Windows legs: https://dev.azure.com/dnceng/internal/_build/results?buildId=2447155&view=results

How is that check supposed to run if it can't find Java? Shouldn't that be brought in by that step?

**Comment by dkurepa** [comment]
looks like there is a way to disable the scan: https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/sdlanalysis/overview#:~:text=extends%3A%0A%20%20template%3A%20v1/1ES.Official.PipelineTemplate.yml%401esPipelines%0A%20%20parameters%3A%0A%20%20%20%20sdl%3A%0A%20%20%20%20%20%20spotBugs%3A%0A%20%20%20%20%20%20%20%20enabled%3A%20false

perhaps we should do that to unblock the build, while we're figuring out why it suddenly started running.

**Comment by ViktorHofer** [comment]
Yeah looks like this will do the job:

```yml
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    sdl:
      spotBugs:
        enabled: false
```

**Comment by ViktorHofer** [comment]
Submitted https://github.com/dotnet/sdk/pull/40759

**Comment by wtgodbe** [comment]
>  I noticed that in the aspnetcore pipeline, the Guardian: Check if enable SpotBugs scan doesn't find any jars, even tho some should be there, is there some special setting that's being used there?

I'm really not sure, is it supposed to find the output .jars or the ones we're using? As far as I know, we don't do anything "special".

**Comment by wtgodbe** [comment]
Is there any way we can get the java libs used by aspnetcore onto the build machines? SpotBugs has been constantly failing with:

> ##[error]The following classes needed for analysis were missing:
##[error]  okhttp3.CookieJar
##[error]  okhttp3.Callback
##[error]  okhttp3.WebSocketListener
##[error]  org.msgpack.value.ValueType
##[error]  org.msgpack.core.MessageFormat
##[error]  com.google.gson.stream.JsonReader
##[error]  com.google.gson.stream.JsonToken
##[error]  com.google.gson.JsonElement
##[error]  com.google.gson.JsonArray
##[error]  com.google.gson.Gson
##[error]  com.google.gson.JsonParser
##[error]  okhttp3.WebSocket
##[error]  okhttp3.Response
##[error]  okio.ByteString

And the list goes on. We've already disabled it in servicing.

**Comment by dkurepa** [comment]
We have disabled the problematic check in the VMR. Closing this issue

**Comment by wtgodbe** [comment]
I'll disable it in aspnetcore for now as well, but is there a chance we'll be forced to turn it back on as part of Spring Grove?
