### ISSUE TITLE
TEST KNOWN ISSUE IN DNCENG

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#276]
### Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=316985

### Known issue core information

```json
 {
    "ErrorMessage" : "1 new pre-builts discovered! Detailed usage report can be found at",
    "BuildRetry": false,
    "ErrorPattern": "",
    "ExcludeConsoleLog": false
 }
 ```

 @dotnet/dnceng

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[325336](https://dev.azure.com/dnceng-public/public/_build/results?buildId=325336)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/325336/logs/44)|dotnet/sdk#33691|
|[322261](https://dev.azure.com/dnceng-public/public/_build/results?buildId=322261)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/322261/logs/45)|dotnet/sdk#33610|
|[320906](https://dev.azure.com/dnceng-public/public/_build/results?buildId=320906)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/320906/logs/45)|dotnet/sdk#33577|
|[320766](https://dev.azure.com/dnceng-public/public/_build/results?buildId=320766)|dotnet/arcade|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/320766/logs/13)|dotnet/arcade#13847|
|[320687](https://dev.azure.com/dnceng-public/public/_build/results?buildId=320687)|dotnet/arcade|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/320687/logs/10)|dotnet/arcade#13847|
|[320355](https://dev.azure.com/dnceng-public/public/_build/results?buildId=320355)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/320355/logs/159)|dotnet/sdk#33468|
|[319509](https://dev.azure.com/dnceng-public/public/_build/results?buildId=319509)|dotnet/arcade|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/319509/logs/15)|dotnet/arcade#13847|
|[319455](https://dev.azure.com/dnceng-public/public/_build/results?buildId=319455)|dotnet/arcade|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/319455/logs/15)|dotnet/arcade#13847|
|[316985](https://dev.azure.com/dnceng-public/public/_build/results?buildId=316985)|dotnet/arcade|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/316985/logs/10)|dotnet/arcade#13847|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|9|

**Comment by premun** [comment]
@missymessa is this issue supposed to track hits for Michael's team? Or is there another reason?

**Comment by missymessa** [comment]
Test completed. Closing.
