### ISSUE TITLE
Unable to load the service index for source https://pkgs.dev.azure.com/devdiv/_packaging/dotnet-core-internal-tooling/nuget/v3/index.json

### ISSUE THREAD

**Issue by agocke** [dotnet/dnceng#2778]
This is hitting a lot of our official builds, see https://dev.azure.com/dnceng/internal/_build/results?buildId=2446012 for an example.

\+ @markwilkie

**Comment by missymessa** [comment]
This was related to when we had to manually rotated PATs for service connections. Closing.
