### ISSUE TITLE
Cannot rotate expired secret for the DotNet Eng Services Secret Manager application

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/dnceng#285]
AzDo issue: https://dev.azure.com/dnceng/internal/_workitems/edit/5180

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by riarenas** [comment]
This has been fixed. Details in the linked work item
