### ISSUE TITLE
Clean up internal repos for ASPNetCore

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#2926]
Delete
https://dev.azure.com/dnceng/internal/_git/Azure-dotnet-extensions-experimental
 
Disable
https://dev.azure.com/dnceng/internal/_git/aspnet-Extensions
https://dev.azure.com/dnceng/internal/_git/dotnet-astra
https://dev.azure.com/dnceng/internal/_git/aspnet-AspNetCore

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by wtgodbe** [comment]
CC @maumar @SamMonoRT in case you want to disable EFCore & EF6 as well

**Comment by SamMonoRT** [comment]
hi @missymessa - the following two repos should also be deleted:

https://dev.azure.com/dnceng/internal/_git/aspnet-EntityFramework6 
https://dev.azure.com/dnceng/internal/_git/aspnet-EntityFrameworkCore

cc @maumar @AndriySvyryd

**Comment by missymessa** [comment]
All repos should be disabled/deleted as requested!

**Comment by SamMonoRT** [comment]
Thank you for the quick turnaround @missymessa
