### ISSUE TITLE
Weekly build failures

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#2955]
Helix-machines and helix-service weekly builds are failing with:

```
Exception: Microsoft.Rest.Azure.CloudException: The access token is from the wrong issuer 'https://sts.windows.net/975f013f-7f24-47e8-a7d3-abc4752bf346/'. It must match the tenant 'https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later.
```

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by garath** [comment]
I've seen this before. Running secret-manager locally should be enough to unblock the weekly builds. It seems like there's something more to this error as it keeps popping up so it would be good to create a follow-up Ops issue to find the root cause.

**Comment by riarenas** [comment]
Ran secret-manager locally over all manifests on both repos. No manual intervention was needed. 

I'm running the weekly pipelines as well to validate that there are no more secrets that still need attention:

https://dev.azure.com/dnceng/internal/_build/results?buildId=2461675&view=results
https://dev.azure.com/dnceng/internal/_build/results?buildId=2461680&view=results

**Comment by riarenas** [comment]
Both weekly builds are passing now. I'll create a follow-up ops issue to figure out the underlying error and close this afterwards.

**Comment by riarenas** [comment]
Opened https://github.com/dotnet/dnceng/issues/2964 for fixing the underlying issue
