### ISSUE TITLE
secret-manager failures during scheduled builds

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#2964]
Scheduled builds for the weekly pipelines are sometimes failing with errors that seem related to the service connections they use to authenticate with Azure.

> Exception: Microsoft.Rest.Azure.CloudException: The access token is from the wrong issuer. It must match the tenant associated with this subscription. 

Some recent examples:
* [dnceng-weekly](https://dev.azure.com/dnceng/internal/_build/results?buildId=2450015&view=results)
* [helix-machines-weekly](https://dev.azure.com/dnceng/internal/_build/results?buildId=2460851&view=results)
* [helix-service-weekly](https://dev.azure.com/dnceng/internal/_build/results?buildId=2461064&view=results)

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by dougbu** [comment]
`secret-manager` uses an MI everywhere doesn't it❓ is this issue still relevant❓

**Comment by garath** [comment]
I believe I fixed this in dotnet/dnceng#3310

**Comment by dougbu** [comment]
so close this issue❓
