### ISSUE TITLE
Guidance to set up APIScan in a pipeline in dnceng

### ISSUE THREAD

**Issue by Shyam-Gupta** [dotnet/dnceng#2965]
This request is for WinForms designer private Github repo: https://github.com/microsoft/winforms-designer.
This repo produces a VSIX and an SDK NuGet package. The VSIX gets inserted into VS and the corresponding binaries are scanned automatically for APIScan centrally. However, the NuGet package is released externally to customers, and for that we have received guideline that we need to run APIScan on our own for the repo.

We already have a dnceng pipeline which runs APIScan: https://dev.azure.com/dnceng/internal/_build?definitionId=1259
This pipeline, however, does not use Managed Identity at present, which is a security issue. We need to resolve it by 5/31.

Since this pipeline is classified as Non-Production, we haven't moved it to 1ES yet. But the changes to move to 1ES are in one of my private branch and we can commit that if required.

I found this [wiki](https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/25351/APIScan-step-by-step-guide-to-setting-up-a-Pipeline) which mentions that a shared Managed Identity (MI) was created and assigned to MicroBuild customers for use for their APIScan runs. Since the corresponding pool is in devdiv, we cannot access it from dnceng.

Thus, if Arcade could create a similar MI and assign it to one of the pools (say, NetCore1ESPool-Internal) that we can use for our pipeline, then it should resolve the issue.

cc: @merriemcgaw, @KlausLoeffelmann 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by riarenas** [comment]
We have some very very recent guidance that pool-wide managed identities should not be used, so we should:

* Get clarity on whether that is true
* If that is true, figure out a better path forward for dnceng customers.

**Comment by KlausLoeffelmann** [comment]
@riarenas: If there are additional tasks on our end, we can do, to expedite this, please don't hesitate to contact me, so I can ramp-up in time and then take care of getting those things into gear!

**Comment by merriemcgaw** [comment]
@MiYanni was interested in the outcome of this as well. I think the sdk team could benefit from it as well.

**Comment by missymessa** [comment]
The only place that we're aware of that runs APIScan is in the Release pipeline. @tkapin do you have any insight on this? We also have no plans to expand APIScan support at this time.

**Comment by missymessa** [comment]
Additionally, here is a link to reach out to the APIScan team directly: https://aka.ms/apiscan. Let us know if there's anything we can do to help.

**Comment by merriemcgaw** [comment]
@missymessa we've reached out to the APIScan team already. This is the recommended approach, and how VSEng is supporting APIScan for the rest of DevDiv. The pipeline we're hoping to enable is one that allows us to ship update WinForms Designer Extensibility SDKs to our 3rd party control vendors. We've talked with the APIScan owners and they have directed us this way. @tkapin I'd be very interested to know how your team is using APIScan in your release pipeline. Perhaps there is something we can leverage there.

To the best of our knowledge, the only other option would be to migrate the entire pipeline to VSEng, which would be a huge lift for my team - and VSEng is still using a pool wise managed identity.

**Comment by KlausLoeffelmann** [comment]
We have reached out several times. 
@missymessa, it's primarily about the Managed Identities. 

See Ricardo's comment above:
https://github.com/dotnet/dnceng/issues/2965#issuecomment-2137910674

**Comment by arkalyanms** [comment]
Roslyn, Razor, Compilers all have the same ask. cc: @jaredpar and @phil-allen-msft

**Comment by Shyam-Gupta** [comment]
@riarenas Any update? WinForms APIScan pipeline is currently blocked on this issue, and probably similar is the case for other teams.

**Comment by riarenas** [comment]
No update. @markwilkie FYI.

**Comment by merriemcgaw** [comment]
@dougbu @mmitche - Has there been any progress in determining what teams are supposed to do here? I feel like quite a few teams are waiting on some form of guidance.

**Comment by dougbu** [comment]
I responded in email thread on this subject.

**Comment by mmitche** [comment]
@merriemcgaw We know that APIScan is still working on federated credential support. That's the main blocker right now. It's **possible** that federated creds + azure CLI + task may work in the meantime, but I'm not sure. I can try out the workaround if I can get someone on the winforms-designer team to work with me.

**Comment by missymessa** [comment]
@mmitche it sounds like guidance was written and the internal thread was wrapped up? Cool to close this?

**Comment by merriemcgaw** [comment]
Cool from our end.

**Comment by missymessa** [comment]
Guidance for future reference: https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/25351/APIScan-step-by-step-guide-to-setting-up-a-Pipeline

**Comment by Shyam-Gupta** [comment]
@missymessa The guidance you shared uses a Managed Identity assigned to a shared pool. Dnceng does not prescribes it and hence it cannot be used. @mmitche suggested me to use Federated Credentials and it is working for us. I have documented it [here](https://microsoft.sharepoint.com/:w:/r/teams/MerriesWinFormsandSetup/_layouts/15/Doc.aspx?sourcedoc=%7BEBA4E3E9-43F8-4171-8396-C5328C965BA6%7D&file=APIScanAuthentication.docx&nav=eyJjIjoxMzU1MjgzNDAyfQ&action=default&mobileredirect=true&share=IQHp46Tr-ENxQYOWxTKMllumAX5r_47eShmn-F58bnFN4WY).
