### ISSUE TITLE
Offline PerfTiger119 from the Windows.11.Amd64.Tiger.Perf queue

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#2977]
Per request from @LoopedBard3, we need to take this machine down for investigations. Once completed we should re-enable the machine.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by riarenas** [comment]
Machine has been disabled

**Comment by epananth** [comment]
done
