### ISSUE TITLE
System.OverflowException at Octokit.PocoJsonSerializerStrategy.DeserializeObject exceptions in dotnet-status

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#3015]
Starting on 6/4, we are seeing a lot of exceptions in the logs.

[App insights query](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fmonitoring%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2FDotNetEng-Status-Prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAAzXNQQ7CIBBG4b2nmPQAnEIXusGEEwD9tSh0yMzEivHwuun2JV8e3hndCq96%252BNK2QEBdOFW080xLVJrCUENz%252FgW5Vd5OO6Bo5LPxs5i7cuaL8hogJdbygQSTaLgPd4Tu0acHsk3%252FEcsMoTTISoNabJ2i5h8wIcCzjAAAAA%253D%253D/timespan/P1D/limit/1000)

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by missymessa** [comment]
See discussion here: https://teams.microsoft.com/l/message/19:276707cdcf5d431caaa8792b29bd832d@thread.skype/1717778544799?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=147df318-61de-4f04-8f7b-ecd328c256bb&parentMessageId=1717778544799&teamName=.NET%20Eng%20Services&channelName=FR%20Internal&createdTime=1717778544799

**Comment by AlitzelMendez** [comment]
there is a version with this fixed.
The fixed for this are rolling out tomorrow: https://github.com/dotnet/dnceng/pull/3043

**Comment by AlitzelMendez** [comment]
this was already fixed. closing
