### ISSUE TITLE
Option 'disable-interactive-auth' is unknown.

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/dnceng#3071]
### Build

https://dev.azure.com/dnceng/internal/_build/results?buildId=2472121&view=logs&j=5c24930e-0ae1-546c-7353-8c3b261a7651&t=90d1b216-f511-5956-2766-23f92c36b673&l=120

```
Option 'disable-interactive-auth' is unknown.
...
##[error]PowerShell exited with code '1'.
```

### Known issue core information

Fill out the known issue JSON section by following the [step by step documentation on how to create a known issue](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step)

```json
 {
    "ErrorMessage" : "Option 'disable-interactive-auth' is unknown.",
    "BuildRetry": false,
    "ErrorPattern": "",
    "ExcludeConsoleLog": false
 }
 ```

 @dotnet/dnceng

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng/internal/_build/results?buildId=2472121
**Error message validated:** `[Option 'disable-interactive-auth' is unknown.`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 6/12/2024 8:00:28 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[2476227](https://dev.azure.com/dnceng/internal/_build/results?buildId=2476227)|dotnet-diagnostics|Publish Using Darc|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2476227/logs/2021)||
|[2476096](https://dev.azure.com/dnceng/internal/_build/results?buildId=2476096)|dotnet-efcore|Publish Using Darc|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2476096/logs/324)||
|[2475182](https://dev.azure.com/dnceng/internal/_build/results?buildId=2475182)|dotnet-efcore|Publish Using Darc|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2475182/logs/380)||
|[2475649](https://dev.azure.com/dnceng/internal/_build/results?buildId=2475649)|dotnet-binaryen|Publish Using Darc|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2475649/logs/483)||
|[2474521](https://dev.azure.com/dnceng/internal/_build/results?buildId=2474521)|dotnet-diagnostics|Publish Using Darc|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2474521/logs/1735)||
|[2473626](https://dev.azure.com/dnceng/internal/_build/results?buildId=2473626)|dotnet-diagnostics|Publish Using Darc|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2473626/logs/1806)||
|[2473156](https://dev.azure.com/dnceng/internal/_build/results?buildId=2473156)|dotnet-winforms|Publish Using Darc|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2473156/logs/343)||
|[2472727](https://dev.azure.com/dnceng/internal/_build/results?buildId=2472727)|dotnet-cecil|Publish Using Darc|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2472727/logs/269)||
|[2472716](https://dev.azure.com/dnceng/internal/_build/results?buildId=2472716)|dotnet-extensions|Publish Using Darc|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2472716/logs/359)||
|[2472647](https://dev.azure.com/dnceng/internal/_build/results?buildId=2472647)|dotnet-wcf|Publish Using Darc|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2472647/logs/331)||
|[2472577](https://dev.azure.com/dnceng/internal/_build/results?buildId=2472577)|dotnet-diagnostics|Publish Using Darc|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2472577/logs/1735)||
|[2472121](https://dev.azure.com/dnceng/internal/_build/results?buildId=2472121)|dotnet-runtime|Publish Using Darc|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2472121/logs/5011)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|12|12|

**Comment by premun** [comment]
@jeffschwMSFT please update Arcade and this will get fixed.

**Comment by premun** [comment]
I can see that runtime's arcade has already been updated and this won't flag any more builds now.

**Comment by premun** [comment]
All repos here got their arcade updates and will no longer fail. All have a successful publishing since then. Closing.
