### ISSUE TITLE
Update helix-admin list to account for team member changes

### ISSUE THREAD

**Issue by haruna99** [dotnet/dnceng#3073]
### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Added github alias

**Comment by missymessa** [comment]
@haruna99 did you do this work?

**Comment by haruna99** [comment]
Yes, I added my alias

**Comment by missymessa** [comment]
@haruna99 you can close this issue if it's done :)
