### ISSUE TITLE
❌Unable to find directory for jdk 11.0.22; please make sure the tool is installed on this image.

### ISSUE THREAD

**Issue by dtivel** [dotnet/dnceng#3077]
### Build

https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=705986

### Build leg reported

VMR Vertical Build / Windows_x64 / Build

### Pull Request

https://github.com/dotnet/sdk/pull/41565

### Known issue core information

Fill out the known issue JSON section by following the [step by step documentation on how to create a known issue](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step)

```json
 {
    "ErrorMessage" : "Unable to find directory for jdk 11.0.22; please make sure the tool is installed on this image.",
    "BuildRetry": false,
    "ErrorPattern": "",
    "ExcludeConsoleLog": false
 }
 ```

 @dotnet/dnceng

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=705986
**Error message validated:** `[Unable to find directory for jdk 11.0.22; please make sure the tool is installed on this image.`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 6/13/2024 6:32:39 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[705436](https://dev.azure.com/dnceng-public/public/_build/results?buildId=705436)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/705436/logs/283)|dotnet/sdk#41142|
|[705986](https://dev.azure.com/dnceng-public/public/_build/results?buildId=705986)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/705986/logs/277)|dotnet/sdk#41565|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|2|2|

**Comment by garath** [comment]
The version of the JDK installed on dnceng-managed images was updated to 11.0.23 during the previous rollout on June 12. I believe you'll need to update the path to reflect the version change.

**Comment by dtivel** [comment]
@garath, by "update the path" do you mean rebase on latest main?

**Comment by garath** [comment]
Unfortunately I'm not especially familiar its effects in this build. I see this is related to VMR, so the context of [this First Responder conversation](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1718226779956?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1718226779956&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1718226779956) may help? If not, let us know.
