### ISSUE TITLE
Add a summary table into secret manager output

### ISSUE THREAD

**Issue by premun** [dotnet/dnceng#309]
### Problem

The current output of secret manager is difficult to sift through and hard to look for a potential problem. The logs look like this:

![image](https://github.com/dotnet/dnceng/assets/7013027/f9abf4cd-a7ba-4d71-8feb-bdb8a3a01910)

### Goal

Make it easier to fish for names of secrets that need an action or have problems.
The new proposed summary would be appended at the end and look like this:

![image](https://github.com/dotnet/dnceng/assets/7013027/118c1844-9405-48ae-9a8d-eb990118af20)

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Added a summary table to secret manager output for easier reading

**Comment by premun** [comment]
The change is minimal and I have it ready in a branch in case we decide to go for this.

**Comment by MilenaHristova** [comment]
that's great. It's hard for me to understand from the logs when a secret is rotated because it's reference was rotated, I see that you added this information in the summary as well

**Comment by andriipatsula** [comment]
The output is more readable and informative. Great proposal!
