### ISSUE TITLE
Add macOS 15 Beta to Scouting Queue

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#3090]
With the release of macOS beta from Apple, we need to add a scouting queue for ARM based systems (similar to osx.amd64.scouting.open)

In addition to macOS 15 beta, we also need to install xcode 16. 

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Added OSX.15.Arm64.Scouting queue

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/40837

**Comment by riarenas** [comment]
This queue is now deployed in Production and *should* be ready to have machines added to it. Let me know if there is any followup work needed here.
