### ISSUE TITLE
Install JDK 11 on Linux and MacOS images

### ISSUE THREAD

**Issue by sebastienros** [dotnet/dnceng#3093]
The Windows images have JDK 11.0.23 installed but the Linux and MacOS ones have JDK 8.
As I am trying to get the aspnet repository to build successfully when users have a more recent version locally, we need to bump Gradle version in our script, but the new version then doesn't support JDK 8 anymore.

For this reason, and also in order to have some consistency (to reduce potential custom steps for each OS target) I'd like to have JDK 11 also available on Linux and MacOS images. NB: we should check if the distribution we use for JDK 8 is still supported (released in 2018)).

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by sebastienros** [comment]
Has there been any changes on the available versions of the JDK?

**Comment by BrennanConroy** [comment]
Can we install a more recent version of the JDK? 11 is very old and while it is still under extended support, we really should be using a more modern version like 21 (LTS).

**Comment by dougbu** [comment]
I feel this is now two separate requests:
1. provide consistent JDK versions on Windows and non-Windows machines we maintain
2. add another more recent JDK version (if they can be installed side-by-side) or bump the single version up

@BrennanConroy could you move (2) into a new issue and provide a bit more background e.g. EOL dates and your preferred timeline❓

**Comment by sebastienros** [comment]
I am fine if 
- both machines have 11
- both machines have 21

If it's less work to go to 21 first then let's do that.

**Comment by dougbu** [comment]
OpenJDK 8 remains in support but OpenJDK 11 is EOL. Our exact changes and the final selection of JDK versions is visible in the issue we used to track the work done: #4554.

If I remember correctly, this also moved to the latest OpenJDK 8 release on macOS machines. Ubuntu VMs were already getting the latest Ubuntu package releases for Linux as we update the images. And, we didn't touch the Windows machines with Oracle 8 on them.

**Comment by dougbu** [comment]
closing this in favour of #4554
