### ISSUE TITLE
Install some playwright dependencies on Ubuntu.2204.Amd64* helix agents

### ISSUE THREAD

**Issue by radical** [dotnet/dnceng#3122]
Could  the `libgbm1`, and `libxkbcommon0` packages be installed for the `Ubuntu.2204.Amd64`, and `Ubuntu.2204.Amd64.Open` helix queues? These are needed for running Playwright on the linux helix agents. And it would allow us to remove 

https://github.com/dotnet/aspire/blob/faf26a8700c79ec435c2348d566caf4c1a4ebc13/tests/helix/send-to-helix-inner.proj#L77-L78

cc @joperezr 

### Release Note Category

- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

### Release Note Description

Add `libgbm1`, and `libxkbcommon0` packages to `ubuntu.2204.amd64[.open]` queues. This eases Playwright setup on those agents and avoids some system-wide changes during workitem execution.

**Comment by dougbu** [comment]
confirmed this rolled out, was reverted, but is now present in the two requested queues. see entries in https://helix.dot.net and let us know if the installed packages disappear

**Comment by radical** [comment]
> confirmed this rolled out, was reverted, but is now present in the two requested queues. see entries in [helix.dot.net](https://helix.dot.net) and let us know if the installed packages disappear

Thank you!!

**Comment by radical** [comment]
> confirmed this rolled out, was reverted, but is now present in the two requested queues. see entries in [helix.dot.net](https://helix.dot.net) and let us know if the installed packages disappear

The packages do show up on that page. When should I expect the new VMs for these updated images to show up? I tried to enable the tests but they still fail - https://dev.azure.com/dnceng-public/public/_build/results?buildId=754402&view=ms.vss-test-web.build-test-results-tab&runId=19118936&resultId=100001&paneView=debug .

**Comment by dougbu** [comment]
Reopening to see what's going on. Might be a `$PATH` issue for example&hellip;

**Comment by dougbu** [comment]
@radical I lost track of this issue. what is your current status❓ if work remains, what is its priority and urgency from your perspective❓

**Comment by radical** [comment]
We have our Playwright based coverage on github actions now, so this can be closed.
