### ISSUE TITLE
Install some dependencies for `dotnet/runtime` performance jobs on the linux helix agents

### ISSUE THREAD

**Issue by radical** [dotnet/dnceng#3124]
`dotnet/runtime` currently installs some packages on helix agents for performance jobs - https://github.com/dotnet/runtime/blob/4a99b64c4d702e4d71daa326e5174170b30f942a/eng/pipelines/coreclr/templates/run-performance-job.yml#L90-L108

Could some of these be installed on the helix agents themselves, so we can avoid installing them on every helix job?

cc @ericstj @dougbu 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by radical** [comment]
cc @LoopedBard3

**Comment by dougbu** [comment]
1. Are these commands ever executed w/in a Docker container❔
2. Why is that YAML removing and re-installing `nodejs`❔

I'm not particularly concerned about the Python installations b/c that's done within a `venv` private to the tests and should go quickly. Not sure about the `npm` commands but I suspect we don't install anything except `nodejs` itself.

**Comment by radical** [comment]
> 1. Are these commands ever executed w/in a Docker container❔

These are executed on the helix agent, which is running in a docker container IIUC.

> 2. Why is that YAML removing and re-installing `nodejs`❔

That is so it can install a specific newer version of nodejs from nodesource.com . https://github.com/dotnet/runtime/commit/06271c6531b6

> I'm not particularly concerned about the Python installations b/c that's done within a `venv` private to the tests and should go quickly. Not sure about the `npm` commands but I suspect we don't install anything except `nodejs` itself.

`jsvu`

cc @lewing @akoeplinger

**Comment by dougbu** [comment]
> These are executed on the helix agent, which is running in a docker container IIUC.

@radical only some Helix work items (those submitted to target queues using the `({Optional Queue Alias}){Helix Queue Id}@{DockerTag}` syntax) use Docker. Those submitted to bare queue names from https://helix.dot.net/ run on the VM directly. Which applies for the YAML you linked❔

> That is so it can install a specific newer version of nodejs from nodesource.com.

Not a great idea b/c smaller repositories can take requests from Microsoft's few external IP addresses as a DOS attempt. What's the version your team needs❔ I'm hoping it's available from the OS vendors now. If it's a compatible upgrade, we should be able to install it even if not.

**Comment by radical** [comment]
> > These are executed on the helix agent, which is running in a docker container IIUC.
> 
> @radical only some Helix work items (those submitted to target queues using the `({Optional Queue Alias}){Helix Queue Id}@{DockerTag}` syntax) use Docker. Those submitted to bare queue names from [helix.dot.net](https://helix.dot.net/) run on the VM directly. Which applies for the YAML you linked❔

For this runtime/wasm case here a docker image is being used:
https://github.com/dotnet/runtime/blob/4a99b64c4d702e4d71daa326e5174170b30f942a/eng/pipelines/libraries/helix-queues-setup.yml#L170-L173

I didn't know this difference in the helix queues! Good to know!
Do IIUC that you are concerned with installing packages when using the bare queue, thus the VM, and not the docker case?

> 
> > That is so it can install a specific newer version of nodejs from nodesource.com.
> 
> Not a great idea b/c smaller repositories can take requests from Microsoft's few external IP addresses as a DOS attempt. What's the version your team needs❔ I'm hoping it's available from the OS vendors now. If it's a compatible upgrade, we should be able to install it even if not.

Based on the yml `18.x` seems to be the version being installed. But I'm no longer on the team, and not updated with the changes made this year. @lewing @akoeplinger @ilonatommy could one of you take this up?

**Comment by dougbu** [comment]
Ah, if the other section also runs only in Docker containers, please close this issue or ask me to. The content of https://github.com/dotnet/dotnet-buildtools-prereqs-docker is primarily self-service i.e., it's up to you and other users to make most Dockerfile changes.

**Comment by radical** [comment]
@LoopedBard3 can you confirm that all the setup bits for helix in https://github.com/dotnet/runtime/blob/4a99b64c4d702e4d71daa326e5174170b30f942a/eng/pipelines/coreclr/templates/run-performance-job.yml#L90-L108 will be running on a queue using the docker container? If so, then we can close this as Doug said.

**Comment by LoopedBard3** [comment]
@radical, for this section of setup commands, these are run on bare metal agents, not docker images. Ultimately, these should not actually be reinstalling every run, instead they are there to install on the first run for new machines and when the version is updated. The only exception to this would be lttng-modules-dkms which may be reinstalled in the regular performance runs but that we need uninstalled for others. Hopefully, this answers the question above. Please mention me if you have any other questions.

**Comment by dougbu** [comment]
this _may_ be straightforward but please list the specific packages requested and the queues where they're needed

**Comment by dougbu** [comment]
put another way, we'd rather not search your YAML then guess 😁

**Comment by LoopedBard3** [comment]
@dougbu, just to clarify, is preinstalling these dependencies something that would be done for both the VM images as well as the baremetal machines we test on? Mostly looking for clarity on what the images are and what style of run they are used in. Thanks!

**Comment by dougbu** [comment]
> @dougbu, just to clarify, is preinstalling these dependencies something that would be done for both the VM images as well as the baremetal machines we test on? Mostly looking for clarity on what the images are and what style of run they are used in. Thanks!

changing on-prem machines is possible but an additional step beyond just doing the VMs. the on-prem update process is mostly manual but we might be able to automate some parts.

again, please provide the exact details of this request so we can understand the full scope

**Comment by LoopedBard3** [comment]
After talking it over with @DrewScoggins, we are not going to go forward with this flow change due to the machines that run this job being majority baremetal, most packages should be just verified that they are installed (we are not passing --force-reinstall), and the current flow allowing us to push updates automatically when we need them. @dougbu, I am good with closing this issue (I don't have permission). Let me know if you have any other questions, thanks!

**Comment by dougbu** [comment]
thanks @radical, @LoopedBard3, and @DrewScoggins
