### ISSUE TITLE
 Build failure: Static graph-based restore failed with exit code .* but did not log an error.

### ISSUE THREAD

**Issue by lewing** [dotnet/dnceng#3139]
### Build

https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=709057

### Build leg reported

Build / windows-arm64 Release NativeAOT / Build product

### Pull Request

https://github.com/dotnet/runtime/pull/103519

### Known issue core information

Fill out the known issue JSON section by following the [step by step documentation on how to create a known issue](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step)

```json
 {
    "ErrorMessage" : "",
    "BuildRetry": false,
    "ErrorPattern": "Static graph-based restore failed with exit code .* but did not log an error.",
    "ExcludeConsoleLog": false
 }
 ```

 @dotnet/dnceng

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=709057
**Error message validated:** `[Static graph-based restore failed with exit code .* but did not log an error.`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 6/20/2024 11:56:24 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[773118](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773118)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/773118/logs/90)|dotnet/runtime#106139|
|[772983](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772983)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/772983/logs/149)|dotnet/runtime#105737|
|[772220](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772220)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/772220/logs/118)|dotnet/runtime#105288|
|[771840](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771840)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/771840/logs/104)|dotnet/runtime#106225|
|[771691](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771691)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/771691/logs/104)|dotnet/runtime#106217|
|[771062](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771062)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/771062/logs/128)|dotnet/runtime#106083|
|[770060](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770060)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/770060/logs/100)|dotnet/runtime#106155|
|[769979](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769979)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/769979/logs/347)|dotnet/runtime#106014|
|[768998](https://dev.azure.com/dnceng-public/public/_build/results?buildId=768998)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/768998/logs/228)||
|[768489](https://dev.azure.com/dnceng-public/public/_build/results?buildId=768489)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/768489/logs/255)|dotnet/runtime#106072|
|[2509726](https://dev.azure.com/dnceng/internal/_build/results?buildId=2509726)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2509726/logs/477)||
|[2509225](https://dev.azure.com/dnceng/internal/_build/results?buildId=2509225)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2509225/logs/458)||
|[766348](https://dev.azure.com/dnceng-public/public/_build/results?buildId=766348)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/766348/logs/109)|dotnet/runtime#105958|
|[764315](https://dev.azure.com/dnceng-public/public/_build/results?buildId=764315)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/764315/logs/109)|dotnet/runtime#105887|
|[2507378](https://dev.azure.com/dnceng/internal/_build/results?buildId=2507378)|dotnet-dotnet|Build|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2507378/logs/1233)||
|[2506996](https://dev.azure.com/dnceng/internal/_build/results?buildId=2506996)|dotnet-runtime|Build product (linux_arm64)|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2506996/logs/1305)||
|[762890](https://dev.azure.com/dnceng-public/public/_build/results?buildId=762890)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/762890/logs/136)|dotnet/runtime#105781|
|[2506608](https://dev.azure.com/dnceng/internal/_build/results?buildId=2506608)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2506608/logs/461)||
|[761775](https://dev.azure.com/dnceng-public/public/_build/results?buildId=761775)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/761775/logs/228)|dotnet/runtime#105734|
|[2506124](https://dev.azure.com/dnceng/internal/_build/results?buildId=2506124)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2506124/logs/502)||
|[760176](https://dev.azure.com/dnceng-public/public/_build/results?buildId=760176)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/760176/logs/124)|dotnet/runtime#105689|
|[760106](https://dev.azure.com/dnceng-public/public/_build/results?buildId=760106)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/760106/logs/212)|dotnet/runtime#104849|
|[760081](https://dev.azure.com/dnceng-public/public/_build/results?buildId=760081)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/760081/logs/109)|dotnet/runtime#105676|
|[759847](https://dev.azure.com/dnceng-public/public/_build/results?buildId=759847)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/759847/logs/109)|dotnet/runtime#105652|
|[759311](https://dev.azure.com/dnceng-public/public/_build/results?buildId=759311)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/759311/logs/109)|dotnet/runtime#105633|
|[758553](https://dev.azure.com/dnceng-public/public/_build/results?buildId=758553)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/758553/logs/134)|dotnet/runtime#105612|
|[757500](https://dev.azure.com/dnceng-public/public/_build/results?buildId=757500)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/757500/logs/107)|dotnet/runtime#105584|
|[2503522](https://dev.azure.com/dnceng/internal/_build/results?buildId=2503522)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2503522/logs/458)||
|[757371](https://dev.azure.com/dnceng-public/public/_build/results?buildId=757371)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/757371/logs/128)|dotnet/runtime#105581|
|[756948](https://dev.azure.com/dnceng-public/public/_build/results?buildId=756948)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/756948/logs/205)|dotnet/runtime#105341|
|[756906](https://dev.azure.com/dnceng-public/public/_build/results?buildId=756906)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/756906/logs/119)|dotnet/runtime#104307|
|[756867](https://dev.azure.com/dnceng-public/public/_build/results?buildId=756867)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/756867/logs/126)|dotnet/runtime#105110|
|[756284](https://dev.azure.com/dnceng-public/public/_build/results?buildId=756284)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/756284/logs/248)|dotnet/runtime#104502|
|[755881](https://dev.azure.com/dnceng-public/public/_build/results?buildId=755881)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/755881/logs/216)|dotnet/runtime#105403|
|[755747](https://dev.azure.com/dnceng-public/public/_build/results?buildId=755747)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/755747/logs/173)||
|[755306](https://dev.azure.com/dnceng-public/public/_build/results?buildId=755306)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/755306/logs/128)|dotnet/runtime#105424|
|[755296](https://dev.azure.com/dnceng-public/public/_build/results?buildId=755296)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/755296/logs/138)|dotnet/runtime#104562|
|[2502396](https://dev.azure.com/dnceng/internal/_build/results?buildId=2502396)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2502396/logs/465)||
|[755046](https://dev.azure.com/dnceng-public/public/_build/results?buildId=755046)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/755046/logs/358)|dotnet/runtime#105308|
|[755035](https://dev.azure.com/dnceng-public/public/_build/results?buildId=755035)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/755035/logs/275)|dotnet/runtime#105394|
|[2501780](https://dev.azure.com/dnceng/internal/_build/results?buildId=2501780)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2501780/logs/464)||
|[753811](https://dev.azure.com/dnceng-public/public/_build/results?buildId=753811)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/753811/logs/378)|dotnet/runtime#105410|
|[753487](https://dev.azure.com/dnceng-public/public/_build/results?buildId=753487)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/753487/logs/204)|dotnet/runtime#105396|
|[753279](https://dev.azure.com/dnceng-public/public/_build/results?buildId=753279)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/753279/logs/242)|dotnet/runtime#105327|
|[2501307](https://dev.azure.com/dnceng/internal/_build/results?buildId=2501307)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2501307/logs/621)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|45|

**Comment by lewing** [comment]
This is the same issue as https://github.com/dotnet/runtime/issues/103526 but moved to infrastructure/dnceng

**Comment by agocke** [comment]
This appears fixed but I don’t have contributor permissions on this repo. @markwilkie  can you open up issue permissions to the whole org?
