### ISSUE TITLE
*Some* helix agents failing with `Bad return status for module build on kernel: 6.5.0-1022-azure (x86_64)` when installing some packages with `apt-get`

### ISSUE THREAD

**Issue by radical** [dotnet/dnceng#3140]
Some helix agents are failing when running `sudo apt-get -o DPkg::Lock::Timeout=120 install -y libgbm1 libxkbcommon0` with:
```
Loading new lttng-modules-2.13.8 DKMS files...
Building for 6.5.0-1022-azure
Building initial module for 6.5.0-1022-azure
Error! Bad return status for module build on kernel: 6.5.0-1022-azure (x86_64)
Consult /var/lib/dkms/lttng-modules/2.13.8/build/make.log for more information.
dpkg: error processing package lttng-modules-dkms (--configure):
 installed lttng-modules-dkms package post-installation script subprocess returned error exit status 10
```

Only *some* helix agents seem to fail. For example - [failure case](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspire-refs-heads-main-e5c84ada1bb6438e96/Aspire.Workload.Tests.EmptyTemplateRunTests/1/console.678fec55.log?helixlogtype=result) from a [failing build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715057&view=results). And a [working case](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspire-refs-pull-4604-merge-fe123d02d111481daf/Aspire.Workload.Tests.Xunit_PerTestFrameworkTemplatesTests/1/console.337dca87.log?helixlogtype=result) from a [working build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=714989&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=dad169e2-35ab-5ac6-55b3-7eed7d423255).

This has been happening pretty randomly, but frequently enough to be blocking `dotnet/aspire` PRs. [This helix run](https://helix.dot.net/api/jobs/fe123d02-d111-481d-afae-0781538ea6e9/workitems?api-version=2019-06-17) has all passing jobs.

I haven't been able to connect to a helix-repro-vm to reproduce the issue. Does it sound like an issue with some particular running VMs, or the image itself? The suggested alternative was https://github.com/dotnet/dnceng/issues/3122 - which would mean that we can drop this `apt-get` invocation.

cc @joperezr @eerhardt @dougbu 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by dougbu** [comment]
This is an issue in your repository's Helix commands and you should have the information to debug that problem @radical. Please move this out of dnceng.
