### ISSUE TITLE
dotnet-mirror pipeline should indicate repo name in title

### ISSUE THREAD

**Issue by mthalman** [dotnet/dnceng#3147]
The [dotnet-mirror pipeline](https://dev.azure.com/dnceng/internal/_build?definitionId=1387&_a=summary) doesn't include the name of the repo being synced in the title of each run. This used to be done with the old code-mirror pipeline. It made it very easy to see when the repo you're interested in had been mirrored and whether it was successful. It would be very helpful to bring back this info in the run name.

**Comment by mmitche** [comment]
@mthalman The mirror pipeline is updating (if necessary) the entire set of mappings in each run, rather than a single repo.
