### ISSUE TITLE
dotneteng-status is down

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#3192]
After the deployment in https://dev.azure.com/dnceng/internal/_build/results?buildId=2482552&view=results the website is reporting that the app service is offline. 

https://dotneteng-status.azurewebsites.net/

This also manifested in not being able to send the telemetry start and end calls for other deployments, such as in https://dev.azure.com/dnceng/internal/_build/results?buildId=2483178&view=logs&j=5104def2-a6ce-550c-4b03-d0689fd42ba0&t=17d947f5-6591-5b95-ab2c-928a4984c9cc

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by dougbu** [comment]
Site is back up after switching to the non-prod deployment slot. Done.
