### ISSUE TITLE
Bump helix-machines package versions

### ISSUE THREAD

**Issue by dougbu** [dotnet/dnceng#3317]
This repo is rather far behind in its package versions. Time fo get caught up&hellip;

See also
- [work item 6613](https://dev.azure.com/dnceng/internal/_workitems/edit/6613)
- [work item 6632](https://dev.azure.com/dnceng/internal/_workitems/edit/6632)
- [work item 6638](https://dev.azure.com/dnceng/internal/_workitems/edit/6638)

### Release Note Category

- [ ] Feature changes/additions
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements

### Release Note Description

Bump most package versions in our dotnet-helix-machines repository.

**Comment by ilyas1974** [comment]
As we already have someone working on the package versions listed in this issue, I am going to close this issue.
