### ISSUE TITLE
dotneteng-status-staging issues

### ISSUE THREAD

**Issue by chcosta** [dotnet/dnceng#3326]
dotneteng-status-staging is acting weird and causing multiple issues across various repositories.

This issue is being used to track the various failures.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by riarenas** [comment]
I took a quick look at the logs, and I think we're having some more Octokit related issues here. 

[This App Insights query](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fcab65fc3-d077-467d-931f-3932eabf36d3%2FresourceGroups%2Fmonitoring%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2FDotNetEng-Status-Staging/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAAzXOvQrCMBSG4d2rOLgKGZ1EKCjWoV2qOJb8fJhgk5ScU23Bi1cQt3d54MVsMUrIiVdvenkU0FiyGRDPjrxmWncLC6JqAnNI9wbiszv%252BFWmhQ5YWojrRMrG6wahTkHoyV0a55AdSrZMbUDa7X1STeCQJVgsqXpLdu77fqiY%252F0WKW9XckF4dCZiEJESw6jqTZfgB1bI61rAAAAA%253D%253D/timespan/2024-07-01T16%3A19%3A59.000Z%2F2024-07-09T17%3A19%3A59.478Z/limit/1000)

Shows that starting on 7/3 we started seeing some MissingMethod exceptions. This makes me think we might have missed a breaking change with the latest bump.

> Method not found: 'Int32 Octokit.Account.get_Id()'.

**Comment by riarenas** [comment]
The code that is failing comes from https://github.com/dotnet/dnceng-shared/tree/main/src/Microsoft.DotNet.GitHub.Authentication. 

I see that dnceng-shared is still using Octokit 10. I think that is probably related and we need to bump the library in that repo.

**Comment by epananth** [comment]
this has been fixed, closing this
