### ISSUE TITLE
New Helix Queue for ARM64 Cedar Crest hardware

### ISSUE THREAD

**Issue by JpratherMS** [dotnet/dnceng#3343]
We have a requirement from Julie Lee to get this new hardware into Helix. I believe we will need a new queue for this and some testing to make sure the hardware will work. I think its likely we will be using a specific version of Server 2025.

### Release Note Category
- [X] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Added new test queues for ARM64 Cedar Crest hardware

**Comment by ilyas1974** [comment]
After talking with @JpratherMS earlier today, it appears that we need 4 new queues to support this hardware

windows.2025
ubuntu.2204
windows.2025.perf
ubuntu.2204.perf

**Comment by ilyas1974** [comment]
All 4 queues need to be associated with the internal project.

**Comment by ilyas1974** [comment]
I believe the OS type needs to exist in os-definitions.json whenever we add a new OS to helix, but I'm not 100% sure.

**Comment by riarenas** [comment]
I believe that's the case as well. What would be the values for these systems?

**Comment by riarenas** [comment]
Are there any existing queues that these new queues should be based on?

**Comment by ilyas1974** [comment]
I would base these queues on the existing windows server 2022 queues as well as existing ubuntu 22.04 queues. As these are on-premises machines, the ubuntu.2204.amd64.viper.perf and windows.11.amd64.viper.perf may be the best place to start.

**Comment by riarenas** [comment]
The above queues should now be available in our staging environment if we want to validate some of the hardware there. The queues will be available in the production environment as part of our next deployment

**Comment by ilyas1974** [comment]
The linux install of helix was successful. 

The Windows install did produce an error
![Image](https://github.com/user-attachments/assets/10167b7a-ba2f-4429-991c-3e74a3ed8421)

cc: @v-parose

**Comment by riarenas** [comment]
Going to start taking a look today.

@ilyas1974  or @v-parose do either of you have the full set of instructions that are being followed? The requested blob seems to be in the storage account, so this 404 might be some authentication problems in disguise. Having access to the full output in a searchable (non image) form would also help find what might be going on.

**Comment by riarenas** [comment]
I have the information now and I'm taking a look at what might be going on here.

**Comment by riarenas** [comment]
I think I tracked this down to a bad sas that isn't being tracked by secret manager. I attempted to fix it manually to see if that helps. While we try to set up a machine again, I'll double check that this sas is properly managed going forward.

**Comment by riarenas** [comment]
@v-parose has confirmed that after the sas fixup he was able to provision a windows machine for this queue setup. https://github.com/dotnet/dnceng/issues/4163 covers the follow up to manage this sas properly.
