### ISSUE TITLE
Sentiment Tracking issues not applying correct labels

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#335]
Issues created via the Sentiment Tracker need to have the "Sentiment Feedback" label applied to them, and it's currently not. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by AlitzelMendez** [comment]
Hi @missymessa!

I want to take a quick look to this because a lot of times I filter the issues by this label, to know if we have reports on build analysis :D do you have any example in where this happened??

**Comment by AlitzelMendez** [comment]
yes! this seems to be working now! I will close the issue and if I see anything unusual I will reopen it :D
