### ISSUE TITLE
Add capacity to ubuntu.2204.amd64.open.rt queue

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#3457]
In doing some research, it appears that the Ubuntu.2204.amd64.open.rt is reaching the limit of instances that a single scale set can support. Helix has a mechanism in place to allow a single queue to be backed by multiple scale sets. We need to add another scale set to the Ubuntu queue used by runtime to help with the capacity issues we are seeing. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Add capacity to ubuntu.2204.amd64.open.rt queue

**Comment by riarenas** [comment]
I was looking at this today!

https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines?path=/src/DeployQueues/QueueManager.cs&version=GBmain&line=994&lineEnd=995&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents This loop makes sure that if we have a max count of over 600, we will split the deployment of the queue into multiple scale sets. I think it's just a matter of adding the `Max` attribute to whatever queue we want, and that should take care of splitting it.
 
We would have an `ubuntu.2204.amd64.open.rt-a-scaleset` and a `ubuntu.2204.amd64.open.rt-b-scaleset` that are both connected to the same service bus queue.

**Comment by chcosta** [comment]
Completed with https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/41156
