### ISSUE TITLE
Depreciate macOS 10.15 queues

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#348]
As 10.15 is no longer a support operating system, please deadletter the osx.1015.amd64.open and osx.1015.amd64 queues.

Two step process
- Please deadletter the queues as part of tomorrow's roll out so we can move the systems in these queues.  
- Update the code in helix-machines to deadletter this queues each time we roll out - moving forward. 

### Release Note Category
- [X] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

Deadletter osx.1015.amd64.open and osx.1015.amd64.open queues.

**Comment by AlitzelMendez** [comment]
@ilyas1974  qq, the variations are still supported or should also be deprectad, like OSX.1015.Amd64.AppleTV and OSX.1015.Amd64.Iphone.Perf?

also, are we redirecting the queues to another one like in other cases or are we completely getting rid of it?

**Comment by ilyas1974** [comment]
As osx.1015.amd64.appletv has no machines in it, I think it is safe to deprecate it. I'm still working with the perf team on getting machines moved out of osx.1015.amd64.iphone.perf? 

As this point, we're trying to get rid of them completely.

**Comment by AlitzelMendez** [comment]
ok, I will keep osx.1015.amd64.iphone.perf and remove appletv. Thanks Ilya :)

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/32550

**Comment by AlitzelMendez** [comment]
we are still waiting for people to stop using osx.1015.amd64.open :)

**Comment by AlitzelMendez** [comment]
took a quick look and roslyn is still using the queue, but they already have a pr out to stop using it: https://github.com/dotnet/roslyn/pull/69528

**Comment by AlitzelMendez** [comment]
New PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/33219

(created a clean pr because previous one was building images which was taking a long time)
