### ISSUE TITLE
Build Analysis allows to merge even though the build hasn't been queued yet

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/dnceng#3556]
See https://github.com/dotnet/runtime/pull/105247

![image](https://github.com/user-attachments/assets/bc1a70e1-0a8e-4d87-8ba0-fc2ac742fc1a)

The AzDO build didn't get queued correctly but Build Analysis allows to merge the PR in.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by missymessa** [comment]
Pretty sure this is a dupe of https://github.com/dotnet/dnceng/issues/3327. Viktor, please close if this is the case.

**Comment by ViktorHofer** [comment]
Closing as dupe of https://github.com/dotnet/dnceng/issues/3327
