### ISSUE TITLE
Fix usage of servicing build pools during main builds of dnceng and dnceng-shared

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#359]
Currently, the main builds of dotnet/dnceng has a lot of the build jobs running in the netcore1espool-svc-internal build pool. This is incorrect, as main builds should all use the non -svc build pools.

For instance, https://dev.azure.com/dnceng/internal/_build/results?buildId=2208056&view=logs&j=d17d50ef-afac-5d4b-95a6-3014ce5cf7a4&t=8c71b5e2-ae2b-4bba-8f0a-2deef5511cc5

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by riarenas** [comment]
FYI @missymessa @dkurepa

**Comment by riarenas** [comment]
at a glance it looks like all stages added by arcade templates are running in the wrong pool:

* Push to BAR
* SDL
* Package publishing

I would start by checking what's going on there. The Arcade templates have helper variables for choosing a pool, which this repo might be holding wrong.

**Comment by riarenas** [comment]
This is also happening for dnceng-shared: https://dev.azure.com/dnceng/internal/_build/results?buildId=2200676&view=logs&j=d17d50ef-afac-5d4b-95a6-3014ce5cf7a4&t=663a9090-1cd9-4395-97c0-61dba5b3f85d, so it's probably something silly to fix in some yaml in both repos

**Comment by dkurepa** [comment]
It looks like the arcade-services pipeline is also running these jobs in the same Svc pool. We haven't touched this part so it's probably been like this for a while now. https://dev.azure.com/dnceng/internal/_build/results?buildId=2220335&view=logs&j=7d9eef18-6720-5c1f-4d30-89d7b76728e9&t=24c68d4a-204a-42bd-9bbf-063f301b6f82

**Comment by riarenas** [comment]
That's another dnceng-ci link, but arcade-services is indeed broken as well and needs to be fixed: https://dev.azure.com/dnceng/internal/_build/results?buildId=2219860&view=logs&j=d17d50ef-afac-5d4b-95a6-3014ce5cf7a4&t=882fd266-2d96-4296-86e0-692de4b9bd02

**Comment by riarenas** [comment]
OOOH, I think this might be related to the fact that all of these 3 repos consume arcade from the 6.0 branch, which *is* a servicing branch. This might be a bug in Arcade instead?

**Comment by dkurepa** [comment]
That would make a lot of sense 😃 I had a brief look at the yaml, it doesn’t even let you chose a non svc pool. Would it make sense to add a flag for our scenario?
