### ISSUE TITLE
Increase service fabric staging partition size on vms

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/dnceng#3617]
Deploying service fabric in staging has become problematic because the machines continually run out of space, the machines has enough space but service fabric lives in a small partition which is only 80GB, we already have in place clean up processes but even with that with are using almost all the space in the machines

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by missymessa** [comment]
@chcosta is this something you're already working on (or fixed already)?

**Comment by chcosta** [comment]
This is fixed, we have migrated to a different VM sku with a larger temporary storage drive and I haven't seen any disk space issues recently.
