### ISSUE TITLE
Update to June 2024 XBox GDK on build images

### ISSUE THREAD

**Issue by steveisok** [dotnet/dnceng#3627]
I'm requesting the build images be updated to the October 2023 release of the XBox GDK. 

For reference, here was the last request we made https://github.com/dotnet/arcade/issues/12718

### Release Note Category
- [X] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Updated XBOX gdk in build images to version 240601

**Comment by riarenas** [comment]
PR: https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/41774

**Comment by riarenas** [comment]
This is rolled out
