### ISSUE TITLE
Timeouts connecting to HelixData sql DB

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#3686]
After the production rollout of 2024-07-31, we started seeing error traces related to SQL DB connection timeouts from the Data Migration service. 

[Go to Log Analytics and run query](https://ms.portal.azure.com/#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fdotnet-eng-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fdotnet-eng/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAAz2MsQoCMRAFe7%252FicR9wYGthZyEIFvoDa%252FLwApdL2F3PC%252FjxxsZqBgbGVQJt98F7ohLGlZq8XTpnHLH%252Fl0wzeRKTGIZbM2cez8sqc4rXShVPZTltgfUnB9xTZnk5uNWkjOPQR0UjFY8G79FcckWkhS%252B9TwwRgwAAAA%253D%253D/timespan/PT30M/limit/1000)

As part of this deployment we switched SQL libraries, and we changed the connection method to the DB, so we should investigate.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by epananth** [comment]
I checked the poolsize in the connection string from the key vault and I checked the pool size that is being set in code its 750. I did not print it, that is the only value that is being used, I will try to print it in staging to double check

**Comment by epananth** [comment]
I was doing a compare of connections open in staging vs prod 

Staging 
<img width="489" alt="image" src="https://github.com/user-attachments/assets/f148638d-c2cb-4721-a278-ecc5a1a5f006">
Prod 
<img width="747" alt="image" src="https://github.com/user-attachments/assets/469a5631-c3d6-4d39-a65d-4bd2a128bb35">

May be the connections are not closed. I am looking that now

**Comment by epananth** [comment]
I looked in datamigration if we are closing connections correctly, but looks like we do. So that is not the issue..

**Comment by epananth** [comment]
<img width="1421" alt="image" src="https://github.com/user-attachments/assets/8f23eae0-6bc6-4bf7-802a-1362996a0689">
max pool size is 750, not sure if we should increase it..

**Comment by epananth** [comment]
I see a lot of await calls 

<img width="1273" alt="image" src="https://github.com/user-attachments/assets/c9593df7-7e00-413a-af7c-a2108b088e37">
