### ISSUE TITLE
Secret manager stopped prepending `?` for the sas query string to be usable.

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#3710]
As of https://github.com/dotnet/dnceng/commit/a6eedeb00291a1abaf8f71dc34f17727ed913281, secret manager stopped prepending a `?` for the `azure-storage-account-sas-token` secret type. This is due to changing the Azure storage libraries. 

We accounted for this change for `azure-storage-container-sas-uri` secret types here: https://github.com/dotnet/dnceng/blob/0b33159c0672b49563b933f3550927209f41a7c9/src/SecretManager/Microsoft.DncEng.SecretManager/StorageUtils.cs#L150-L151

But we didn't for the storage account SAS.

I can see that older versions of secrets using this secret type in our vaults include the query string, but newer versions don't. This is causing issues when trying to fix https://github.com/dotnet/dnceng/issues/3622 

We should fix up secret manager, and force-cycle all secrets of this type.

### Release Note Category
- [ ] Feature changes/additions 
- [x] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Fixed secret manager's generation of azure account sas token secrets to account for differences in library behavior

**Comment by riarenas** [comment]
@garath FYI!

**Comment by garath** [comment]
Good catch, thanks for the fix!

**Comment by riarenas** [comment]
All repos should now be using a version of secret manager with this bug fixed, and they are set up for automatic updates of secret manager through maestro.
