### ISSUE TITLE
Failed to build installable wheels for some pyproject.toml based projects (cffi)

### ISSUE THREAD

**Issue by Unbelievable52** [dotnet/dnceng#3711]
### Build

When I install selenium, they announcement that, I don't know what are happening.
![Screenshot 2024-08-02 221901](https://github.com/user-attachments/assets/6aafd63b-527e-45e0-8f38-00a03e5488c9)

### Known issue core information

Fill out the known issue JSON section by following the [step by step documentation on how to create a known issue](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step)

```json
 {
    "ErrorMessage" : "",
    "BuildRetry": false,
    "ErrorPattern": "",
    "ExcludeConsoleLog": false
 }
 ```

 @dotnet/dnceng

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by missymessa** [comment]
@Unbelievable52 This repo is related to work with the .NET product. I'm not seeing how the error you provided is related to .NET.
