### ISSUE TITLE
Build break: Unable to build SLES 15 image

### ISSUE THREAD

**Issue by dougbu** [dotnet/dnceng#374]
SLES 15, unlike SLES 12, does not have the `python36-devel` package available. This is causing image builds to fail in the 'main' branch of [dotnet-helix-machines-ci](https://dev.azure.com/dnceng/internal/_build?definitionId=596). Example build: [#20230713.08](https://dnceng.visualstudio.com/internal/_build/results?buildId=2221595&view=results).

Example build console logging:
``` text
+ zypper -n install cmake which gcc libunwind-devel git-core libicu-devel libmsquic lttng-ust-devel libuuid-devel libopenssl-devel libcurl-devel krb5-devel libffi-devel python36 python36-devel zip
No provider of 'python36' found.
No provider of 'python36-devel' found. (86d883a4-bd91-c39c-c2ae-3059197b6c48)
##[warning]Attempt failed for sles.15.amd64, sles.15.amd64.svc, sles.15.amd64.open, sles.15.amd64.open.rt, sles.15.amd64.open.svc, Tracking ID 86d883a4-bd91-c39c-c2ae-3059197b6c48, Attempt ID 349bb3bc-6a59-4c68-915f-2064b6da2f7d: Full logs located in https://imagefactoryv2stpme.blob.core.windows.net/logfiles/cpwnpbox?sv=2021-08-06&se=2023-07-24T07%3A33%3A31Z&sr=b&sp=rw&sig=FcTbEuzHOlObACFJ92j0qajWmckjMpzT4tVR5mAWl4Q%3D
##[error]D:\a\_work\1\s\CreateCustomImage.dll(,): error : sles.15.amd64: Failed task 'MakeImage' for image 'sles.15.amd64, sles.15.amd64.svc, sles.15.amd64.open, sles.15.amd64.open.rt, sles.15.amd64.open.svc': System.Exception: Test results are missing from the blob storage. It's possible that the execution of validations failed catastrophically so that the report could not have been generated. Unfortunately, we don't have details available.
   at Microsoft.Internal.Helix.Machines.ValidateArtifacts.TestResultsStorage.DownloadTestResultIntoTempFile(Guid attemptId) in D:\a\_work\1\s\src\ValidateArtifacts\TestResultsStorage.cs:line 98
   at Microsoft.Internal.Helix.Machines.Types.ImageManifestArtifacts.PostProcessImageManifestTestDataAsync(String queueName, String buildName, Guid attemptId, String imageConnectionString) in D:\a\_work\1\s\src\Types\ImageManifestArtifacts.cs:line 43
   at Microsoft.Internal.Helix.Machines.CreateCustomImage.ImageFactoryImageProcessor.MakeImageAsync(String id, String name, IReadOnlyList`1 definitions) in D:\a\_work\1\s\src\CreateCustomImage\ImageFactoryImageProcessor.cs:line 305
   at Microsoft.Internal.Helix.Machines.CreateCustomImage.Program.TryProcessDefinitionsAsync(IReadOnlyList`1 targetDefinitions, IDefinitionStore generatedStore, IImageProcessor processor, List`1 forcedQueues, Boolean buildExistingImages, IContextLogger logger, String reportingConnectionString, Boolean isOfficialBuild) in D:\a\_work\1\s\src\CreateCustomImage\Program.cs:line 636
```

Example Image Factory console logging is similar but earlier messages are telling:
``` text
2023-07-17 07:37:03Z -> 'python36' not found in package names. Trying capabilities.
2023-07-17 07:37:03Z -> 'python36-devel' not found in package names. Trying capabilities.
```

Root cause is [!32479](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/32479) changing the `linux-add-package` packages for both SLES 12 and 15. I used `FORCE_QUEUE` for Mariner 2.0 instead of SLES 15 in that PR.

### Release Note Category

- [ ] Feature changes/additions 
- [x] Bug fixes
- [ ] Internal Infrastructure Improvements

### Release Note Description

Separate the OS package listing for SLES 12 and 15. SLES 12 continues to use `python36` and `python36-devel` because they're newer than the OS default versions. SLES 15 again installs the current `python3` and `python3-devel` packages.

**Comment by dougbu** [comment]
@garath thoughts on putting this into the `Helix Machines improvements` milestone❔

I am starting to lean toward using that mostly for broad changes like using the 1ES APIs instead of our Image Factory API and the Azure Resource Manager API. Keeping up on versions is primarily a vendor task, except when blocked by our infrastructure; those exceptions may fit better in Operations (perhaps answering my #368 question). Build breaks could land in either bucket&hellip;

**Comment by garath** [comment]
This feels squarely like Operations to me since it's a "figure out a fix for this build break". The Helix Machines epic is funded but not started yet (and does not yet have a start date), so anything with any urgency can't really go into a regular epic. 

I agree that adopting 1ES APIs is appropriate for the Helix Machines epic.

**Comment by dougbu** [comment]
> This feels squarely like Operations

How are we indicating that tie these days❔

----

Happy news: Build break is fixed, unblocking our builds though we need to watch [#20230717.03](https://dev.azure.com/dnceng/internal/_build/results?buildId=2223804&view=results). Think I'll close this once that build completes.

**Comment by dougbu** [comment]
Closing. Up to you if you want to mark this appropriately so that it's tracked for Operations @garath

**Comment by garath** [comment]
> How are we indicating that tie these days❔

Just add the "Operations" label to the issue.
