### ISSUE TITLE
403 errors when running DotNet.Status.Web locally

### ISSUE THREAD

**Issue by mmitche** [dotnet/dnceng#3764]
When running DotNet.Status.Web locally, we get 403 errors attempting to log in and get tokens.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by missymessa** [comment]
@garath do you know if this was fixed by another PR? (Looks like it according to the discussion on @mmitche's PR linked to this)

**Comment by garath** [comment]
Yah this is sorted.
