### ISSUE TITLE
Create documentation for every library shared in dnceng-shared

### ISSUE THREAD

**Issue by dkurepa** [dotnet/dnceng#3777]
We want to have a page on our wiki that describes all libraries we have in dnceng-shared, so people can check really quickly if something they need is already there

**Comment by missymessa** [comment]
In triage, we discussed having a principle for having documentation. We discovered we already had one here: https://github.com/dotnet/dnceng/blob/main/Documentation/Policy/TechnicalDebtPolicy.md#policy--automation-of-checks-wherever-we-can-will-be-important-for-sustainability
