### ISSUE TITLE
Upgrade Azure.Security.KeyVault.Keys

### ISSUE THREAD

**Issue by mmitche** [dotnet/dnceng#3779]
### Release Note Description

Update Azure.Security.KeyVault.Keys to 1.2.3

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by missymessa** [comment]
@mmitche dnceng is on version 4.6.0: https://github.com/dotnet/dnceng/blob/f98c37803a8be4833719dbbd7b991178ce925c4f/Directory.Packages.props#L22

Did you want us to downgrade?

**Comment by mmitche** [comment]
No definitely not. I think the title is wrong for this issue.

**Comment by missymessa** [comment]
I'm going to close this. @mmitche can open a new issue with the correct info when he is able to.
