### ISSUE TITLE
dotnet eng status webhooks intermittently working

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#3785]
1. Log into GitHub as the bot account
2. Navigate to: https://github.com/settings/apps/dotnet-eng-status/advanced
3. See the many failed webhook deliveries. 

The webhook deliveries seem to succeed on redelivery. But the error that the failed ones are experiencing are: 

```
        <h1>An error occurred while starting the application.</h1>
        <div id="stackpage" class="page">
            <ul>
            </ul>
        </div>
```

Affected functionality: 
- Milestone creation for epics
- Forwarding team mentions
- RCA templates
- Timeline issue triage

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by MilenaHristova** [comment]
is the bot account dotnet-bot? Because as I logged in as it and in https://github.com/settings/apps I don't see any apps

**Comment by riarenas** [comment]
Which bot account is used here?

**Comment by riarenas** [comment]
Going to try dotnet-gh-app-bot as that's the closest match according to https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/546/Bots

**Comment by riarenas** [comment]
The account was indeed dotnet-gh-app-bot. There are no failed deliveries in the last 24 hours. Closing.
