### ISSUE TITLE
Get artefacts up to date on on-premise machines

### ISSUE THREAD

**Issue by dougbu** [dotnet/dnceng#379]
As discovered when investigating #368, our artefacts are not up to date on many on-premise machines. This for example means recent changes to helix-scripts/ content were unable to be used on some machines. In particular, `ubuntu.1804.amd64.tiger.perf.[open]` machines are running an older version of `pip` than what we have chosen in helix.base.yaml &mdash; even though linux.yaml shows nothing special for those machines. This old `pip` version was one of the root causes of #368.

Note this is a tactical issue to bring us to a known compliance state and to assist in addressing #368. As part of `Epic: Helix Machines Improvements`, we should fund work to automate as much of this as we can. Running artefact updates on a regular cadence will go a long way toward improving our security stance and avoid problems likely we encountered in the 12 July rollout. But, that strategic approach is somewhat separate from this issue.

### Release Note Category

- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

### Release Note Description

Brought all artefacts on on-premise machines to the latest versions. This includes deploying both new artefect scripts and updating versions (e.g. of Python packages) on those machines.

**Comment by dougbu** [comment]
suspect we'll open a separate issue for the broader need to update all or most artefacts on on-premise machines on a regularly basis. for that future issue, we should remember to clean a few things up before downloading and executing `run.sh`:
- clean up any executing Docker, Python, and emulator processes
- remove `systemctl` entries and similar for Helix startup
- remove the `helixbot` and `helix-runner` users and the `kvm` user group
- perhaps remove or disconnect any data disks
- remove a few directory trees:
  - C:\arcade-tools (on Windows)
  - /etc/helix
  - /etc/helix-prep
  - /etc/local.d (on Alpine, if we have any on-prem Alpine machines)
  - /home/helixbot
  - /Users/helix-runner (on OSX)
  - /usr/local/nodejs
  - /usr/local/v8
  - Windows equivalents of most of the above directories
 - clear the /cores directory on OSX

there's probably more to think about but this should be a fairly good start

**Comment by garath** [comment]
I believe pip is now up to date on all machines.

**Comment by dougbu** [comment]
so, we should close this and merge [!32783](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/32783) &mdash; the "revert revert" PR❔

**Comment by garath** [comment]
Yes, if that was the next step you intended. (I was focused just on the task of updating, the context around it... slipped out of my brain.)

**Comment by dougbu** [comment]
complete❕

**Comment by dougbu** [comment]
let's also start thinking about _keeping_ our artefacts up to date in general and in some automated fashion. could you write that issue up @garath❔ I haven't seen your tooling or thought through anything about how to wrap it in (for example) a weekly pipeline run

**Comment by garath** [comment]
Yes! I'd like to figure out some way to maybe have an automated run that generates an inventory or "state of the machine", run it weekly and put it in a database, and put up a dashboard to let the state be discoverable and also highlight any differences from what's expected (as defined in the helix-machines artifacts definitions).

**Comment by dougbu** [comment]
we _know_ the differences list at the moment is pretty extensive and `pip` was just an urgent example. could you write up two issues, one for an automated inventory (which will be useful b/c searching our YAML isn't a great way to query) and another for fixing things up (essentially, avoiding the requirement to reimage a machine to keep it updated)❔ if I created the issues, they'd basically say "here's the problem" and not "here's a way to think of a solution" 😀

**Comment by dougbu** [comment]
should I file placeholder issues b/4 the long weekend (so we don't forget 😁)❔

**Comment by dougbu** [comment]
filed

- #768 
- #769
