### ISSUE TITLE
repo is missing dotnet tools manifest

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#380]
This repo lacks a dotnet-tools.json. Specifically it would be useful to have it for keeping secret manager up to date in the repo and to make it easier to cycle secrets locally.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
No release notes necessary

**Comment by missymessa** [comment]
Merged!
