### ISSUE TITLE
Investigate failure to login to Grafana prod

### ISSUE THREAD

**Issue by MilenaHristova** [dotnet/dnceng#3832]
Investigate "database or disk is full" error when logging to Grafana prod
![image](https://github.com/user-attachments/assets/cfa3bc79-5247-4288-8603-53310fc2604e)

wiki page for investigating Grafana issues: https://dnceng.visualstudio.com/internal/_wiki/wikis/DNCEng%20Services%20Wiki/977/-Alerts-Azure-Monitor-Alert-Grafana-health-(Availability-Alert)

The [memory metric](https://ms.portal.azure.com/#view/Microsoft_Azure_MonitoringMetrics/Metrics.ReactView/Referer/MetricsExplorer/ResourceId/%2Fsubscriptions%2Fa4fc5514-21a9-4296-bfaf-5c7ee7fa35d1%2FresourceGroups%2Fmonitoring%2Fproviders%2FMicrosoft.Compute%2FvirtualMachines%2Fgrafana8-prod/TimeContext~/%7B%22relative%22%3A%7B%22duration%22%3A86400000%7D%2C%22showUTCTime%22%3Afalse%2C%22grain%22%3A1%7D/ChartDefinition~/%7B%22v2charts%22%3A%5B%7B%22metrics%22%3A%5B%7B%22resourceMetadata%22%3A%7B%22id%22%3A%22%2Fsubscriptions%2Fa4fc5514-21a9-4296-bfaf-5c7ee7fa35d1%2FresourceGroups%2Fmonitoring%2Fproviders%2FMicrosoft.Compute%2FvirtualMachines%2Fgrafana8-prod%22%7D%2C%22name%22%3A%22Available%20Memory%20Bytes%22%2C%22aggregationType%22%3A2%2C%22namespace%22%3A%22microsoft.compute%2Fvirtualmachines%22%2C%22metricVisualization%22%3A%7B%22displayName%22%3A%22Available%20Memory%20Bytes%20(Preview)%22%7D%7D%5D%2C%22title%22%3A%22Min%20Available%20Memory%20Bytes%20(Preview)%20for%20grafana8-prod%22%2C%22titleKind%22%3A1%2C%22visualization%22%3A%7B%22chartType%22%3A2%2C%22legendVisualization%22%3A%7B%22isVisible%22%3Atrue%2C%22position%22%3A2%2C%22hideSubtitle%22%3Afalse%7D%2C%22axisVisualization%22%3A%7B%22x%22%3A%7B%22isVisible%22%3Atrue%2C%22axisType%22%3A2%7D%2C%22y%22%3A%7B%22isVisible%22%3Atrue%2C%22axisType%22%3A1%7D%7D%7D%7D%5D%7D) doesn't indicate any problems

**Comment by MilenaHristova** [comment]
Previous similar issue: https://github.com/dotnet/dnceng/issues/959

**Comment by MilenaHristova** [comment]
```
mhristova@microsoft.com@grafana8-prod:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        29G   29G     0 100% /
devtmpfs        7.9G     0  7.9G   0% /dev
tmpfs           7.9G     0  7.9G   0% /dev/shm
tmpfs           1.6G  150M  1.5G  10% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
/dev/loop0       64M   64M     0 100% /snap/core20/2264
/dev/loop1       64M   64M     0 100% /snap/core20/2318
/dev/loop3       92M   92M     0 100% /snap/lxd/24061
/dev/loop4       39M   39M     0 100% /snap/snapd/21759
/dev/loop5       39M   39M     0 100% /snap/snapd/21465
/dev/sda15      105M  6.1M   99M   6% /boot/efi
/dev/sdb1        32G   17G   14G  54% /mnt
/dev/loop6       92M   92M     0 100% /snap/lxd/29619
tmpfs           1.6G     0  1.6G   0% /run/user/15740529
```

**Comment by davfost** [comment]
We doubled the disk space from the azure portal and were able to logon to the site after the disk size was increased:

Filesystem      Size  Used Avail Use% Mounted on
/dev/root        62G   29G   33G  47% /
devtmpfs        7.9G     0  7.9G   0% /dev
tmpfs           7.9G     0  7.9G   0% /dev/shm
tmpfs           1.6G  1.2M  1.6G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
/dev/loop0       64M   64M     0 100% /snap/core20/2318
/dev/loop3       92M   92M     0 100% /snap/lxd/24061
/dev/loop1       64M   64M     0 100% /snap/core20/2264
/dev/loop2       92M   92M     0 100% /snap/lxd/29619
/dev/loop4       39M   39M     0 100% /snap/snapd/21465
/dev/loop5       39M   39M     0 100% /snap/snapd/21759
/dev/sda15      105M  6.1M   99M   6% /boot/efi
/dev/sdb1        32G   17G   14G  54% /mnt
tmpfs           1.6G     0  1.6G   0% /run/user/13496015

Closing alert
