### ISSUE TITLE
Update Apple Device Scouting queues

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#3838]
Per customer request, we need to update the OS and XCode versions in the osx.amd64.appletv.scouting.open and osx.amd64.iphone.scouting.open queues. 

Desired OS - macOS 14 (latest release)
Desired XCode - 15.4 (*.xip file upload to netcorenativeassets)

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Updates to AppleTV and iPhone scouting queues

**Comment by matouskozak** [comment]
fyi: @ivanpovazan

**Comment by ilyas1974** [comment]
This has been completed. We will be performing a larger update to our Mac infrastructure after .NET 9 releases.
