### ISSUE TITLE
Review Grafana project to see if it has ARM instruction for the VM deployment of grafana8-prod and if instruction exist update them to ensure a 64GB OS drive is assigned instead of a 32GB drive.

### ISSUE THREAD

**Issue by davfost** [dotnet/dnceng#3840]
Review Grafana project to see if it has ARM instruction for the VM deployment of grafana8-prod and if instruction exist update them to ensure a 64GB OS drive is assigned instead of a 32GB drive.

Original thread that led to increasing the drive size:
https://teams.microsoft.com/l/message/19:276707cdcf5d431caaa8792b29bd832d@thread.skype/1724078693504?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=147df318-61de-4f04-8f7b-ecd328c256bb&parentMessageId=1724078693504&teamName=.NET%20Eng%20Services&channelName=FR%20Internal&createdTime=1724078693504

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by garath** [comment]
There's no programmatic deployment for the Azure resources. There are scripts that set Grafana up on an existing VM ([here](https://github.com/dotnet/dnceng/tree/main/src/Monitoring/grafana-init)), but nothing that builds the VM or its friends.

**Comment by davfost** [comment]
Based on @garath comment above and what I am finding in my searches it looks like there is no deployment automation that would alter the drive size of the VM.

As such I am closing the issue without further action.
