### ISSUE TITLE
Add RHEL 8 queue(s)

### ISSUE THREAD

**Issue by richlander** [dotnet/dnceng#3867]
RHEL 7 is now EOL (per our purposes). Context: https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux/rhel-7-end-of-maintenance

We need to move all RHEL testing for all supported .NET versions to RHEL 8 but we don't have a RHEL 8 queue.

Here is a PR I created to move the test legs. I didn't realize the lack of a RHEL 8 queue when I started. Ooops.

https://github.com/dotnet/runtime/pull/105063

**Comment by dougbu** [comment]
@richlander you're now testing w/ CentOS Docker containers. is a RedHat 8 test queue still useful❓

/cc @ilyas1974

**Comment by richlander** [comment]
Great question. I would like to skip this if we could. I propose we wait until we have a pressing need.
