### ISSUE TITLE
Helix VMs are not heartbeating

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#3900]
We are currently not seeing any heartbeats for VM based queues, although our scale sets and CPU quota are maxed out.

https://github.com/dotnet/dnceng/issues/3898
https://github.com/dotnet/dnceng/issues/3899

are directly related to this.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Rollback "Manage Identity Storage Account & Packages bumps" PR from Helix Machines

**Comment by riarenas** [comment]
We are starting to see recovery and new machines created after https://dev.azure.com/dnceng/internal/_build/results?buildId=2525609&view=results completed are now heartbeating. Once the system has experienced full recovery I'll close this and write up the RCA.

**Comment by riarenas** [comment]
Systems are recovered, RCA will be available through #3907

**Comment by chcosta** [comment]
Re-opening just so I can use this issue for the rollback PR
