### ISSUE TITLE
`Report test repository issue` button bad URL

### ISSUE THREAD

**Issue by dkurepa** [dotnet/dnceng#3950]
A customer reported that clicking the `Report test repository issue` button on GH checks brings up an invalid URL. We should investigate and fix this.
![image](https://github.com/user-attachments/assets/cad87725-53d7-43f8-8a99-08285adfadc0)
https://helix.dot.net/ki/new/pr=https%3A%2F%2Fgithub.com%2Fdotnet%2Fruntime%2Fpull%2F106965&repository=dotnet%2Fruntime&build=https%3A%2F%2Fdev.azure.com%2Fdnceng-public%2Fcbb18261-c48f-4abb-8651-8cdcb5474649%2F_build%2Fresults%3FbuildId%3D795134&labels=Known%20Build%20Error%2Cblocking-clean-ci&build-leg=System.Numerics.Tensors.Tests.TensorSpanTests.TensorExtensionsTwoSpanInFloatOut%3CSingle%3E%28tensorPrimitivesOperation%3A%20TensorPrimitivesTwoSpanInTOut%601%20%7B%20Method%20%3D%20Single%20Distance%28System.ReadOnlySpan%601%5BSystem.Single%5D%2C%20System.ReadOnlySpan%601%5BSystem.Single%5D%29%2C%20Target%20%3D%20null%20%7D%2C%20tensorOperation%3A%20TensorTwoSpanInTOut%601%20%7B%20Method%20%3D%20Single%20Distance%5BSingle%5D%28System.Numerics.Tensors.ReadOnlyTensorSpan%601%5BSystem.Single%5D%20ByRef%2C%20System.Numerics.Tensors.ReadOnlyTensorSpan%601%5BSystem.Single%5D%20ByRef%29%2C%20Target%20%3D%20null%20%7D%29

**Comment by missymessa** [comment]
@dkurepa do you know the PR that this originated from?

**Comment by dkurepa** [comment]
Hey @missymessa, here's the link to the customer message where all the info is available: https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1725570769627?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1725570769627&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1725570769627.
Should have put it here in the first place, my bad

**Comment by missymessa** [comment]
@dkurepa I'm not seeing an issue matching that screenshot in the thread you linked. Was it a different thread?

**Comment by chcosta** [comment]
Report test infrastructure issue is also a bad url.  Investigating

**Comment by chcosta** [comment]
Validated, this is now [fixed](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/44431)with the latest helix-service rollout
