### ISSUE TITLE
`No valid signing identities found in the keychain` when running in osx queues

### ISSUE THREAD

**Issue by dkurepa** [dotnet/dnceng#3953]
A customer reported that they're getting a `No valid signing identities found in the keychain` error when trying to run tests in `osx.amd64.iphone.scouting.open` and `osx.amd64.appletv.scouting.open`. Following instructions https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/862/Apple-(iOS-tvOS)-signing-certificates I saw that we have `0 valid identities`. The next step would be to open the keychain and investigate but I had issues doing so with the passwords that are on the devices

**Comment by dkurepa** [comment]
I was able to open the keychain with the password in a KV. The certificates were expired (we missed these queues last year), so I just rotated them

**Comment by matouskozak** [comment]
I tried the queues and I'm now getting:
```Signing /tmp/helix/working/A7370925/w/AAFD0926/e/System.Runtime.Tests.app
    "/Users/helix-runner/Library/Keychains/signing-certs.keychain-db"
security: SecKeychainUnlock signing-certs.keychain-db: The user name or passphrase you entered is not correct.
```

**Comment by dkurepa** [comment]
I remoted onto DNCENGMAC161 to investigate. I looked at the keychain password and it had no weird characters, just numbers and letters. When I tried to use it to unlock the keychain, like in https://github.com/dotnet/arcade/blob/a2142f04aaf08e4f08db9175aada7a822b1313be/src/Microsoft.DotNet.Helix/Sdk/tools/xharness-runner/xharness-runner.apple.sh#L101, it did not work. Interestingly, the artifact that's installing these certificates unlocks the keychain, and doesn't lock it https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines?path=/artifacts/macos-signing-certs/macos-signing-certs.sh. Maybe we should just manually go to every machine in the queue and unlock the keychain?

**Comment by oleksandr-didyk** [comment]
> Tried re-run the signing certificate artifact and validate status on `DNCENGMAC163` and it seems to have worked. Will do the same with the other machines tomorrow

Did the same for all machines in the `osx.amd64.iphone.scouting.open` and `osx.amd64.appletv.scouting.open` queues

**Comment by oleksandr-didyk** [comment]
@matouskozak the machines should be fixed now, please let us know if you run into this issue again
