### ISSUE TITLE
Investigate (and fix) intermittently failing scenario test in Helix Service

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#4122]
![image](https://github.com/user-attachments/assets/92d19ff5-f0fb-4ca4-9e36-b4479bbb6fa5)

Error message: Expected stream not to be <null> because the snapshot 'SnapshotId' was retrieved..

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by epananth** [comment]
This test works upon retry. Going to close this
