### ISSUE TITLE
netcoreinternalassets-sas-read needs to be managed by secret manager

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#4163]
the secret with this name is used during the [on-premises deployments for helix-machines](https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines?path=/src/PrepareOnPrem/scripts/driver/driver.py&version=GBmain&line=41&lineEnd=42&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents), but it's not being managed through secret manager, and didn't have the correct set of access scopes when it was created manually. This secret's configuration should be similar to the existing configuration for [netcorenativeassets-sas-read](https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines?path=/.vault-config/helixprodkv.yaml&version=GBmain&line=146&lineEnd=147&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) but it should target the storage account netcoreassetsinternal.blob.core.windows.net.

We should also make sure that the `netcorenativeassets-sas-read` variable is still needed, as we should no longer be downloading private blobs from the netcorenativeassets storage account.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description
No release notes necessary

**Comment by riarenas** [comment]
I would look at the history to see how it was configured, and if we still need the new sas to exist, it should be in secret manager.

**Comment by missymessa** [comment]
> I would look at the history to see how it was configured, and if we still need the new sas to exist, it should be in secret manager.

Yes, I just wanted to document that it was already removed. :)

**Comment by missymessa** [comment]
PR: https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/44780
