### ISSUE TITLE
`eng/common/native/install-cmake.sh` Incompatible with macOS in arcade-validation

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/dnceng#4204]
In https://github.com/dotnet/arcade-validation/pull/4575, I attempted to add a macOS leg to arcade-validation. This is needed to complete https://github.com/dotnet/arcade/issues/14431, which is focused on enabling signing on Mac and Linux machines.

Upon running the new macOS leg, the build fails with the following errors:
```bash
/Users/runner/work/1/s/eng/common/native/install-cmake.sh --baseuri https://netcorenativeassets.blob.core.windows.net/resource-packages/external --installpath /Users/runner/work/1/s/.tools/bin --version 3.11.1
downloading to: /Users/runner/.netcoreeng/native/temp/cmake-3.11.1-MacOS-x86_64.tar.gz
Downloading https://netcorenativeassets.blob.core.windows.net/resource-packages/external/macos/cmake/cmake-3.11.1-MacOS-x86_64.tar.gz
extracting from  /Users/runner/.netcoreeng/native/temp/cmake-3.11.1-MacOS-x86_64.tar.gz to /Users/runner/work/1/s/.tools/bin/cmake/3.11.1
Extracting /Users/runner/.netcoreeng/native/temp/cmake-3.11.1-MacOS-x86_64.tar.gz to /Users/runner/work/1/s/.tools/bin/cmake/3.11.1
Creating directory: '/Users/runner/work/1/s/.tools/bin/cmake/3.11.1'
Extracting archive
Generating '/Users/runner/work/1/s/.tools/bin/cmake.sh' shim
/Users/runner/work/1/s/eng/common/native/common-library.sh: line 154: Write-PipelineTelemetryError: command not found
/Users/runner/work/1/s/eng/common/native/install-cmake.sh: line 113: Write-PipelineTelemetryError: command not found
```

After speaking with @dougbu - we have discussed the following options to fix the build error:
1. update the macOS package to match the Linux package's layout
2. extend the install-cmake.sh script to support either package layout
3. choose yet-another tool -- hopefully one w/ archive layouts that match between Linux and macOS

It was also discussed that something other than `cmake-test` may be chosen as the second tool.

### Release Note Category

- [ ] Feature changes/additions
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements

### Release Note Description

Removed test-related `native-tools` section from arcade-validation's global.json in 'main' branch.

**Comment by ellahathaway** [comment]
I think a workaround for this would be to not run the problematic scripts on macOS. This is what I've done locally, and it seems to work as the build and tests succeed. This of course depends on the machine already having cmake installed, but it's worth a shot to try in CI.

**Comment by ellahathaway** [comment]
@dotnet/dnceng - This is blocking signing work for Unified Build, so I'm going to need a fix for this soon. Can I please get input on the problem and a potential solution? Thanks in advance.

**Comment by dougbu** [comment]
fixed in dotnet/arcade-validation#4626. filed #4369 for any follow-up we may choose to do around native tool testing in arcade-validation's 'main' branch

will close this issue either immediately once @ellahathaway confirms fix was only needed in 'main' or after backporting to (some of) the servicing branches

**Comment by ellahathaway** [comment]
Validated in https://github.com/dotnet/arcade-validation/pull/4624 that the fix works. Thanks, Doug.

**Comment by ellahathaway** [comment]
This fix is currently only needed in main.
