### ISSUE TITLE
Grafana alerting is not opening GitHub issues

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#4279]
Currently two active alerts with no issues being open: https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/introduction/introduction?orgId=1&viewPanel=9

Before closing this issue, even if the alerts are no longer active, please fix the functionality that is supposed to open issues so we are not blind to problems in the infrastructure.

**ROOT ISSUE:**

The Web Hooks using the uri 'https://dotneteng-status.azurewebsites.net/api/alert' defined for notification channels on the grafana site are no longer working (expired/revoked)

https://dotnet-eng-grafana.westus2.cloudapp.azure.com/alerting/notifications

**CONFIRMING ISSUE IS RESOLVED:**

Review all notification channel definitions and verify that all channels pass the 'Test' operation to verify connection to the notification streams are valid.

Select Each Channel:
![Image](https://github.com/user-attachments/assets/702b1db1-7f0c-4ac4-837f-f76d3b6e3183)

For Each Channel Click The Test Button At The Bottom Of The Instruction Page Verify Result Is Green Not Red:

![Image](https://github.com/user-attachments/assets/01135ea0-9bf1-4566-baea-111761360600)

Completion criteria:
* [ ] The notification channel testing feature in Grafana opens a new test issue in the GitHub repository
* [ ] A real alert opens a new issue in the GitHub repository
* [ ] Updates to the alert status are reflected as updates to the GitHub issue opened in the above checkbox

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by ilyas1974** [comment]
Alert has been investigated and closed. Closing the corresponding github issue.

**Comment by riarenas** [comment]
Please stop closing this issue until we have evidence that the automation that opens github issues when a grafana alert fires is fixed.

**Comment by davfost** [comment]
The tokens use to authenticate to the status site appear to be invalid. I was able to test using a personal token but I don't think we should use individual human identity tokens. We will need to discuss this at Ops Standup to determine what account should be used to generate tokens here.

**Comment by davfost** [comment]
All notification channels for both Staging and Production have been updated and pass all tests now.

I am working on the backend key vault updates to ensure deployment logic continues to function.

**Comment by davfost** [comment]
NOTE: The 'Test' operations generated matching GitHub issues so that should confirm the Status Site to Gitub connection is still good.

**Comment by davfost** [comment]
Ok the all grafana notification channel tests are passing and I have seen a real github alert be created from production.

https://github.com/dotnet/dnceng/issues/4295
