### ISSUE TITLE
Disable grafana external images

### ISSUE THREAD

**Issue by chcosta** [dotnet/dnceng#4283]
Disable grafana external images

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description
Disable grafana external images

**Comment by garath** [comment]
For helix-service: [!44579](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/44579)

**Comment by garath** [comment]
For dotnet-release: [!44580](https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/44580)

**Comment by garath** [comment]
These three PRs should cover everything. I found no other references in my searches.
