### ISSUE TITLE
Helix Systems not updating as expected.

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#4331]
According to grafana (https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/queueOverview/on-premises-helix-queue-status?orgId=1), we have ~340 systesm that have not been updating helix as expected. Can you please investigate what is going on with these systems.

**Comment by premun** [comment]
| Queue | Count |
| --- | --- |
| windows.11.amd64.android.open | 142 |
| windows.11.amd64.cet.open | 45 |
| windows.11.amd64.viper.perf | 44 |
| windows.11.amd64.tiger.perf | 38 |
| windows.server.arm64.perf | 11 |
| windows.11.arm64.surf.perf | 10 |
| windows.11.amd64.owl.perf | 7 |
| windows.11.amd64.tiger.perf.open | 5 |
| windows.11.amd64.cet | 5 |
| raspbian.11.arm32.iot.open | 3 |
| windows.11.amd64.viper.perf.open | 2 |
| windows.11.amd64.galaxy.perf | 2 |
| windows.11.amd64.pixel.perf | 2 |
| raspbian.11.arm32.iot | 1 |
| windows.10.amd64.client.open | 1 |
| windows.11.amd64.urchin.perf | 1 |
| windows.10.amd64.server2022.es | 1 |

**Comment by chcosta** [comment]
Thanks for the data @premun

**Comment by chcosta** [comment]
Filed icm with DDFun

**Comment by ilyas1974** [comment]
All systems have been updated except for ones with other, known issues.
