### ISSUE TITLE
Fix the build error for python3

### ISSUE THREAD

**Issue by v-zheyan** [dotnet/dnceng#4377]
Here is the build error in helix-machines https://dnceng.visualstudio.com/internal/_build/results?buildId=2568853&view=results. the failures are because Visual Sutdio is installing a newer version of Python than we are installing later in the process. 

Need to update the version of the Python artifact installed on these images from the current version 3.10.11 to instead use version 3.12.7. 

### Release Note Category
- [ ] Feature changes/additions 
- [x] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
No release notes.

**Comment by dougbu** [comment]
Done in [!44572](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullRequest/44572) and rolled out on 11 Nov
