### ISSUE TITLE
Add Xcode 16.1 to `osx.amd64.iphone.scouting.open`

### ISSUE THREAD

**Issue by jkurdek** [dotnet/dnceng#4379]
Xcode version 16.1 added new CLI options for downloading simulators. We added support for this to xharness and we would like to be able to run tests using the new xcode version. Adding Xcode 16.1 to `osx.amd64.iphone.scouting.open` would help us. 

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by matouskozak** [comment]
Could we do the same update for the `appletv` scouting queue for parity?

**Comment by matouskozak** [comment]
We could also update both queues to macOS 15 if possible.

**Comment by matouskozak** [comment]
Based on https://github.com/dotnet/dnceng/issues/4455#issuecomment-2501602464, this can be closed as well. cc: @ilyas1974
