### ISSUE TITLE
Rotate Apple Signing Certificate

### ISSUE THREAD

**Issue by premun** [dotnet/dnceng#4386]
Same as last year (#1515), it's time for us to rotate the certificate associated with our Apple Developer account. Details on what needs to be done can be found at https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/862/Apple-(iOS-tvOS)-signing-certificates. 

As each machine needs to have the new certificate applied to it we would like this work done during Prague business hours - when usage of these machines is low. 

We have until 12/9 to complete this work. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description
No release notes.

**Comment by oleksandr-didyk** [comment]
The certificate expires next Friday:
![Image](https://github.com/user-attachments/assets/5c2f3a3f-81dd-43ba-93b7-7ceec82462a4)

Discussed offline and decided that it would be better to complete the rotation as close to the expiration date as possible, i.e. next week

**Comment by dkurepa** [comment]
List of queues:
 - [ ] macos.arm64.appletv.open
 - [ ] macos.arm64.iphone.open
 - [ ] osx.1015.amd64.iphone.perf
 - [ ] osx.1100.amd64
 - [ ] osx.1100.amd64.appletv
 - [ ] osx.1100.amd64.appletv
 - [ ] osx.1100.amd64.appletv.open
 - [ ] osx.1100.amd64.open
 - [ ] osx.1100.arm64
 - [ ] osx.1100.arm64.appletv
 - [ ] osx.1100.arm64.appletv.open 
 - [ ] osx.1100.arm64.open
 - [ ] osx.12.amd64.appletv.open
 - [ ] osx.1200.amd64
 - [ ] osx.1200.amd64.iphone.open
 - [ ] osx.1200.amd64.open
 - [ ] osx.1200.arm64
 - [ ] osx.1200.arm64.open
 - [ ] osx.13.amd64
 - [ ] osx.13.amd64.appletv
 - [ ] osx.13.amd64.appletv.open
 - [ ] osx.13.amd64.iphone
 - [ ] osx.13.amd64.iphone.open
 - [ ] osx.13.amd64.iphone.perf
 - [ ] osx.13.amd64.open
 - [ ] osx.13.amd64.perf
 - [ ] osx.13.arm64
 - [ ] osx.13.arm64.appletv.open
 - [ ] osx.13.arm64.iphone.open
 - [ ] osx.13.arm64.m1.perf
 - [ ] osx.13.arm64.m2.perf
 - [ ] osx.13.arm64.open
 - [ ] osx.14.amd64
 - [ ] osx.14.amd64.open
 - [ ] osx.14.arm64
 - [ ] osx.14.arm64.open
 - [ ] osx.15.amd64
 - [ ] osx.15.amd64.open
 - [ ] osx.15.arm64
 - [ ] osx.15.arm64.open
 - [ ] osx.amd64.appletv.scouting.open
 - [ ] osx.amd64.iphone.perf
 - [ ] osx.amd64.iphone.scouting.open
 - [ ] osx.amd64.scouting.open
 - [ ] osx.arm64.scouting.open

**Comment by dkurepa** [comment]
Certificates on all on prem apple devices should be rotated now

**Comment by premun** [comment]
This is now done
