### ISSUE TITLE
The windows.vs2022* images are lagging behind significantly

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/dnceng#4403]
See https://github.com/dotnet/sdk/pull/43015/#issuecomment-2456761270 for context on why this comes up now and is blocking.

The latest version of Visual Studio is 17.12 Preview 5 but the `windows.vs2022` images (same for the open queues) have ancient versions of VS on them:

![Image](https://github.com/user-attachments/assets/3d29f888-8323-4b91-b075-444ed636880a)

![Image](https://github.com/user-attachments/assets/cc80fd0d-660f-4b17-a2ab-c0048525b1c7)

![Image](https://github.com/user-attachments/assets/c99523c6-3261-4b32-9bba-686e0a77b9d3)

This is causing issues as MSBuild & NuGet shipped with a bug that cause issues when being used with a newer .NET SDK. Can those images please get upgraded asap? Any idea why those didn't get upgraded in months? Don't we have a dashboard for that with notifications enabled?

From the doc: https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/899/VS2022-Upgrade-Schedule with me

![Image](https://github.com/user-attachments/assets/9d41033d-83b5-49c2-916d-6cbafb2e95ad)

I'm not sure I understand this. How can the "Regular Preview VS" version be older than the "Scouting Release VS" version?

> Regular images (both Release and Preview) are upgraded 2 weeks after Scouting queues by copying the previous Scouting image/version from two weeks previous

As an example, 17.12 Preview 1 released on August 13th. Based on the above statement I would expect our "Regular Preview" image to get updated to that ~3 weeks later which would be early September. Now, two months later we are still on "17.11 Preview 7.0".

**Comment by ViktorHofer** [comment]
@ilyas1974 @dougbu

**Comment by ViktorHofer** [comment]
From the doc:

![Image](https://github.com/user-attachments/assets/9d41033d-83b5-49c2-916d-6cbafb2e95ad)

I'm not sure I understand this. How can the "Regular Preview VS" version be older than the "Scouting Release VS" version?

**Comment by ilyas1974** [comment]
@garath I know you've been working on this issue. Can you please give Viktor an update on your status?

**Comment by MichaelSimons** [comment]
Have Windows containers been considered as an alternative to the overhead of maintaining VMs?  VS can be installed within Windows images.  If defined correctly, rebuilds would always pick up the latest versions.  The [.NET Framework SDK containers](https://github.com/microsoft/dotnet-framework-docker/blob/main/README.sdk.md) may be a good base image or at least a good reference.  One downside is the size of the windows containers.  They are most useful for non-trivial workloads and else require pre-caching.

**Comment by ViktorHofer** [comment]
gentle ping @ilyas1974 @garath

**Comment by ilyas1974** [comment]
Apologies - was out on Friday. The CI build to merge these changes is currently running (https://dnceng.visualstudio.com/internal/_build/results?buildId=2579596&view=results). Once it is successful, we proceed with the roll out of these changes. Plan is to roll out later today.

**Comment by ViktorHofer** [comment]
This now happened, thanks. Can we please put this in on a retrospective. I would really like to better understand why the images lagged behind so much. Also see my other questions in the top post.

**Comment by missymessa** [comment]
@ViktorHofer added this to our Retrospective for next month and invited you to the meeting. https://microsoft.sharepoint.com/teams/netfx/engineering/_layouts/OneNote.aspx?id=%2Fteams%2Fnetfx%2Fengineering%2FShared%20Documents%2FEngineering%20Services&wd=target%28Retrospectives.one%7C3B3A3F21-7897-4C47-9168-43444DAC87E1%2FRollout%20Retrospective%20%2812%5C%2F10%5C%2F2024%5C%29%7CD49E3FFD-ABC0-4982-9E61-380947985A02%2F%29
onenote:https://microsoft.sharepoint.com/teams/netfx/engineering/Shared%20Documents/Engineering%20Services/Retrospectives.one#Rollout%20Retrospective%20(12/10/2024)&section-id={3B3A3F21-7897-4C47-9168-43444DAC87E1}&page-id={D49E3FFD-ABC0-4982-9E61-380947985A02}&end

**Comment by garath** [comment]
VS updates are back on schedule and retrospective has happened. No further action for now.
