### ISSUE TITLE
Helix queue windows.server.arm64.perf heartbeat and deployment issues

### ISSUE THREAD

**Issue by v-parose** [dotnet/dnceng#4410]
All machines currently in the "windows.server.arm64.perf" Helix queue are currently not heartbeating. Looking into the logs the D:\h\logs\install.log file on each of the machines shows the below errors. Those same errors popup in a cmd window before the machine then tries to reboot causing a reboot loop until manually stopped. I have tried to redeploy the helix agent and also wipe and reimaged a machine setting it up for helix using our documentation but the same error appears in the install.log file and a reboot loop starts. Can you please help take a look at this issue? I have left machine DOTCJADE-34 in state for the investigation, please let me know if you need me to gather any additional information from the affected machines. Thank you!

Error seen in install.log file
![Image](https://github.com/user-attachments/assets/f44f9e15-3b11-4c99-8828-43696929f04d)

Helix setup instructions for these ARM windows machines:
https://dev.azure.com/devdiv/Engineering/_wiki/wikis/CNEKB/44149/Windows-on-ARM-Helix-setup

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by riarenas** [comment]
There's a ddfun ICM: https://portal.microsofticm.com/imp/v5/incidents/details/558531114/summary that mentions no repro on the error, and there are 11 machines heartbeating in the queue. I will keep this open until the ICM is resolved.

**Comment by riarenas** [comment]
I still see machines in this queue, and the ICM doesn't report any other trouble running these scripts. Closing
