### ISSUE TITLE
Create light-weight mechanism to determine load source

### ISSUE THREAD

**Issue by markwilkie** [dotnet/dnceng#4414]
Today it is often challenging to know *where* load is coming from in our builds and test runs.  The idea is to add something to telemetry such that we're able to better understand how our capacity if being used.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by missymessa** [comment]
Similar to https://github.com/dotnet/dnceng/issues/4045. Closing.
