### ISSUE TITLE
Fix PowerBI dashboard refresh

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#4428]
We have received notification that a few power BI dashboards have stopped refreshing due to owner changes for the underlying model. Diagnose and fix.

Affected reports:
* KnwonIssuesReports
* Sentiment

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by riarenas** [comment]
> {"error":{"code":"Premium_ASWL_Error","pbi.error":{"code":"Premium_ASWL_Error","parameters":{},"details":[{"code":"Premium_ASWL_Error_Details_Label","detail":{"type":1,"value":"We are unable to refresh the semantic model because the model owner no longer has access to the workspace. Please grant the model owner Contributor (or higher) access to the workspace or take over the semantic model by using an account that has Contributor (or higher) access to the workspace."}}]}}}

I believe there was an ownership change to the model on 11/8 which might be the cause for this error

**Comment by riarenas** [comment]
After adding the current owner to the workspace, and attempting a refresh, a new error shows up

``` 
We are unable to refresh the semantic model because the model uses a data connection configured for Workspace Identity authentication, but the workspace has no identity, or the model owner does not have permissions to use the workspace identity. Please configure a workspace identity and make sure the model owner has Contributor (or higher) access to the workspace, or use a different authentication method.
```

**Comment by riarenas** [comment]
KnownIssuesReports is fixed. Sentiment still has the above errors.

**Comment by riarenas** [comment]
Speaking with the previous owner, they mentioned they believe the authorization method for the application insights connection used to be oauth based, wasn't sure. I attempted to use that auth type, and it triggered an interactive entra ID auth for my identity, which then failed to work. I'll continue investigating and digging around.

**Comment by riarenas** [comment]
This is now fixed! 

We're still using oauth2 auth. I also re-enabled the daily refresh.

**Comment by Mabdelhalim79** [comment]
What did you do exactly ? you used OAuth and it worked ? what about the Github link ? should it be anonymous or should i use my account in Github ?
