### ISSUE TITLE
Fix arcade daily pipeline

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#4429]
(Opening this issue manually while https://github.com/dotnet/dnceng/issues/4405 is preventing automatic issue creation)
Fix the arcade-daily pipeline to make sure secrets are properly cycled.

https://dnceng.visualstudio.com/internal/_build?definitionId=1020

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by missymessa** [comment]
Well, fixed one secret... gotta fix another :D

**Comment by missymessa** [comment]
Pipeline is working again. Closing.
