### ISSUE TITLE
Helix-machines-cleaining pipeline failing

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#4438]
This pipeline has been failing with 

> ##[error]D:\a\_work\1\s\CleanPrs.dll(,): error : Cloud error during operation : Resource group 'helix-image-factory-westus' could not be found.

https://dev.azure.com/dnceng/internal/_build?definitionId=855&_a=summary

### Release Note Category
- [ ] Feature changes/additions 
- [x] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Fixing the CleanPrs job

**Comment by missymessa** [comment]
Pretty sure this was me :(  I'll handle it.

**Comment by missymessa** [comment]
PR: https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/44996

**Comment by missymessa** [comment]
This is working again! Closing.
