### ISSUE TITLE
Determine a safe way to connect to Helix VMs

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#4451]
See PRs related to https://github.com/dotnet/dnceng/issues/4447 for more info.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by ilyas1974** [comment]
Documentation updated (https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/866/Connecting-to-Azure-VMs-via-VPN).
