### ISSUE TITLE
Update scouting queues

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#4455]
Per request from the customer, we need to update our scouting queues to the latest release version of macOS 15, XCode 16 and iOS 18. Using this issue to track the work.

**Comment by ilyas1974** [comment]
https://portal.microsofticm.com/imp/v5/incidents/details/565811288

**Comment by matouskozak** [comment]
Can this replace the older issue https://github.com/dotnet/dnceng/issues/4379? @jkurdek

**Comment by jkurdek** [comment]
@matouskozak if this means that we gonna have a XCode version >= 16.1 there - absolutely!

**Comment by ilyas1974** [comment]
The systems in our 3 scouting queues have been updated to macOS 15, XCode 16.1 and iOS 18. Closing work item

| Queue | Machine |
| :-----| :-----:|
osx.amd64.scouting.open | dci-mac-build-292
osx.amd64.scouting.open | dci-mac-build-293
osx.amd64.appletv.scouting.open	| DNCENGMAC091
osx.amd64.iphone.scouting.open	| DNCENGMAC160
osx.amd64.iphone.scouting.open	| DNCENGMAC161
osx.amd64.iphone.scouting.open	| DNCENGMAC162
osx.amd64.iphone.scouting.open	| DNCENGMAC163
osx.amd64.iphone.scouting.open	| DNCENGMAC164
