### ISSUE TITLE
Consider migrating DotNet.Status.Web webhooks to GitHub Workflows

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#454]
Initial Investigation: 
- [ ] Is it worth doing? We have multiple repos that utilize the DotNet Status Web GitHub app that would need to be updated to use the workflows. From my initial understanding, the workflows are a file that are added to the repository directly. However, if functionality needs to be shared across multiple repos, is it worth creating individual files that would need to be updated each time a change is made, with the risk of the functionality drifting if changes are made independently of wherever the source workflow file is stored? 
- [ ] Determine how we would work with the secrets. https://docs.github.com/en/actions/using-workflows/about-workflows#storing-secrets. Is using the default secret good enough, or would we need to create one specifically for workflows? Will we need to build out rotation functionality in Secret Manager for these secrets? How would they get synced across all repos that are using this? 
- [ ] If workflow files are stored centrally and dependency flowed to consuming repos, how would we want to deal with existing logic that is opt-in for repos via config file? 

Work: 
- [ ] Migrate logic in the GitHubHookController in DotNet.Status.Web to utilize GitHub Workflows instead of the webhook. 

Things to consider: 
- [ ] Multiple repos use the DotNet Status Web GitHub app. Ensure that all workflows are able to be consumed by repos using the webhooks. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by dougbu** [comment]
> However, if functionality needs to be shared across multiple repos, is it worth creating individual files that would need to be updated each time a change is made, with the risk of the functionality drifting if changes are made independently of wherever the source workflow file is stored?

this is less of an issue than you likely imagine. for example, <https://github.com/dotnet/arcade/blob/main/.github/workflows/backport-base.yml> contains all the complicated scripting but <https://github.com/dotnet/aspnetcore/blob/main/.github/workflows/backport.yml> is happy using that template.

> Is using the default secret good enough, or would we need to create one specifically for workflows?

the default secret can do whatever the `permissions:` allow it to do w/in the repo where the top-level action is configured.

note _reading_ from another repo just works if that one is public e.g., <https://github.com/dotnet/aspnetcore/blob/main/.github/workflows/runtime-sync.yml> reads from dotnet/runtime.

also, numerous things may not immediately seem possible are easily done w/ either existing GitHub apps and integrations e.g., to AzDO or other actions from <https://github.com/marketplace?type=actions>. (need to fork the action into dotnet/ and get @mmitche to review it if it's not already forked and GitHub didn't write it.)

**Comment by riarenas** [comment]
Triage: what's the ROI of doing this work?

**Comment by missymessa** [comment]
My opinion is that things with the webhook work at the moment, but it may be worthwhile to use them for new functionality in the future. My one concern is the fact that if we have logic that needs to span multiple repos, keeping them consistent would be more difficult to do.

**Comment by missymessa** [comment]
I'm going to close this issue for now. If it comes up again where we can do something with the workflow over a webhook, we can explore it then.
