### ISSUE TITLE
Add Helix queues for Android API 33 and 34

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/dnceng#467]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Right now the latest Android queue on Helix is ubuntu.2204.amd64.android.32, however 33 was released last year and 34 will be in a few months. Please add queues for these Android versions.

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
- Added  ubuntu.2204.amd64.android.33 and  ubuntu.2204.amd64.android.34 queues

**Comment by ilyas1974** [comment]
Thanks Alex, I will get this into the pipeline.

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/33116
