### ISSUE TITLE
Update label for AzDO work items 

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#468]
We need to update the label that is currently associated with the AzDO work items being mirrored to github from "FROps" to "Compliance" to align with our newly defined Ops group. 

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements

### Release Note Description
Update GitHub issue labelling to reflect most recent view of "Operations".

**Comment by garath** [comment]
Ah, I need to also update all the automation that applies labels too.
