### ISSUE TITLE
Remove XAML and Reunion Helix Queues

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#470]
The XAML and Reunion teams have moved away from testing using helix. 

Per request from customer, please delete the following queues from Helix. 

- windows.10.amd64.client20h2.xaml
- windows.10.amd64.clientrs5.open.xaml 
- windows.10.amd64.clientrs5.xaml
- windows.11.amd64.client.open.xaml
- windows.11.amd64.client.xaml
- windows.10.amd64.client.open.reunion
- windows.10.amd64.client.reunion
- windows.10.amd64.client20h2.open.reunion
- windows.10.amd64.client20h2.reunion
- windows.10.amd64.clientrs5.open.reunion
- windows.10.amd64.clientrs5.reunion
- windows.11.amd64.client.open.reunion
- windows.11.amd64.client.reunion
- windows.amd64.server2022.open.reunion
- windows.amd64.server2022.reunion

### Release Note Category
- [X] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Remove XAML and Reunion Queues from Helix

**Comment by missymessa** [comment]
PR here: https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/32886

**Comment by AlitzelMendez** [comment]
this already rolled out :) 

I will take a look if anything needs to be removed from Grafana

**Comment by AlitzelMendez** [comment]
we are still monitoring the quota consumption of xaml and reunion queues: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service?path=/src/ServiceFabric/AutoScaler/ProcessAutoScaleService/Configs/AutoScaleQuotaConfigProd.json&version=GBmissymessa-13585&line=7&lineEnd=8&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

should we stop monitoring this @ilyas1974 ?

**Comment by ilyas1974** [comment]
As we've removed the queues, we should also remove the subscriptions from any of our tooling.

**Comment by AlitzelMendez** [comment]
PR for removing the subscriptions from the austocaler: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/33242
