### ISSUE TITLE
Deprecate tasks in arcade-extensions

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#507]
### Context

Even though "no one is using" the Azure DevOps tasks anymore, the code still exists in the [arcade-extensions repo](https://github.com/dotnet/arcade-extensions/tree/main/src/tasks), and thus, must be maintained per CG rules. To eliminate the need for this maintenance, we should delete the code for the tasks and be clear about the deprecation of the API (for future devs to not have to do the same exercise of figuring out why the methods are a no-op).

Note: The tasks are still a part of servicing branches, so they will continue to "be used" by those branches, but are not used by any current branches

### Historical Context

The SendStartTelemetry and SendEndTelemetry tasks eventually feed data into the Telemetry API in Helix API. However, all the methods in the Telemetry API are no-ops since circa 2018. These tasks, along with BashOrCmd, were created 5+ years ago to fill a need that wasn't available in Azure DevOps at the time. Since then, the product teams have moved to using functionality in Azure DevOps, thus, there is no longer a need to maintain these tasks. 

### Action Items

- [x] Delete the code for the Azure DevOps tasks in dotnet/arcade-extensions. (Do not delete the repo, as it's still needed for the Helix Artifact extension in Azure DevOps). We will also want to keep a "shell" of the task available in the repo so that when the project is rebuilt and published, the tasks don't disappear and possibly cause breaks for any servicing builds that are still referencing the tasks. Include comments in the remaining "shell" of the tasks to reflect the deprecation status of the tasks. 
- [x] Ensure references to these tasks are removed from Arcade and any documentation.
- [x] Add a comment in the TelemetryController class in Helix API noting the deprecation status and that it's kept around so that callers aren't broken. Additionally, change the API to return a 404 now that it's been deprecated for 5+ years. 
- [x] Update any known code that is currently attempting to use these tasks (clear up any ambiguity of the code's deprecation status)
- [x] ~~Add alerting to Grafana that looks and alerts on usage of the Telemetry API so that we can track down other places that need to have the task removed.~~ Opting to remove everything, so no need to track who's calling it

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description

- BashOrCmd, SendStartTelemetry, and SendEndTelemetry AzDO tasks have been fully deprecated
- Fully deprecating the Helix Telemetry API (endpoints will return 404, now)

**Comment by garath** [comment]
Is asking the pipelines that still use these tasks to stop using them an option?

**Comment by missymessa** [comment]
We can ask them to stop, but we'll probably get more traction making a PR to remove them from the repos ourselves.

**Comment by missymessa** [comment]
PR to deprecate Telemetry API in Helix: https://dnceng.visualstudio.com/internal/_git/dotnet-helix-service/pullrequest/32995

**Comment by missymessa** [comment]
PRs for other repos: 
- https://github.com/dotnet/spark/pull/1157

**Comment by missymessa** [comment]
PRs for other repos: 
- https://github.com/dotnet/spark/pull/1157

**Comment by missymessa** [comment]
PRs submitted to internal repos; email sent to Partners alerting folks of the total deprecation. Will aim to merge all deprecation PRs at the end of Aug 2023.

**Comment by missymessa** [comment]
PR to remove to the tasks was merged. The extensions were updated on the AzDO marketplace. Closing this issue.
