### ISSUE TITLE
Build Monitor to monitor CI for dotnet/versions

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#526]
Let's make sure we have monitoring around the CI pipeline for this repo. Looks like it's been broken for a while an no one was aware of it. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by riarenas** [comment]
This issue is a trap!

It involves:
* Adding multi organization support to build monitor (currently only supports one azdo organization)
* Adding new secrets to the build monitor configuration
* Adding a new section for dnceng-public to the configuration files for build monitor.

**Comment by riarenas** [comment]
higher priority workitems mean I'm currently not working on this.

**Comment by missymessa** [comment]
Replacement for old Maestro is currently in the works https://dnceng.visualstudio.com/internal/_workitems/edit/6145, so closing this issue.
