### ISSUE TITLE
SSL Cert for Grafana has expired

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#531]
Per notification from our customers, it appears that the SSL Cert associated with dotnet-eng-grafana.westus2.cloudapp.azure.com has expired.

**Comment by epananth** [comment]
registered domain, for the cert. We will have to wait 3 days for approval

**Comment by ilyas1974** [comment]
related to #545

**Comment by garath** [comment]
Grafana prod is now good. I've reconfigured the cert for the new provider and set to auto-renew.

**Comment by garath** [comment]
New docs on this process in [!33220](https://dev.azure.com/dnceng/internal/_git/dotnet-eng-wiki/pullrequest/33220)

**Comment by garath** [comment]
dotnet/dnceng#590 is another, more general representation of this problem. It should be resolved along with this.

**Comment by garath** [comment]
Actually, this issue is about Grafana Prod, which is now updated and working properly. I'm going to close this issue as resolved and continue other certificate work in #590.
