### ISSUE TITLE
Close async triage channel

### ISSUE THREAD

**Issue by garath** [dotnet/dnceng#558]
The async triage tool is no longer needed in the Now Times. Close the Teams channel, stop running the tool, and shut down any other related items that are no longer needed (and enumerate those items here).

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [X] Internal Infrastructure Improvements
### Release Note Description
No release notes.

**Comment by riarenas** [comment]
Asked @markwilkie for help deleting the Teams channel

https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/34913 has my initial attempts at deleting the code for the tool.

Will now go and spelunk for issues that we can close and I will reference this issue.

**Comment by riarenas** [comment]
Deleted the following wiki pages:

* https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/544/Async-Triage-(Experiment)
* https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/958/Async-Triage
* https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/620/async-triage-core-eng13288

Removed mention of the async triage tasks in https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki?wikiVersion=GBwikiMaster&pagePath=/Documentation/Operations&pageId=970

**Comment by riarenas** [comment]
> Will now go and spelunk for issues that we can close and I will reference this issue.

I came back with nothing. It looked like all the async triage related issues had already been closed. Verified with @missymessa if she remembered anything we might have left behind, but nothing came to mind.

**Comment by riarenas** [comment]
Teams channel has been deleted.

I think the only pending change is to get some eyes and then merge the PR that deletes the tooling from helix-service.

**Comment by riarenas** [comment]
Code has been deleted, docs have been removed, Teams channel has been deleted. Bye Async triage!
