### ISSUE TITLE
Reenable perftiger172

### ISSUE THREAD

**Issue by dougbu** [dotnet/dnceng#559]
Per @LoopedBard3's [request](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1692041134266?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1692041134266&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1692041134266), we off-lined the perftiger172 machine in ubuntu.2204.amd64.tiger.perf. This machine should be reenabled sometime soon.

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

:grin:

**Comment by premun** [comment]
Machine got enabled as per the Teams conversation
