### ISSUE TITLE
Update VS Scouting Preview Queue to 17.8 Preview 1

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#563]
Per request from our customers, please update the VS Preview Scouting queue (Build.Windows.Amd64.VS2022.Pre.Scout.Open) to version 17.8 Preview 1. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
(no notes needed, already announced in Aug 23 rollout)

**Comment by garath** [comment]
Is this an out-of-cycle update or is this how it would deploy based on the usual VS scouting cycle?

**Comment by garath** [comment]
I believe this was done in [!33179](https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/33179) and is rolling-out tomorrow.
