### ISSUE TITLE
New Queues Needed - Ubuntu.2204.arm64.open and Ubuntu.2204.arm64

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#584]
As Ubuntu 18.04 is listed as EOL for regular support (though it is in extended support), we would like to have our customers move their workloads to Ubuntu 22.04 when possible. 

### Release Note Category
- [X] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Add Ubuntu 22.04 ARM queues to Helix

**Comment by ilyas1974** [comment]
@AlitzelMendez is this something you can work on?

**Comment by dougbu** [comment]
[!33266](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/33266) now merged; watching main build [#20230821.04](https://dev.azure.com/dnceng/internal/_build/results?buildId=2249545&view=results)

**Comment by dougbu** [comment]
should roll out 23 August

**Comment by dougbu** [comment]
done 😁
