### ISSUE TITLE
Update labels for alerts

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#652]
Alerts from Grafana are applying old labels to them. They should be updated to use the `Ops - First Responder` label instead of `First Responder` 

(example: https://github.com/dotnet/dnceng/issues/602)

Should also update CG issues to include the `Ops - Compliance` label, as well. 

(example: https://github.com/dotnet/dnceng/issues/626)

### Release Note Category
- [ ] Feature changes/additions 
- [x] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Update label on grafana alerts to "Ops - First Responder"

**Comment by ilyas1974** [comment]
First part of this issue is complete - https://github.com/dotnet/dnceng/pull/667
Working on part 2 - Ops - Compliance label for CG.

**Comment by ilyas1974** [comment]
Tags have been updated in the following repos: 
dotnet-arcade
dotnet-arcade-extensions
dotnet-arcade-services
dotnet-arcade-validation
dotnet-helix-machines
dotnet-helix-services
dotnet-xharness
dotnet-xliff-task

**Comment by garath** [comment]
Don't forget these:
- dotnet-dnceng
- dotnet-dnceng-shared
- dotnet-migrate-package

**Comment by ilyas1974** [comment]
changes have been made and merged. closing issue.
