### ISSUE TITLE
Review and set Component Governance notifications for our repos

### ISSUE THREAD

**Issue by tkapin** [dotnet/dnceng#724]
The CG email notifications for our repositories are not set accordingly to the repo ownership.

Specifically:
- email notifications for [dotnet-helix-machines](https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-helix-machines?_a=settings&view=alerts) are sent to both ".NET Engineering Services ProdCon" and "Helix" services
- email notifications for [dotnet-arcade-services](https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-arcade-services?_a=settings&view=alerts) are sent to "Helix" only.

This is clearly not aligned with the repo ownership by the individual teams. Also, I haven't checked the notifications for the other repos owned by our teams.

I'm logging this in the dnceng as we should team up and agree on how the CG notifications should be routed. This is not urgent, but it's important to get this sorted out so we can be sure the CG alerts have the right visibility.

@dkurepa will be the right person to talk about this on my team.

**Comment by garath** [comment]
@dkurepa what are your thoughts here? 

DNCEng doesn't rely on the emails, instead using the Azure DevOps workitems that the tool opens. Its been a while since we've done a proper audit so that would certainly be good (though S360 ensures we wouldn't miss anything.)

**Comment by missymessa** [comment]
ping @dkurepa :)

**Comment by dkurepa** [comment]
Sorry, I missed this. The arcade-services and helix-machines part was resolved in https://github.com/dotnet/arcade-services/issues/2887, where we correctly configured Product Catalogs for the `Helix` and `.NET Engineering Services ProdCon` services. CG is wired up to send notifications to Service Tree Services, so this issue should be resolved
