### ISSUE TITLE
Clean up unused bot accounts

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#734]
- [x] dotnet-mc-bot
- [x] dotnet-mc-bot2
- [ ] dotnet-dumpling-bot
- [x] dotnet-build-bot

will be removed from bots-low team to see if they are still in use. If no "screams" come out of the "scream" test, let's deactivate these accounts. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by mmitche** [comment]
I wasn't able to clean up the secrets in the Helix vault for the mc bots.

**Comment by mmitche** [comment]
dumpling is MIA and totally unrecoverable. Closing as completed.
