### ISSUE TITLE
Add bot for commenting on PRs

### ISSUE THREAD

**Issue by mmitche** [dotnet/dnceng#735]
Add a bot to the dotnet org (no perms except read) that can be used for commenting on PRs (via PR validation).

Name: dotnet-comment-bot
Add a PAT secret, and service connection for the bot into dnceng-public. PAT should be public_repo only.

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

Add a new bot that allows for commenting using PR validation pipelines.

**Comment by riarenas** [comment]
@mmitche Is there anything remaining here?
