### ISSUE TITLE
ValidateSecrets failures in eng services repos

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#740]
We are seeing auth errors during the secret validation stage of the official dnceng build
https://dev.azure.com/dnceng/internal/_build/results?buildId=2256113&view=logs&j=1b26fc61-3fb8-52f6-954f-c497793aab18&t=7406d6b8-afb6-55bb-9ee1-f2266ae71496

### Release Note Category
- [ ] Feature changes/additions 
- [X] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Fixed authentication issues with the secret manager application.

**Comment by riarenas** [comment]
This is the same symptoms as https://github.com/dotnet/dnceng/issues/723, but in this case the pipeline is already using the expected build pool that should be able to auth. I'll start investigating this.

**Comment by riarenas** [comment]
The only difference I can see is the image we use for both pipelines. The failing build was using the [1es-windows-2019 image](https://github.com/dotnet/dnceng/blob/c4a490a89b38b3fc0c6ab9182af5436f95e346c8/eng/deploy.yaml#L21C6-L21C54), while our passing weeklies are using the [1es-windows-2022](https://github.com/dotnet/dnceng/blob/c4a490a89b38b3fc0c6ab9182af5436f95e346c8/azure-pipelines-weekly.yml#L19) image

This does seem like it would matter, so I'll try to hack up a test build that runs this job using the updated image to validate if this is something we should hotfix to unblock deployments.

**Comment by riarenas** [comment]
This came back with a vengeance and seems to be affecting all of our repos now.

**Comment by premun** [comment]
I am on FR and will work on this tomorrow too. One thought - the dnceng-shared is where secretmanager is, I'll try to run the validation there to see if it works. We've recently moved to new set of Azure auth libraries in the repo that get credentials from the env better so maybe that will help.

**Comment by riarenas** [comment]
This is also breaking the weekly pipelines as well.

**Comment by garath** [comment]
> the dnceng-shared is where secretmanager is, I'll try to run the validation there to see if it works

Secret Manager [is in dnceng](https://github.com/dotnet/dnceng/tree/main/src/SecretManager), not dnceng-shared.

**Comment by riarenas** [comment]
The way this is set up:

* The builds use the [dotnet eng services secret manager service connection](https://dnceng.visualstudio.com/internal/_settings/adminservices?resourceId=fcbc38df-3375-4230-b624-33af318f0e3f) as the `azureSubscription` parameter for the azureCLI@2 task. For instance as seen in this repo's weekly pipeline yaml https://github.com/dotnet/dnceng/blob/main/azure-pipelines-weekly.yml#L28
* That service connection is backed by the [dotnet eng services secret manager AD application](https://ms.portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/~/Overview/appId/b48b9c03-b12d-468f-ac1d-6532186a487b)

I verified that:
* The service connection is healthy, and the AD application's secrets are still active and in use.
* Between yesterday and today, the version of our 1es-windows-2022 image was updated from 79.0, which was based on this hosted runner image: https://github.com/actions/runner-images/releases/tag/win22%2F20230804.1  to version 80.0, which is based on this hosted runner image: https://github.com/actions/runner-images/releases/tag/win22%2F20230820.1
* I can't see anything in the changelog for the new public base image that would explain a problem to obtain credentials. 
* Both images use the same version of the Azure CLI as reported in https://dnceng.visualstudio.com/internal/_build/results?buildId=2256404&view=logs&j=1b26fc61-3fb8-52f6-954f-c497793aab18&t=7406d6b8-afb6-55bb-9ee1-f2266ae71496&l=10
```
azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Program Files\Common Files\AzureCliExtensionDirectory'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal
```

There's a difference in where the tool is located in the agent, but it's not clear to me if that should affect this:

* For the good image: `C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd`
* For the failing image: `C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" `

**Comment by riarenas** [comment]
It looks like things might be related to the toolset changes. The image moved from the x86 version of the Azure CLI to the x64 version https://github.com/actions/runner-images/issues/8150, and that broke at least one other customer.

It's still unclear to me why this would cause a difference in obtaining credentials, but the new tooling is probably the root cause of the issue.

**Comment by riarenas** [comment]
I haven't been able to make much progress here. Even using the x64 azure cli I'm able to get secret-manager to work as expected. 

If we need to unblock things quickly, we can change the version of the 1es-windows-2022 image to the last known good: 79.0.0, but this will only buy us until there's another new version.

@premun do you think this might be fixed by the move to the new auth libraries? if so we might be able to revert the image for now while we finish verifying that.

**Comment by premun** [comment]
Thanks for the explanation above, that helps a lot.

To give more context on what I want to try:

- CG is forcing us to move to new `Azure.Identity` libraries which replace some older `Microsoft.Azure.*` auth libraries.
- Based on the [migration guidance](https://github.com/dotnet/dnceng/pull/732/commits/086f26025be1d61cdc1f864abc68fcfa675b0487), these new libraries should make it even easier to get credentials from env. After using these in [several of our repos](https://github.com/dotnet/dnceng-shared/commit/da9b63e8cee2228dc0b333e0ff4c721cc7cb490f), the code did get simplier and things seem to work. For instance we've already deployed Maestro staging using these.
- Looking at the guidance, there is a thing named `AzureCliCredential` which should hopefully pull credentials from the AzureCLI environment better. I am trying this here: [`086f260` (#732)](https://github.com/dotnet/dnceng/pull/732/commits/086f26025be1d61cdc1f864abc68fcfa675b0487) to see if I can get SecretManager going in `dnceng`.

It's a wild guess but the migration needs to happen anyway.

**Comment by premun** [comment]
Ok, so after moving to the new libraries, we at least now have more informative errors:

```
##[error]Unhandled Exception: The user, group or application 'appid=cd8aa9be-8ad5-4a68-98f9-4c7e5c95bc4c;oid=a5528183-acef-46ac-a0fc-02edef759a58;iss=https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/' does not have secrets list permission on key vault 'dotnet-grafana;location=westus2'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287
Status: 403 (Forbidden)
ErrorCode: Forbidden
```

I will keep trying

**Comment by premun** [comment]
Oh wait, I might have been only changing scenario tests there...

**Comment by premun** [comment]
@riarenas I was able to make it work with the new auth libs!

I literally typed out a comment that I couldn't do it while the last attempt was just running and it worked 😅

The new classes allow this:

```csharp
        var creds = new AzureCliCredential(new AzureCliCredentialOptions() { TenantId = ConfigurationConstants.MsftAdTenantId });
        
        var token = await creds.GetTokenAsync(new TokenRequestContext(new[]
        {
            "https://management.azure.com/.default",
        }), cancellationToken);
```

**Comment by riarenas** [comment]
Version  `1.1.0-beta.23451.13` of secret-manager is the first version that uses the new libraries. I will update our repos to use this new version.

**Comment by riarenas** [comment]
I'm using repos that have a weekly build as a signal. The PRs to fix things up for repos are:

* Helix-machines: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/33545
* helix-service: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/33546
* Arcade: https://github.com/dotnet/arcade/pull/14007


Arcade-services and dotnet-release are both correctly configured to receive updates to secret-manager through maestro, so I triggered the subscriptions earlier than the expected Monday auto trigger in hopes that we will fix this before the weekly runs on Monday cause a lot of noise.

* Arcade-services: https://github.com/dotnet/arcade-services/pull/2888#pullrequestreview-1607456674
* dotnet-release: https://dnceng.visualstudio.com/internal/_git/dotnet-release/pullrequest/33294

**Comment by dougbu** [comment]
excellent, we're covered then 😁

do we have an Ops issue somewhere covering creating subscriptions for the repos that don't have them❔ I have considered updating arcade's bits in helix-machines automatically but wasn't previously as worried about dnceng's packages

**Comment by riarenas** [comment]
@dougbu I was in the middle of creating one, but it's scoped to secret-manager: https://github.com/dotnet/dnceng/issues/764

**Comment by premun** [comment]
Seems like we can close this one?
