### ISSUE TITLE
[Landing Page] Add repository info to search timeline

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/dnceng#744]
In multiple occasions when an issue is reported we need to know if this is happening in multiple repositories or if is coming only for one and such, adding this information in the landing page. 

 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Added repository and pipeline information to search timeline results

**Comment by riarenas** [comment]
If it's feasible, can we add the pipeline as well? It'd be good to know if a problem is localized to a single pipeline as well as the repo.

**Comment by AlitzelMendez** [comment]
this has been rolled out. closing!
