### ISSUE TITLE
Offline PERFTIGER120 and PERFSURFX01

### ISSUE THREAD

**Issue by garath** [dotnet/dnceng#75]
Customer request from an [FR Channel request](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1685123443047?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1685123443047&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1685123443047) to offline two machines for an investigation:

- windows.10.arm64.perf.surf/PERFSURFX01
- windows.10.amd64.19h1.tiger.perf/PERFTIGER120

**Comment by garath** [comment]
These are now offline.

**Comment by andriipatsula** [comment]
both machines are enabled.
