### ISSUE TITLE
Secret manager should support expiration dates of GitHub PATs

### ISSUE THREAD

**Issue by mmitche** [dotnet/dnceng#754]
I think secret-manager assumes that the expiration dates are never, and so stores them all as expiring in year 9999. New PATs have a default expiration of 90 days, so we should at least support the ability to enter the expiration date in the tool.

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by garath** [comment]
dotnet/dnceng#3143 added messaging to guide the user in setting this field, so I think this issue can be closed.
