### ISSUE TITLE
$HELIX_CORRELATION_PAYLOAD/reporter/run.py crash 

### ISSUE THREAD

**Issue by jkotas** [dotnet/dnceng#775]
### Build

https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=395322

### Build leg reported

System.ComponentModel.TypeConverter.Tests.WorkItemExecution

### Pull Request

https://github.com/dotnet/runtime/pull/91300

### Known issue core information

Fill out the known issue JSON section by following the [step by step documentation on how to create a known issue](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step)

```json
 {
    "ErrorMessage" : "(core dumped) $HELIX_PYTHONPATH $HELIX_CORRELATION_PAYLOAD/reporter/run.py",
    "BuildRetry": false,
    "ErrorPattern": "",
    "ExcludeConsoleLog": false
 }
 ```

 @dotnet/dnceng

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=395322
**Error message validated:** `(core dumped) $HELIX_PYTHONPATH $HELIX_CORRELATION_PAYLOAD/reporter/run.py`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 9/5/2023 6:13:01 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by dougbu** [comment]
closing because we haven't had a hit in at least a month
