### ISSUE TITLE
dotnet-helix-machines-ci  build broken 

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/dnceng#777]
This is broken for the latest commit https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/32783 that probably needs to get reverted in order to have a green build

we are not able to rollout until this build gets into a green state 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
No release notes required

**Comment by dougbu** [comment]
agree w/ reverting.

when I get back, can `FORCE_QUEUE` the ARM image in yet-another `cryptography` PR and try to get to the bottom of this new Python problem.

**Comment by AlitzelMendez** [comment]
this wasn't enough and I am focused on fixing helix-services, if someone else can take a pick to this would be great

**Comment by garath** [comment]
I'm on ops, I'll take this.

**Comment by dougbu** [comment]
I suspect the relatively new `python` on ubuntu.2204.armarch may be rejecting use of `distutils` in at least some of our validation attempts. that is, my PR wasn't the direct cause of the problems. unfortunately, migrating to avoid `distutils` is painful b/c we have so many `python` versions on our various machines (everything from 3.5 on Ubuntu 16.04 to 3.11 on Windows when we do the "you, Mr. macos-* must act like a bare metal OSX machine" thing in our builds.

**Comment by dougbu** [comment]
filed #813 as a new issue b/c the revert might have solved some issues we were seeing

**Comment by garath** [comment]
@dougbu I think we're good on this now that main is green, yes?

**Comment by dougbu** [comment]
we still have the ubuntu.1804.amd64.android.open.arcade flakiness but let's file a separate issue for that once @ilyas1974 finishes his research

**Comment by ilyas1974** [comment]
So while the original issue for using the v3 is "valid", it is no longer necessary - we have hardened against that particular feature. From what I can tell, the main reason we are still using D_v3 within this sub is quote - we never bothered getting enough D_v4 quota within the staging environment. We do have some, so we can experiment with moving to that SKU to see if the issues you are seeing @dougbu get resolved. If they do, we can take the extra step of obtaining additional V4 quota.

**Comment by dougbu** [comment]
🆗 and much appreciated @ilyas1974. I'll create a new issue about the ubuntu.2204.amd64.android.open.arcade flakiness. resolution will be to move to D_V4 machines.
