### ISSUE TITLE
`Send to Helix` jobs failing because of `AuthenticationException: RevocationStatusUnknown`

### ISSUE THREAD

**Issue by dkurepa** [dotnet/dnceng#783]
Recently, there's been a spike of `AuthenticationException: RevocationStatusUnknown` exceptions our customers are seeing in their Helix jobs
![image](https://github.com/dotnet/dnceng/assets/91743470/46794a4a-2bc8-4f93-b884-987c621e096e)
We should investigate this issue.
We have seen something similar in the past: https://github.com/dotnet/arcade/issues/8703

**Comment by dkurepa** [comment]
Looks like this is happening on the following images: 

ImageName
--
ubuntu-22.04
macos-12
macos-11
windows-2019
build.ubuntu.2204.amd64
windows.vs2022.amd64
1es-ubuntu-2004
build.ubuntu.1804.amd64
build.ubuntu.2004.amd64
windows.vs2019.amd64
windows.vs2022preview.amd64

so basically all

**Comment by garath** [comment]
Assigning to FR.

**Comment by garath** [comment]
On its face this seems like a transient, server-side problem (not helix). Let's monitor for a day and see if it continues.

**Comment by garath** [comment]
The Timeline tables can have duplicate entries. This should be a more precise query:

Execute in [[Web](https://dataexplorer.azure.com/clusters/engsrvprod/databases/engineeringdata?query=H4sIAAAAAAAAA0WNsW7CQBBE+0j8w3S2IwpCbwo6ijTg1NHiW8FivBvd3gU5yseDnQDdSDPzXiM9n0V5457ZZy+/uBw5Mprhi1HXKDhGiwVIA97ZnQ6MIzmKLX9bS0lMd4lS9g/t1C5ajIiTiaITDbWockTzL1lnOQeHKaa0CU/fDRLTuMMKdLByuQjV2Hrue4ryw0jU8SfpUL5W2A93whxbbi1O6a754z6frWVN5fTai5YP1RxvoboCE8Lh0wEBAAA=)] [[Desktop](https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAAA0WNsW7CQBBE+0j8w3S2IwpCbwo6ijTg1NHiW8FivBvd3gU5yseDnQDdSDPzXiM9n0V5457ZZy+/uBw5Mprhi1HXKDhGiwVIA97ZnQ6MIzmKLX9bS0lMd4lS9g/t1C5ajIiTiaITDbWockTzL1lnOQeHKaa0CU/fDRLTuMMKdLByuQjV2Hrue4ryw0jU8SfpUL5W2A93whxbbi1O6a754z6frWVN5fTai5YP1RxvoboCE8Lh0wEBAAA=&web=0)] [[cluster('engsrvprod.kusto.windows.net').database('engineeringdata')](https://dataexplorer.azure.com/clusters/engsrvprod/databases/engineeringdata)]

```kql
TimelineIssues
| where Type == 'error' and Message has 'RevocationStatusUnknown'
| join kind=inner TimelineBuilds on BuildId
| where StartTime > ago(20d)
| summarize take_any(*) by BuildId, RecordId, TimelineId
| summarize count() by bin(StartTime, 1d)
```

StartTime | count_
-- | --
2023-09-07T00:00:00Z | 147
2023-09-06T00:00:00Z | 107

**Comment by garath** [comment]
No occurrences since September 11. Whatever was causing this server-side appears to have been fixed.
