### ISSUE TITLE
Disable Visual Studio automatic updates in helix-machines

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#784]
The VS team has enabled automatic updates of VS extensions. Automatic updates can wreak havoc in CI systems, as seen in https://github.com/dotnet/dnceng/issues/728

The VSSetup team recommends disabling automatic updates and killing any VSIXautoupdate tasks after setup completes.

We should consider adding these additional steps to either our workloads installation artifact, or as a separate artifact.

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Added artifact to disable Visual Studio automatic updates in VS windows images.

**Comment by riarenas** [comment]
To kill the vsix auto update task: `schtasks /change /tn "\Microsoft\VisualStudio\VSIX Auto Update" /disable`

To disable updates altogether, let's attempt the reg keys in https://learn.microsoft.com/en-us/visualstudio/install/configure-policies-for-enterprise-deployments?view=vs-2022

**Comment by riarenas** [comment]
Working on this in this PR: https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/33632

**Comment by garath** [comment]
The new artifact to disable the scheduled update task is working, except that the VSIX Auto Update task is not (consistently?) present at the time the artifact runs. (Can't disable something that isn't even present). 

It does seem to be consistently enabled during the artifact validation stage, hence the build failures we see in this issue. 

Is there perhaps a delay after startup for the task to be scheduled? There are a number of VS workloads set up earlier in the process, are those having some effect? More research is needed.

**Comment by dougbu** [comment]
have you tried running the remediation as part of the first run sequence @garath❔ that should occur on the "real" machine rather than the template that's created in IF

**Comment by garath** [comment]
The misbehaving artifact was found (details in the PR). This has been rolled-out with the October 17 deployment.
