### ISSUE TITLE
dotnet-helix-machines-image-generation broken

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/dnceng#814]
This has been broken for almost 1month.

It seems to be another authentication case: https://dev.azure.com/dnceng/internal/_build/results?buildId=2266787&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=45862c6e-83c5-515f-73e2-e7009eff9f9b

### Release Note Category
- [ ] Feature changes/additions 
- [x] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Fix authentication when talking to ImageFactory

**Comment by garath** [comment]
It is an auth problem but only since the 7th (when the key expired). There may be other problems, of course.
