### ISSUE TITLE
Remove dotnet org from dn-bot-all-orgs-test-r 

### ISSUE THREAD

**Issue by epananth** [dotnet/dnceng#830]
### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

Remove dotnet org from dn-bot-all-orgs-test-r

**Comment by epananth** [comment]
PR https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/33744

**Comment by missymessa** [comment]
What was the requirement for this work? Should we have created new tokens instead? Is this going to break Build Analysis (because it needs to read from both dnceng and dnceng-public)? 

/cc @AlitzelMendez

**Comment by AlitzelMendez** [comment]
it is not going to break build analysisbuild Analysis  uses dnceng and dnceng-public and both are still on the secret, the only one removed was dotnet 

it was removed because the dotnet wasn't no longer visible by dn-bot so the secret was not able to be rotated if we wanted to add this org

**Comment by epananth** [comment]
this was rolled out last week. Closing this
