### ISSUE TITLE
Offline PerfTiger172 in ubuntu.2204.amd64.tiger.perf

### ISSUE THREAD

**Issue by epananth** [dotnet/dnceng#836]
Customer request from an [FR Channel request](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1695154284929?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1695154284929&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1695154284929) to offline the machine for an investigation:

PerfTiger172/ubuntu.2204.amd64.tiger.perf

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by epananth** [comment]
Machine has been disabled

**Comment by garath** [comment]
Machine is now online again.
