### ISSUE TITLE
Disable auto-issue-linking in dnceng Azure DevOps workitems

### ISSUE THREAD

**Issue by garath** [dotnet/dnceng#845]
This feature is incorrectly linking numbers found in GitHub mirror repositories to the unrelated Azure DevOps workitems. This then causes the workitem to be closed incorrectly.

**Comment by garath** [comment]
I believe it's this feature. [Resolve work items on commit](https://learn.microsoft.com/en-us/azure/devops/repos/git/resolution-mentions?view=azure-devops).

Unfortunately, it is a per-repo setting.

**Comment by AlitzelMendez** [comment]
yes, last year I did a bunch of repos manually, but I guess there are new repos 😞

**Comment by riarenas** [comment]
For my understanding. What is the work here? To go into every repository in dnceng/internal and click the setting? or only for repositories owned by engineering services?

**Comment by riarenas** [comment]
This mentions that it's enabled by default on a per-repo basis. https://learn.microsoft.com/en-us/azure/devops/repos/git/resolution-mentions?view=azure-devops#enable-commit-mention-work-item-resolution 

I don't think this is the way to go. Moving this to triage for discussion.

**Comment by riarenas** [comment]
I decided I don't want to champion this in triage. I went through the list of 145 repos with active mirroring enabled and made sure the setting was turned off.
