### ISSUE TITLE
Helix machines out of disk space

### ISSUE THREAD

**Issue by epananth** [dotnet/dnceng#846]
We are encountering quite a few out of disk space errors on Helix and 1ES machines

Here are a few examples : 

1) Bruce Forstall reported in OSX.1200.Amd64.Open [teams link](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1694583199431?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1694583199431&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1694583199431) and [another one](https://dev.azure.com/dnceng-public/public/_build/results?buildId=417137&view=ms.vss-test-web.build-test-results-tab&runId=9135622&paneView=debug&resultId=117545)
2) Jakob Botsch reported in VM windows.10.amd64.open [teams link](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1694015045228?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1694015045228&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1694015045228)
3) Missy reported another one in Ubuntu 20.04 and 18.04 [Github issue](https://github.com/dotnet/dnceng/issues/225)

Suggested next steps : [teams thread](https://teams.microsoft.com/l/message/19:276707cdcf5d431caaa8792b29bd832d@thread.skype/1695217657622?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=147df318-61de-4f04-8f7b-ecd328c256bb&parentMessageId=1695217657622&teamName=.NET%20Eng%20Services&channelName=FR%20Internal&createdTime=1695217657622)
1. Is this happening in both Helix and 1ES machines?
2. 1ES machines are clean machines for every run verify if this fails here too. 
3. Make Helix Client to log message in app insights about the disk space. Link to the [code](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines?path=/resources/helix-scripts/helix/client.py&version=GC266aa38e8a524f5ed2b6420fef7401e10dd27604&line=109&lineEnd=149&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents)
4. Check if we are cleaning up build artifacts properly 

### Release Note Category

- [ ] Feature changes/additions 
- [x] Bug fixes
- [ ] Internal Infrastructure Improvements

### Release Note Description

Reduced the "cache" of retained correlation payloads from `3` to `1` to reduce space usage on Helix VMs.

**Comment by epananth** [comment]
| Machine in question | VM or On prem | Helix or 1ES |  Pipeline |  Notes|
| ---|---|---|---|--|
| OSX.1200.Amd64.Open | On prem | Helix | runtime-coreclr jistress | |
| Ubuntu 20.04 and 18.04 | VM | 1ES | sdk, runtime | out put size of test is roughly 62 GB (solution was to change tier to premium, change sku or attach empty disk|
| windows.10.amd64.open | VM | | runtime-coreclr superpmi-replay |128 GB for VM- 50 GB totally used by the repo |

**Comment by epananth** [comment]
I think we can ignore the 1ES one here, cos its SKU upgrade related. I am going to see if any of these machines are still online so that I can I can bring it down and investigate further

**Comment by premun** [comment]
`dci-mac-build-127` has this:

| Filesystem     |  Size |  Used | Avail Capacity iused | ifree %iused          | Mounted on       |                      |                             |                           |
|----------------|:-----:|:-----:|----------------------|-----------------------|------------------|----------------------|-----------------------------|---------------------------|
| /dev/disk2s1s1 |  99Gi |  22Gi | 17Gi                 | 56%                   | 501138 181182080 | 0%                   | /                           |                           |
| devfs          | 194Ki | 194Ki | 0Bi                  | 100%                  | 672              | 0                    | 100%                        | /dev                      |
| /dev/disk2s4   |  99Gi | 3.0Gi | 17Gi                 | 15%                   | 4 181182080      | 0%                   | /System/Volumes/VM          |                           |
| /dev/disk2s2   | 99Gi  | 312Mi | 17Gi                 | 2%                    | 1178 181182080   | 0%                   | /System/Volumes/Preboot     |                           |
| /dev/disk2s5   | 99Gi  | 111Mi | 17Gi                 | 1%                    | 405 181182080    | 0%                   | /System/Volumes/Update      |                           |
| /dev/disk2s7   | 99Gi  | 55Gi  | 17Gi                 | 76% 1040320 181182080 | 1%               | /System/Volumes/Data |                             |                           |
| /dev/disk2s6   | 113Gi | 11Gi  | 20Gi                 | 37%                   | 102 208143080    | 0%                   | /Volumes/BotDeploy          |                           |
| map auto_home  | 0Bi   | 0Bi   | 0Bi                  | 100%                  | 0                | 0                    | 100%                        | /System/Volumes/Data/home |
| /dev/disk2s1   | 99Gi  | 22Gi  | 17Gi                 | 56%                   | 502236 181182080 | 0%                   | /System/Volumes/Update/mnt1 |                           |

So obviously there is the Data volume that is quite occupied but I have no idea what goes where with these machines

**Comment by premun** [comment]
Also the last row is very suspicious? The numbers don't seem to add up?

**Comment by AlitzelMendez** [comment]
I just took a quick look to dci-mac-build-127, I agree with Premek that is a little bit suspicious, I looked into /System/Volumes/Data to see what is using so much space and basically was
Application (15G is xcode)
Users (15G is helix-runner)
Volumes (11G of a dmg)

but also the space has been low on this machine from all the data that we have so it's hard to see what changed 
<img width="1616" alt="image" src="https://github.com/dotnet/dnceng/assets/6895254/95aa0427-2d49-4455-8506-fd00555f5dac">

but this is not the same scenario for other machines on this queue, so definitely something is off on this one 

### windows.10.amd64.open.rt
 
I found something interesting in this one, please if anyone things that this is not the case or have any ideas to prove this theory share your thoughts.

I looked into the logs of the machine  "(windows.10.amd64.open.rt) -  a00CZGX"  in there I noticed that we were not deleting the correlation payloads at the beginning,  after looking into the helix code we keep the last 3 correlation payloads that we downloaded, after that we start deleting one and we always preserve 3 and delete the excess. 

My theory is that the payloads are getting to big and eating up the space, please see this graph of the free space of some queues from windows.10.amd64.open.rt, this queues ended up with `LowDiskSpace` status

Note: The colors are work items
<img width="1468" alt="image" src="https://github.com/dotnet/dnceng/assets/6895254/91183d6f-236b-4e50-aa9b-7ccc6b372385">

<img width="1449" alt="image" src="https://github.com/dotnet/dnceng/assets/6895254/5dd41e17-9e5f-40a7-aa61-7bd080567ef4">

as you can see they follow a pattern of having enough space and then in big chunks the space decrees, we were looking for something that we were not cleaning up and seems to be that we are not cleaning the correlation payload, at least not immediately.  

Observe this other example (of a machine with no problems) in where after the third one it frees space up:
<img width="1448" alt="image" src="https://github.com/dotnet/dnceng/assets/6895254/2439f6c4-9c89-45b1-8ad0-85a91b104e64">

I will try to proof this theory (by finding a machine in this state, but it doesn't happen that often, as probably three jobs with big payloads needs to run in a row.

### Impact
Additionally I verified that this are the only queues impacted and how many machines were impacted over the last 10 days:

- windows.10.amd64.open.rt: 23 machines impacted out of 14846 machines created over that period of time
- osx.1200.amd64: 1 machines impacted

I know is an issue that is impacting people, I just want to give some context about the impact on this

**Comment by premun** [comment]
These are great measurements, @AlitzelMendez!

Can you maybe check the python code and under which circumstances we delete the correlation payloads? I remember we had this caching but maybe it's smart but not enough?

**Comment by AlitzelMendez** [comment]
> These are great measurements, @AlitzelMendez!
> 
> Can you maybe check the python code and under which circumstances we delete the correlation payloads? I remember we had this caching but maybe it's smart but not enough?

oh I did this :) probably I should had mentioned it, we delete the correlation payload when we have more than 3 folders of correlation payloads:
https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines?path=/resources/helix-scripts/helix/client.py&version=GBmain&line=300&lineEnd=301&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

it can be more than 3 but the *CorrelationFolderRetention* [value is 3](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines?path=/resources/helix-scripts/helix/settings.py&version=GBmain&line=20&lineEnd=21&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) 

so unless I am missing something this doesn't look very smart, we can make it smarter and have a different approach of considering the available space and which is the space that we have committed to keep free for the users

**Comment by AlitzelMendez** [comment]
looks like this was changed some time ago: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/commit/085d3f93379887f48d4a54cf736c7ddb60093bb8?refName=refs/heads/main&path=/resources/helix-scripts/helix/settings.py&_a=contents and for a similar reason https://github.com/dotnet/core-eng/issues/8289

**Comment by premun** [comment]
@AlitzelMendez I won't be in this week anymore as tomorrow is a holiday and Friday we're flying with Tomas so just wanted to close the loop here:

- The MacOS queue needs to wait for the IcM and the two machines brought online
- We should decide what to do about the 3 cached payloads. Should we possibly have an upper limit and keep just 1 if we are over the limit? Something simple like that might work?

**Comment by jakobbotsch** [comment]
Here's a new case that just happened on the windows.10.amd64.open.rt queue, in case you want to take the machine offline and investigate:
https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-92710-merge-0a24a9bf7e1c46fd89/linux-x64/1/console.acafe5ad.log?helixlogtype=result

**Comment by AlitzelMendez** [comment]
thanks @jakobbotsch  I put the machine offline to verify if this is what is happening :)

> @AlitzelMendez I won't be in this week anymore as tomorrow is a holiday and Friday we're flying with Tomas so just wanted to close the loop here:
> 
> * The MacOS queue needs to wait for the IcM and the two machines brought online
> * We should decide what to do about the 3 cached payloads. Should we possibly have an upper limit and keep just 1 if we are over the limit? Something simple like that might work?

I think that will be good enough :) my only question is which number is the limit? which much space are we committed to have available for a new workitem? do we have that information @ilyas1974 ?

as a reference the workitem shared above: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-92710-merge-0a24a9bf7e1c46fd89/linux-x64/1/console.acafe5ad.log?helixlogtype=result had 22GB available when the workitem started

**Comment by ilyas1974** [comment]
Two updates - per https://portal.microsofticm.com/imp/v3/incidents/incident/426721565/summary the mac systems have been re-imaged to utilize the larger disks. 
As to your question about the correlation payloads, do we have any data that shows if a previously cached payload is being used? If it is, I would then back us out to saving 1 as you ( @AlitzelMendez ) suggest.

**Comment by AlitzelMendez** [comment]
@ilyas1974 the plan is to keep only 1 correlation payload if we are under X amount of space, although I don't know which number is X, do you have any idea of the "ideal" space available for a work item?

and I don't know if we have data of us using the cached payloads, I doubt it but let me look

**Comment by ilyas1974** [comment]
I don't but perhaps Jakob who reported the issue can answer that question.

**Comment by jakobbotsch** [comment]
For us, we need up to 50GB (call it 60GB for good measure) space for our largest pipelines.

**Comment by MilenaHristova** [comment]
Another low disk-space error was reported on [FR channel](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1696247786861?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1696247786861&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1696247786861)

**Comment by dougbu** [comment]
[!34191](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/34191) applies the most direct and obvious fix for this issue. reducing the number of cached correlation folders to `1`.

comments about missing OS disks in Teams are concerning and won't be addressed in that PR

**Comment by dougbu** [comment]
I need an approval for !34191 to consider this issue even temporarily resolved for VMs

**Comment by dougbu** [comment]
Core fix (described in **Release Note**) implemented in [!34191](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/34191)
