### ISSUE TITLE
dotneteng-status is down

### ISSUE THREAD

**Issue by garath** [dotnet/dnceng#849]
[dotneteng-status](https://dotneteng-status.azurewebsites.net/) is down. 

Staging is up. 

Once resolved, also add a availability check so that we get notified when it stops responding.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description
Improve Grafana-to-GitHub connection

**Comment by missymessa** [comment]
Works for me! :D

**Comment by garath** [comment]
Still seeing occasional down-ness, though not enough to trigger availability alerts. 

- 1ES Cookie Test, which GETs the index, has seen HTTP 500 twice now
- POSTs to /api/alert are seeing 500

**Comment by garath** [comment]
Related conversation:

[--: `dotneteng-status` is broken /?](https://teams.microsoft.com/l/message/19:276707cdcf5d431caaa8792b29bd832d@thread.skype/1695390606707?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=147df318-61de-4f04-8f7b-ecd328c256bb&parentMessageId=1695390606707&teamName=.NET%20Eng%20Services&channelName=FR%20Internal&createdTime=1695390606707)
posted in .NET Eng Services / FR Internal on September 22, 2023 6:50 AM

**Comment by garath** [comment]
Secrets recycled. The sites appear to be operating as expected.

**Comment by garath** [comment]
This comment made it through the system successfully, confirming that all is well again. https://github.com/dotnet/dnceng/issues/638#issuecomment-1737641668

**Comment by garath** [comment]
Holding until Rollout happens and the (minor) changes make it to Prod.

**Comment by garath** [comment]
The inconsistency in when the site was working is explainable by the "bad VM" found in dotnet/dnceng#638.

Cycling the secrets was necessary but probably not the cause.

**Comment by garath** [comment]
Rollout successful!
