### ISSUE TITLE
dotnet/versions is failing to build 

### ISSUE THREAD

**Issue by epananth** [dotnet/dnceng#858]
[Teams thread](https://teams.microsoft.com/l/message/19:276707cdcf5d431caaa8792b29bd832d@thread.skype/1695411040822?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=147df318-61de-4f04-8f7b-ecd328c256bb&parentMessageId=1695411040822&teamName=.NET%20Eng%20Services&channelName=FR%20Internal&createdTime=1695411040822)

Unable to merge the [PR](https://github.com/dotnet/versions/pull/911)

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by missymessa** [comment]
PR to fix: https://github.com/dotnet/versions/pull/912

**Comment by missymessa** [comment]
Build's fixed.
