### ISSUE TITLE
Determine root cause of dotnet-versions-public-ci build break

### ISSUE THREAD

**Issue by dougbu** [dotnet/dnceng#860]
Starting with [build #20230823.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=383974&view=results), this pipeline was red until @missymessa and @epananth got dotnet/versions#912 into dotnet/versions main branch. From a process POV, that's a long period of redness. However this specific issue is specifically about why both dotnet/versions#899 and dotnet/versions#900 (both at least somewhat related to the build failures) built successfully and [build #20230707.3](https://dev.azure.com/dnceng-public/public/_build/results?buildId=332482&view=results) (after dotnet/versions#900 merged) was successful.

It appears the pipeline was not triggered after dotnet/versions#899 went in (also on 7 July), until 23 August. That's also strange; not sure how to get more information about the gap.

This issue is a follow up to #858.

### Release Note Category

- [ ] Feature changes/additions 
- [x] Bug fixes
- [ ] Internal Infrastructure Improvements

### Release Note Description

We investigated a sequence of failures in the dotnet-versions-public-ci pipeline and &hellip;

**Comment by riarenas** [comment]
There are no longer any broken builds in the history for this pipeline, so there's nothing for me to look at. I suggest retaining builds that need analysis at a later date, such as this one.
