### ISSUE TITLE
grafana notifications not working properly

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#868]
While grafana is generating alerts as expected, the issues we expect to be generated automatically in github are not being created. Please investigate.

**Comment by epananth** [comment]
Spoke to Stu, he said this is related to https://github.com/dotnet/dnceng/issues/849 and he is looking at it

**Comment by epananth** [comment]
Stu fixed this, I am going to close this tomorrow after I validate grafana is creating github issues.

**Comment by epananth** [comment]
this is fixed, closing this
