### ISSUE TITLE
Slowness in Macs

### ISSUE THREAD

**Issue by epananth** [dotnet/dnceng#876]
Investigate slowness in macs

Possible things to investigate 
- [ ] Is there any slowness in queue times 
- [ ] Is there any slowness in test execution times
- [ ] Determine which queues experience these
- [ ] possible solutions for this slowness 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by ilyas1974** [comment]
Changes have been made by the 1ES Mac team to our systems. Currently waiting on information from the product teams.

**Comment by ilyas1974** [comment]
Received confirmation that this issue is resolved.
