### ISSUE TITLE
dependency updates to arcade are blocked

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#880]
The current dependency update PR to arcade is blocked with many errors. We should investigate and fix up.

https://github.com/dotnet/arcade/pull/13998

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by premun** [comment]
I fixed this as it was blocking a person with an FR request
