### ISSUE TITLE
Additional tests around symbol uploader package in arcade-validation

### ISSUE THREAD

**Issue by epananth** [dotnet/dnceng#882]
Historically updating Sybmol uploader task has caused a bit of errors in repos like runtime, installer etc.

We should write some tests around it in arcade validation so that we don't have to test them against product repo everytime there is a change to this package. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by riarenas** [comment]
@epananth can you please elaborate on what kind of validation is missing here and what kind of tests you would like added?

**Comment by epananth** [comment]
Adding @hoyosjs 

He has more info on this

**Comment by riarenas** [comment]
Closing, it's been a while and we don't know what we want to validate. Feel free to reopen once there are concrete scenarios to look at.
