### ISSUE TITLE
Known issue validation doesn't look at the "Build information" section of the known issue when retriggering

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#963]
Currently, we don't retrigger the issue validation if we update the section of the issue called "Build information", and we also don't look at that information when retriggered, instead, after the initial validation, we only look at the "Known Issue Validation" section of the issue. This is the section that the known issue service will fill out itself, so it's strange that we expect users to manually change that for validation.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by riarenas** [comment]
@AlitzelMendez Educated me to the fact that we don't really enforce a "Build Information" section to create a known issue, especially for normal issues that become known issues after the fact. That makes it a bit harder to get consistency here.

**Comment by AlitzelMendez** [comment]
yes, it is hard to get consistency in here as the issue body can change for multiple reasons, until now looks like this constraint hasn't been too problematic, so I will close the issue, but if this becomes problematic, we will need to come up with other solution for this.
