### ISSUE TITLE
[Known issue reporter] Update issue for the reporter should exclusively update the body, is this possible?

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/dnceng#964]
the API method that we are using right now to update the issue for the known issue report, pass the whole information (title, assignees,  labels, etc.)  but we want to explore the option in where the issue body is exclusively update.

The issue that we had was because there were some problems with the Assignees and as we were trying to set all the value the call was failing 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Fixed errors caused by known issue reported updating the whole issue instead of only the body

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/34905

**Comment by missymessa** [comment]
Had to revert these changes :( 

https://github.com/dotnet/dnceng/issues/1436

**Comment by AlitzelMendez** [comment]
this is already covered by: https://github.com/dotnet/dnceng/issues/962 closing
