### ISSUE TITLE
[Known issues] Investigate whether we can look at older build attempts when validating known issue messages

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#965]
When we do the known issue validation to see if the provided known issue blob matches the example build provided, we only look at the latest attempt of the build. It would be helpful for devs if this validation looked at older attempts. 

It's a common scenario for a dev to rerun a build before knowing whether their issue will repro again, while at the same time filing a known issue for future occurrences.

This might be too expensive to get from Azure DevOps, so let's examine whether it's feasible.

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Known issue validation now reviews all the failures in a build, including errors of previous attempts

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/35901

**Comment by AlitzelMendez** [comment]
validated, closing
