### ISSUE TITLE
Helix Machines running Linux experiencing space issues

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#966]
As issue #846 is focused on resolving the issues on the Windows systems, I'm opening a separate issue for the Linux systems.

I have gotten buy off to increase our spend on these systems so whatever we decide to do to increase the space available on these systems has been "approved" - from a budget perspective.

**Comment by ilyas1974** [comment]
To my knowledge, we need to evaluate the SKU that is being used and see if there is a different SKU we should use or if we should add a secondary disk to these queues to meet our customers needs.

**Comment by davfost** [comment]
Correlation Folder retention policies were changed to address space issues by the following PR:

https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/34191
