### ISSUE TITLE
Add Ubuntu 22.04 `.svc` queues for Android emulators

### ISSUE THREAD

**Issue by premun** [dotnet/dnceng#993]
Currently we only have 18.04 which is going away and so we will need new servicing queues for Android emulators: https://github.com/dotnet/dnceng/issues/952

Also discussed here: https://github.com/dotnet/xharness/pull/1081

### Release Note Category
- [X] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Add ubuntu 22.04 servicing images for android 29

**Comment by premun** [comment]
I can take this next week when I'm on SSA

**Comment by premun** [comment]
Oh, I actually am not on SSA. Can someone take this? Maybe @andriipatsula? It should be very straightforward

**Comment by andriipatsula** [comment]
Do you mean to create two images(`ubuntu.2204.amd64.android.29.open.svc` & `ubuntu.2204.amd64.android.29.svc`), based on Ubuntu2204Android29 and ServicingSubscription, similar to what we have for [ubuntu18.04](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines?path=/definitions/shared/linux.yaml&version=GBmain&line=2148&lineEnd=2159&lineStartColumn=1&lineEndColumn=46&lineStyle=plain&_a=contents)?

**Comment by andriipatsula** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/34420

**Comment by andriipatsula** [comment]
PR is merged.
